'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixtures,exact,approval,database,OWNER,OTHER}=require('./helpers/migration-db.cjs');
const M=require('../src/approved-market-migration.js');
const [capsule]=fixtures();
test('migration browser projection preserves investment objects and atomic persistence',async t=>{
 const h=await database();let state,owner=OWNER,response,saves=0,fail=false;
 const base=JSON.parse(capsule.base),protectedData={holding:{shares:13},plans:[{id:'plan'}],orders:[{id:'order'}],discussionState:{current:{body:'immutable original'},history:[{body:'old'}]},technicalReview:{judgment:'original'}};
 const seed=()=>({stocks:[{code:'9999.HK',id:'fixture',...structuredClone(protectedData),...structuredClone(base),marketRevisionReview:{status:'review_required'}}],updatedAt:3});
 const client=M.create({rpc:async()=>response,user:async()=>owner,getState:()=>state,persist:async(next)=>{assert.equal(state.stocks[0].priceHistory[0].provider,'eastmoney');if(fail)throw Error('storage_failure');saves++;assert.equal(next.stocks[0].priceHistory[0].provider,'yahoo')},adopt:next=>{state=next}});
 try{
  await h.stage(capsule);let v=await h.migration('read',{symbol:'9999.HK'});v=await h.migration('approve',approval({...v,capsule}));response=await h.migration('apply',exact(v));
  await t.test('accepts only bound owner and valid synchronized versions',async()=>{state=seed();owner=OTHER;await assert.rejects(client.sync('9999.HK'),/migration_context_invalid/);owner=OWNER;const saved=response;response=structuredClone(saved);response.bundle.technicalData.technicalVersion='0'.repeat(64);await assert.rejects(client.sync('9999.HK'),/migration_versions_invalid/);response=saved;assert.equal(saves,0)});
  await t.test('stale local facts cannot be overwritten',async()=>{state=seed();state.stocks[0].priceHistory[0].close+=1;await assert.rejects(client.sync('9999.HK'),/migration_local_version_conflict/);assert.equal(saves,0)});
  await t.test('storage failure leaves entire in-memory state unchanged',async()=>{state=seed();const before=JSON.stringify(state);fail=true;await assert.rejects(client.sync('9999.HK'),/storage_failure/);assert.equal(JSON.stringify(state),before);assert.equal(saves,0);fail=false});
  await t.test('adopts four market fields together without holdings/Plan/orders/Discussion/AI rewrite',async()=>{state=seed();await client.sync('9999.HK');for(const key of Object.keys(protectedData))assert.deepEqual(state.stocks[0][key],protectedData[key]);assert.equal(saves,1);assert.equal(state.stocks[0].marketMigration.status,'applied');assert.equal(state.stocks[0].marketRevisionReview.status,'resolved_by_approved_migration');assert.equal(state.stocks[0].technicalData.aiJudgmentStatus,'needs_review')});
  await t.test('repeated poll is idempotent and cannot overwrite later daily content',async()=>{state.stocks[0].priceHistory.at(-1).volume+=1;await client.sync('9999.HK');assert.equal(saves,1);assert.notEqual(state.stocks[0].priceHistory.at(-1).volume,response.bundle.priceHistory.at(-1).volume)});
  await t.test('page/readiness/Discussion agree on migrated technical/content versions',async()=>{const stock={code:'9999.HK',...structuredClone(response.bundle)},date=stock.priceHistory.at(-1).date;const U=require('../src/technical-view-ux.js'),D=require('../src/discussion-data-readiness.js'),W=require('../src/discussion-workbench.js');for(const value of [U.canonicalTechnicalDate({...stock,referenceDate:date}),D.technical(stock,{reviewDate:date}),W.buildContext(stock,{reviewDate:date}).context.currentFacts.technical]){assert.equal(value.dataContentVersion,response.contentHash);assert.equal(value.technicalVersion,stock.technicalData.technicalVersion)}});
  await t.test('rollback projection restores complete previous facts and prior review overlay',async()=>{state=seed();await client.sync('9999.HK');const a=response;response=await h.migration('rollback',{...exact(a),expectedCurrentVersion:a.currentVersion,expectedGeneration:a.generation,phrase:`Rollback ${a.currentVersion} to ${a.previousVersion}`,reason:'isolated fixture'});let written;const r=M.create({rpc:async()=>response,user:async()=>OWNER,getState:()=>state,persist:async next=>{written=next},adopt:next=>{state=next}});await r.sync('9999.HK');assert.deepEqual(M.facts(state.stocks[0]),base);assert.equal(state.stocks[0].marketRevisionReview.status,'review_required');assert.equal(written,state);for(const key of Object.keys(protectedData))assert.deepEqual(state.stocks[0][key],protectedData[key])});
 }finally{await h.db.close()}
});
