'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixtures,exact,approval,database,OWNER,OTHER}=require('./helpers/migration-db.cjs');
const [capsule,second]=fixtures();
test('approved migration real PostgreSQL transaction and permissions',async t=>{
 const h=await database(),db=h.db;let staged,approved,applied;
 const view=()=>h.migration('read',{symbol:'9999.HK'});
 const counts=async()=>(await db.query("select (select count(*) from market_private.migration_versions) versions,(select count(*) from market_private.migration_events) events,(select status from market_private.migration_records limit 1) status,(select generation from market_private.migration_heads limit 1) generation")).rows[0];
 try{
 await t.test('operator stages validated complete package; staging does not approve or switch',async()=>{staged=await h.stage(capsule);const v=await view();assert.equal(v.status,'staged');assert.equal(v.generation,0);assert.equal(v.bundle,null);assert.equal(await h.migration('current',{symbol:'9999.HK'}),null)});
 await t.test('anonymous cannot read/approve/apply; auth anonymous rejected',async()=>{await assert.rejects(h.migration('read',{symbol:'9999.HK'},null,'anon'),/permission denied/);await assert.rejects(h.migration('read',{symbol:'9999.HK'},null),/authentication_required/)});
 await t.test('outsider cannot read, approve, apply or rollback another record',async()=>{assert.equal(await h.migration('read',{symbol:'9999.HK'},OTHER),null);for(const action of ['approve','apply','rollback'])await assert.rejects(h.migration(action,exact(await view()),OTHER),/migration_not_owned/)});
 await t.test('no browser table reads/writes or staging privilege',async()=>{for(const table of ['migration_records','migration_versions','migration_heads','migration_events'])for(const sql of [`select * from market_private.${table}`,`delete from market_private.${table}`])await assert.rejects(db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.exec(sql)}),/permission denied/);await assert.rejects(db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.query('select market_private.migration_stage($1,$2)',[OWNER,second])}),/permission denied/)});
 await t.test('cannot apply without explicit recorded approval',async()=>{await assert.rejects(h.migration('apply',exact(await view())),/approval_not_available/)});
 await t.test('forged client context/arbitrary command is rejected',async()=>{await assert.rejects(h.migration('apply',{...exact(await view()),approved:true,applyIntent:'provider_rebase_apply'}),/invalid_action/);for(const symbol of ['https://example.com','C:\\shell','9999.HK; drop table x','$(whoami)'])await assert.rejects(h.migration('read',{symbol}),/invalid_input/)});
 await t.test('each hash mismatch and wrong source confirmation is rejected',async()=>{for(const key of ['candidateHash','contentHash','approvalPackageHash'])await assert.rejects(h.migration('approve',{...exact(await view()),[key]:'0'.repeat(64)}),/approval_binding_mismatch/);await assert.rejects(h.migration('approve',{...approval({...await view(),capsule}),provider:'eastmoney'}),/explicit_approval_required/)});
 await t.test('tampered capsule cannot stage under another owner',async()=>{for(const key of ['package','content','base','technical']){const p=structuredClone(capsule);p[key]=p[key].replace(/\{/,'{"forged":true,');await assert.rejects(h.stage(p,OTHER),/hash_binding_mismatch|technical_hash_mismatch/)}});
 await t.test('second active migration cannot be staged for same symbol',async()=>{const p=structuredClone(capsule);const c=JSON.parse(p.candidate);c.generatedAt='2026-01-01T00:00:00Z';const hash=x=>require('crypto').createHash('sha256').update(x).digest('hex');const pkg=JSON.parse(p.package);pkg.generatedAt=c.generatedAt;p.package=JSON.stringify(pkg);c.approvalPackageHash=hash(p.package);p.candidate=JSON.stringify(c);await assert.rejects(h.stage(p),/migration_one_pending/)});
 await t.test('outdated guard and release are rejected by the server',async()=>{for(const key of ['guard','release']){const p=structuredClone(capsule),c=JSON.parse(p.candidate);if(key==='guard')c.guardImplementationHash='0'.repeat(64);else c.evidence.productionDeployment.assetVersion='obsolete-release';p.candidate=JSON.stringify(c);await assert.rejects(h.stage(p,OTHER),/migration_release_binding_mismatch/)}});
 await t.test('owner approves exact server-staged hashes',async()=>{approved=await h.migration('approve',approval({...await view(),capsule}));assert.equal(approved.status,'approved');assert.ok(approved.approvalId);assert.equal(approved.readyToApply,true)});
 await t.test('generation/version and running task conflicts stop apply',async()=>{await assert.rejects(h.migration('apply',{...exact(approved),expectedGeneration:8}),/version_conflict/);const task=await h.account('request',{symbol:'9999.HK',taskType:'UPDATE_DAILY_MARKET_DATA'});await assert.rejects(h.migration('apply',exact(approved)),/active_task_conflict/);await db.query("update market_private.tasks set status='failed' where id=$1",[task.taskId])});
 await t.test('failure after pointer write rolls back pointer, version, approval consumption and event',async()=>{const before=await counts();await db.exec("create function market_private.fixture_fail() returns trigger language plpgsql as $$ begin if new.action='applied' then raise exception 'fixture_failure_after_pointer'; end if;return new;end $$; create trigger fixture_fail before insert on market_private.migration_events for each row execute function market_private.fixture_fail();");await assert.rejects(h.migration('apply',exact(approved)),/fixture_failure_after_pointer/);assert.deepEqual(await counts(),before);await db.exec('drop trigger fixture_fail on market_private.migration_events; drop function market_private.fixture_fail()')});
 await t.test('atomic apply switches bars/technical together and preserves complete previous',async()=>{applied=await h.migration('apply',exact(approved));assert.equal(applied.status,'applied');assert.equal(applied.generation,1);assert.deepEqual(applied.previousBundle,JSON.parse(capsule.base));assert.deepEqual(applied.bundle.priceHistory,JSON.parse(capsule.candidate).stock.priceHistory);assert.equal(applied.bundle.technicalData.aiJudgmentStatus,'needs_review');assert.equal(applied.bundle.technicalData.technicalVersion,applied.bundle.marketDataFreshness.technicalVersion);assert.equal(applied.bundle.marketDataFreshness.dataContentVersion,applied.contentHash)});
 await t.test('duplicate apply consumes approval once and never reexecutes',async()=>{const before=await counts();const again=await h.migration('apply',exact(approved));assert.equal(again.idempotent,true);assert.deepEqual(await counts(),before)});
 await t.test('Worker is read-only, owner-bound, and revocation immediately blocks',async()=>{const token='a'.repeat(64);await h.account('register_worker',{token});const read=()=>db.transaction(async tx=>{await tx.exec('set local role anon');return (await tx.query('select public.market_data_migration_current($1,$2) as value',[token,'9999.HK'])).rows[0].value});assert.equal((await read()).owner,OWNER);await h.account('revoke_worker',{});await assert.rejects(read(),/worker_unauthorized/)});
 await t.test('immutable versions and audit refuse mutation even via SQL',async()=>{for(const table of ['migration_versions','migration_events'])await assert.rejects(db.exec(`delete from market_private.${table}`),/immutable_migration/);await assert.rejects(db.exec("update market_private.migration_records set content_hash='bad'"),/immutable_migration/)});
 await t.test('rollback restores complete old facts and retains failed/new audit/version',async()=>{const result=await h.migration('rollback',{...exact(applied),expectedCurrentVersion:applied.currentVersion,expectedGeneration:applied.generation,phrase:`Rollback ${applied.currentVersion} to ${applied.previousVersion}`,reason:'synthetic acceptance'});assert.equal(result.status,'rolled_back');assert.equal(result.generation,2);assert.deepEqual(result.bundle,JSON.parse(capsule.base));assert.deepEqual(result.previousBundle,applied.bundle);assert.equal(Number((await counts()).versions),2)});
 await t.test('consumed approval cannot reapply or approve after rollback',async()=>{const v=await view(),i={...exact(v),expectedCurrentVersion:v.currentVersion,expectedGeneration:v.generation};await assert.rejects(h.migration('apply',i),/approval_not_available/);await assert.rejects(h.migration('approve',{...approval({...v,capsule}),...i}),/approval_not_available/)});
 await t.test('independent symbol stages; operator supersession retains approval audit',async()=>{await h.stage(second);let v=await h.migration('read',{symbol:'9998.HK'});v=await h.migration('approve',approval({...v,capsule:second}));await db.query("select market_private.migration_supersede($1,$2,'SUPERSEDED_BY_RELEASE_BINDING')",[OWNER,v.migrationId]);const now=await h.migration('read',{symbol:'9998.HK'});assert.equal(now.status,'superseded');assert.equal(now.approvalId,v.approvalId);await assert.rejects(h.migration('apply',exact(v)),/approval_not_available/)});
 }finally{await db.close()}
});
