'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/plan-context-contract'),P=require('../src/plan-v2'),R=require('../src/plan-review'),RT=require('../src/plan-runtime'),F=require('./fixtures/homepage-attention');
const clone=C.clone;
test('V4 assessments bind the full action intent and exact revision; entry applicability stays strict',()=>{
  const V=require('../src/plan-v4'),plan=P.createPlan({action:'observe',triggerPrice:50,triggerDirection:'above',conditions:{invalidation:['结构变化']}}),state=F.state({plans:[plan]}),definition=V.legacyDefinition(plan,'hold_watch');
  V.writeRevision(state,'home-stock',plan.id,definition);C.captureAssessment(state,'review:v4',state.stocks[0].plans[0],state.stocks[0]);const ref=clone(C.assessmentStore(state).byId['review:v4'].definitionRef);
  assert.equal(ref.hashContractVersion,V.HASH_CONTRACT);assert.equal(C.validateAssessmentStore(state.planAssessmentBindings),true);
  definition.actionIntent='risk_review';V.writeRevision(state,'home-stock',plan.id,definition);assert.equal(C.binding(state,ref).bindingStatus,'changed');
  const entry=P.createPlan({action:'buy',triggerPrice:40,triggerDirection:'below',conditions:{invalidation:['前提变化']},allocationConstraint:{maxPositionPct:10,targetWeightRange:null}}),empty=F.state({shares:0});V.writeRevision(empty,'home-stock',null,V.legacyDefinition(entry,'entry'));const created=empty.stocks[0].plans[0];C.captureAssessment(empty,'entry',created,empty.stocks[0]);empty.stocks[0].shares=20;assert.equal(C.assessmentStatus(empty,'entry',{}).applicability.status,'blocked');
});
test('binding, evidence and applicability are independent derived axes',()=>{
  const plan=P.createPlan({action:'reduce',triggerPrice:50,triggerDirection:'above',quantity:20}),state=F.state({plans:[plan]}),stock=state.stocks[0];
  C.captureAssessment(state,'review:r',plan,stock);const before=clone(state.planAssessmentBindings);stock.shares=60;
  let result=R.assessmentStatus(state,{reviewId:'r',planId:plan.id});assert.equal(result.bindingStatus,'current');assert.equal(result.evidenceFreshness.status,'current');assert.equal(result.applicability.status,'applicable');
  stock.priceHistory.push({...stock.priceHistory[0],date:'2026-09-07'});result=R.assessmentStatus(state,{reviewId:'r',planId:plan.id});assert.equal(result.bindingStatus,'current');assert.equal(result.evidenceFreshness.status,'stale');
  stock.shares=10;assert.equal(R.assessmentStatus(state,{reviewId:'r',planId:plan.id}).applicability.status,'blocked');stock.shares=0;assert.ok(R.assessmentStatus(state,{reviewId:'r',planId:plan.id}).applicability.reasons.includes('holding_required'));
  plan.triggerPrice=52;assert.equal(R.assessmentStatus(state,{reviewId:'r',planId:plan.id}).bindingStatus,'changed');assert.deepEqual(state.planAssessmentBindings,before);assert.equal(plan.status,'active');
});
test('old reviews keep their judgments and cannot manufacture missing evidence',()=>{const plan=P.createPlan({action:'sell',triggerPrice:50,triggerDirection:'above'}),state=F.state({plans:[plan]}),review={reviewId:'old',planId:plan.id,planVersion:1,planSnapshotHash:R.planSnapshotHash(plan),reviewOutcome:'still_valid',reviewDate:'2020-01-01'},before=JSON.stringify(review);const result=R.assessmentStatus(state,review);assert.equal(result.bindingStatus,'legacy_unknown');assert.equal(result.evidenceFreshness.status,'unknown');assert.equal(JSON.stringify(review),before)});
test('PlanReview prepare and save use exact V4 revision, including intent-only changes',()=>{
 const V=require('../src/plan-v4'),Portfolio=require('../src/portfolio-review-context'),p=P.createPlan({action:'observe',triggerPrice:50,triggerDirection:'above',conditions:{invalidation:['前提变化']}}),state=F.state({plans:[p]}),definition=V.legacyDefinition(p,'hold_watch');V.writeRevision(state,'home-stock',p.id,definition);
 const ctx=R.buildContext(state.stocks,{state,allStocks:state.stocks,portfolioContext:Portfolio}),response={planReviews:ctx.expectedPlans.map(x=>({symbol:x.symbol,planId:x.planId,planVersion:x.planVersion,review:{outcome:'still_valid',summary:'维持观察',changedPremises:[],riskFlags:[],suggestedChanges:[],confidence:'medium'}}))},preview=R.process(JSON.stringify(response),{expectedPlans:ctx.expectedPlans,reviewDate:ctx.reviewDate});assert.equal(preview.ok,true);const built=R.buildReviewCandidate(state,preview);assert.equal(R.assessmentStatus(built.candidate,built.reviews[0]).bindingStatus,'current');definition.actionIntent='risk_review';V.writeRevision(state,'home-stock',p.id,definition);assert.throws(()=>R.buildReviewCandidate(state,preview),/变化/);
});
test('Runtime rejects stale facts at prepare and again after Preview with zero writes',async()=>{for(const mutate of [s=>s.shares=0,s=>s.priceHistory.push({...s.priceHistory[0],date:'2026-09-07'}),s=>s.technicalData.technicalDataStatus='stale']){const plan=P.createWatchPlan({...F.definition,reviewAction:'reduce_review'}),state=F.state({plans:[plan]}),prepared=RT.prepare(state,'home-stock',plan.id),raw=JSON.stringify({planRuntimeReview:{suggestedPhase:'forming',transitionAssessment:'advance',summary:'复核结果',evidence:[],risks:[],watchPoints:[],confidence:'medium'}}),preview=RT.process(raw,{state,prepared});assert.equal(preview.ok,true);mutate(state.stocks[0]);assert.throws(()=>RT.prepare(state,'home-stock',plan.id),/不再适用/);let writes=0;const result=await RT.commit(preview,state,{saveCandidate:async()=>writes++},{confirmed:true});assert.equal(result.status,'stale');assert.equal(writes,0)}});
test('Runtime accepts harmless shares change but never same-version rule change',async()=>{const state=await F.runtime(),plan=state.stocks[0].plans[0],raw=clone(state.planRuntimeStates);state.stocks[0].shares=60;assert.doesNotThrow(()=>RT.prepare(state,'home-stock',plan.id));assert.equal(RT.assessmentStatus(state,plan.id).bindingStatus,'current');plan.entryConditions=['另一规则'];assert.equal(RT.bindingStatus(state,plan.id),'definition_changed');assert.deepEqual(state.planRuntimeStates,raw);assert.equal(RT.validateStore(raw).ok,true)});
test('assessment store rejects corrupted bindings and remains optional for old backups',()=>{const state=F.state(),plan=P.createWatchPlan(F.definition);C.captureAssessment(state,'x',plan,state.stocks[0]);assert.equal(C.validateAssessmentStore(state.planAssessmentBindings),true);state.planAssessmentBindings.byId.x.definitionRef.definitionHash='wrong';assert.throws(()=>C.validateAssessmentStore(state.planAssessmentBindings));assert.deepEqual(C.assessmentStore({}),{schemaVersion:C.ASSESSMENT_STORE,byId:{}})});
