'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const Recovery=require('../src/auth-password-recovery.js');
const PROD='fntslvdxnupmdljnadec',TEST='lblyapnsngqnjimgskkp',USER='recovery-fixture-user';
const flush=()=>new Promise(resolve=>setTimeout(resolve,15));
function fixture(t,{url=Recovery.PRODUCTION_URL,project=PROD,storage=new Map()}={}){
  let session={user:{id:USER},expires_at:Math.floor(Date.now()/1000)+3600},userError=null,sendError=null,updateError=null,initializeError=null;
  const calls={send:[],update:[],verify:0,logout:0},history=[];
  const root={location:{href:url},history:{state:null,replaceState(_s,_title,next){root.location.href=new URL(next,root.location.href).href;history.push(root.location.href)}},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},setTimeout:(fn,ms)=>{const timer=setTimeout(fn,ms);if(ms>1000)timer.unref();return timer},clearTimeout};
  const sdk={auth:{initialize:async()=>({error:initializeError}),getSession:async()=>({data:{session}}),getUser:async()=>{calls.verify++;return {data:{user:session?.user},error:userError}},resetPasswordForEmail:async(email,options)=>{calls.send.push({email,options});return {error:sendError}},updateUser:async attributes=>{calls.update.push(attributes);return {data:{user:session?.user},error:updateError}}}};
  const recovery=Recovery.create({root,getClient:()=>sdk,configuration:()=>({projectRef:project}),signOut:async()=>{calls.logout++;session=null;recovery.accept('SIGNED_OUT',null)}});
  t.after(()=>recovery.reset());
  return {root,storage,calls,history,recovery,sdk,setSession:v=>{session=v},setUserError:v=>{userError=v},setSendError:v=>{sendError=v},setUpdateError:v=>{updateError=v},setInitializeError:v=>{initializeError=v},async activate(){recovery.accept('PASSWORD_RECOVERY',session);await flush();assert.equal(recovery.getState().status,'ready')}};
}
test('CASE 2/5 empty and malformed email do not call Auth',async t=>{const f=fixture(t);for(const email of ['', 'bad','a@b','a b@example.invalid'])await assert.rejects(f.recovery.request(email),e=>e.code==='email');assert.equal(f.calls.send.length,0)});
test('CASE 3 official resetPasswordForEmail receives verified production redirect',async t=>{const f=fixture(t);await f.recovery.request(' fixture@example.invalid ');assert.deepEqual(f.calls.send,[{email:'fixture@example.invalid',options:{redirectTo:Recovery.PRODUCTION_URL+'?auth=recovery'}}])});
test('production redirect never follows caller origin or a redirect query',async t=>{const f=fixture(t,{url:'https://untrusted.invalid/?redirectTo=https://evil.invalid/'});assert.equal(f.recovery.redirectTo(),Recovery.PRODUCTION_URL+'?auth=recovery')});
test('test project redirect is limited to local test app',t=>{const f=fixture(t,{project:TEST,url:'http://127.0.0.1:8899/index.html?x=1'});assert.equal(f.recovery.redirectTo(),'http://127.0.0.1:8899/?auth=recovery');const foreign=fixture(t,{project:TEST,url:'https://foreign.invalid/'});assert.throws(()=>foreign.recovery.redirectTo(),e=>e.code==='redirect')});
test('CASE 4 account enumeration success text is identical for unknown email',async t=>{const f=fixture(t);const a=await f.recovery.request('known@example.invalid');f.setSendError({code:'user_not_found',message:'PRIVATE'});assert.equal(await f.recovery.request('unknown@example.invalid'),a)});
for(const [name,error,code] of [['CASE 6 rate limit',{status:429},'rate'],['CASE 7 network',{name:'TypeError',message:'PRIVATE'},'network'],['server failure',{status:503,message:'PRIVATE'},'service']])test(name,async t=>{const f=fixture(t);f.setSendError(error);await assert.rejects(f.recovery.request('fixture@example.invalid'),e=>e.code===code&&!e.message.includes('PRIVATE'));assert.equal(f.calls.send.length,1)});
test('sending twice concurrently does not duplicate recovery emails',async t=>{const f=fixture(t);let release;f.sdk.auth.resetPasswordForEmail=()=>new Promise(r=>{release=r});const first=f.recovery.request('fixture@example.invalid');await assert.rejects(f.recovery.request('fixture@example.invalid'),e=>e.code==='busy');release({});await first});
test('CASE 8 recovery event validates on server outside SDK callback',async t=>{const f=fixture(t);let callbackActive=true;f.sdk.auth.getUser=async()=>{assert.equal(callbackActive,false);return {data:{user:{id:USER}}}};f.recovery.accept('PASSWORD_RECOVERY',{user:{id:USER}});assert.equal(f.recovery.getState().status,'checking');callbackActive=false;await flush();assert.equal(f.recovery.getState().status,'ready')});
test('CASE 9 mismatch and CASE 10 short password never submit',async t=>{const f=fixture(t);await f.activate();await assert.rejects(f.recovery.update('long-fixture','different'),e=>e.code==='mismatch');await assert.rejects(f.recovery.update('short','short'),e=>e.code==='password');assert.equal(f.calls.update.length,0)});
test('CASE 11/12 official password update succeeds and clears recovery intent',async t=>{const f=fixture(t,{url:Recovery.PRODUCTION_URL+'?auth=recovery'});await f.activate();await f.recovery.update('new-fixture-password','new-fixture-password');assert.deepEqual(f.calls.update,[{password:'new-fixture-password'}]);assert.equal(f.recovery.getState().status,'success');assert.equal(f.storage.size,0);assert.equal(new URL(f.root.location.href).search,'');assert.equal(f.calls.logout,0)});
for(const [code,expected] of [['weak_password','weak'],['same_password','same']])test('server password rejection: '+code,async t=>{const f=fixture(t);await f.activate();f.setUpdateError({code,message:'PRIVATE'});await assert.rejects(f.recovery.update('new-fixture-password','new-fixture-password'),e=>e.code===expected&&!e.message.includes('PRIVATE'));assert.equal(f.recovery.getState().status,'ready')});
test('CASE 13 expired link fails even with an existing normal session',async t=>{const f=fixture(t,{url:Recovery.PRODUCTION_URL+'?auth=recovery#error=access_denied&error_code=otp_expired'});f.setInitializeError({code:'otp_expired'});await f.recovery.start();assert.equal(f.recovery.getState().status,'expired');assert.equal(new URL(f.root.location.href).hash,'');await assert.rejects(f.recovery.update('new-fixture-password','new-fixture-password'),e=>e.code==='expired');assert.equal(f.calls.update.length,0)});
test('CASE 14 query marker alone cannot authorize a password change',async t=>{const f=fixture(t,{url:Recovery.PRODUCTION_URL+'?auth=recovery'});await f.recovery.start();assert.equal(f.recovery.getState().status,'expired');assert.equal(f.calls.update.length,0)});
test('CASE 15 reused link rejection cannot fall back to a saved intent',async t=>{const storage=new Map([['auth-recovery-intent-'+PROD,JSON.stringify({userId:USER,until:Date.now()+60000})]]),f=fixture(t,{storage,url:Recovery.PRODUCTION_URL+'?auth=recovery#error=access_denied'});await f.recovery.start();assert.equal(f.recovery.getState().status,'expired');assert.equal(storage.size,0)});
for(const event of ['SIGNED_IN','TOKEN_REFRESHED','INITIAL_SESSION'])test('CASE 16/17 ordinary '+event+' never opens recovery',async t=>{const f=fixture(t);f.recovery.accept(event,{user:{id:USER}});await f.recovery.start();assert.equal(f.recovery.getState().status,'idle')});
test('CASE 18 reload restores only bounded intent plus server-validated same user',async t=>{const storage=new Map(),first=fixture(t,{storage});await first.activate();const second=fixture(t,{storage});await second.recovery.start();assert.equal(second.recovery.getState().status,'ready');assert.equal(second.calls.verify,1)});
test('a different user cannot restore a previous user recovery intent',async t=>{const storage=new Map([['auth-recovery-intent-'+PROD,JSON.stringify({userId:'other',until:Date.now()+60000})]]),f=fixture(t,{storage});await f.recovery.start();assert.equal(f.recovery.getState().status,'expired');assert.equal(f.calls.update.length,0)});
test('failed server session validation denies update',async t=>{const f=fixture(t);await f.activate();f.setUserError({status:401,message:'PRIVATE'});await assert.rejects(f.recovery.update('new-fixture-password','new-fixture-password'),e=>e.code==='expired');assert.equal(f.calls.update.length,0)});
test('normal authenticated session without a recovery event denies update',async t=>{const f=fixture(t);await assert.rejects(f.recovery.update('new-fixture-password','new-fixture-password'),e=>e.code==='expired');assert.equal(f.calls.update.length,0)});
test('account change while verifying invalidates the pending update',async t=>{const f=fixture(t);await f.activate();let done;f.sdk.auth.getUser=()=>new Promise(resolve=>{done=resolve});const update=f.recovery.update('new-fixture-password','new-fixture-password');f.recovery.accept('SIGNED_OUT',null);done({data:{user:{id:USER}}});await assert.rejects(update,e=>e.code==='expired');assert.equal(f.calls.update.length,0)});
test('cancel active recovery uses existing local signOut',async t=>{const f=fixture(t);await f.activate();await f.recovery.cancel();assert.equal(f.calls.logout,1);assert.equal(f.storage.size,0);assert.equal(f.recovery.getState().status,'idle')});

test('recovery expiring during server validation cannot submit a password change',async t=>{const f=fixture(t);await f.activate();const after=JSON.parse([...f.storage.values()][0]).until+1;f.sdk.auth.getUser=async()=>{t.mock.method(Date,'now',()=>after);return {data:{user:{id:USER}}}};await assert.rejects(f.recovery.update('new-fixture-password','new-fixture-password'),e=>e.code==='expired');assert.equal(f.calls.update.length,0)});

test('server-confirmed update remains success when the local intent deadline passes in flight',async t=>{const f=fixture(t);await f.activate();const after=JSON.parse([...f.storage.values()][0]).until+1;f.sdk.auth.updateUser=async()=>{t.mock.method(Date,'now',()=>after);return {data:{user:{id:USER}}}};await f.recovery.update('new-fixture-password','new-fixture-password');assert.equal(f.recovery.getState().status,'success');assert.equal(f.storage.size,0)});
test('CASE 22 marker stores no password or credential, and no custom localStorage is used',async t=>{const f=fixture(t);await f.activate();const marker=JSON.parse([...f.storage.values()][0]);assert.deepEqual(Object.keys(marker).sort(),['until','userId']);const source=fs.readFileSync('src/auth-password-recovery.js','utf8')+fs.readFileSync('src/auth-password-recovery-ui.js','utf8');assert.doesNotMatch(source,/console\.|localStorage|indexedDB/)});
test('storage denial permits current recovery page without plaintext fallback',async t=>{const f=fixture(t);f.root.sessionStorage.setItem=()=>{throw Error('denied')};await f.activate();assert.equal(f.storage.size,0)});
test('semantic PASSWORD_RECOVERY is not lost by shared session deduplication',async()=>{
  let callback;const value={user:{id:USER},access_token:'synthetic-fixture'};const events=[],seen=[];
  const sdk={auth:{onAuthStateChange:fn=>{callback=fn},getSession:async()=>({data:{session:value}})}};
  const ctx={setTimeout,clearTimeout,URL,location:{href:Recovery.PRODUCTION_URL},UNIVERSE_CLOUD_CONFIG:{projectRef:PROD,url:`https://${PROD}.supabase.co`,publishableKey:'sb_publishable_fixture'},UniverseSupabaseSdk:{createClient:()=>sdk},AuthPasswordRecovery:{create:()=>({accept:e=>seen.push(e)})}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('src/supabase-browser-client.js','utf8'),ctx);
  ctx.SupabaseBrowserClient.onAuthStateChange(event=>events.push(event));await flush();callback('PASSWORD_RECOVERY',value);await flush();assert.equal(events.filter(e=>e==='PASSWORD_RECOVERY').length,1);assert(seen.includes('PASSWORD_RECOVERY'));
});
