'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const PlanV2=require('../src/plan-v2.js');
const PlanReview=require('../src/plan-review.js');
const PortfolioContext=require('../src/portfolio-review-context.js');
const DecisionContext=require('../src/decision-compression-context.js');
const Contract=require('../src/decision-compression-contract.js');

const reviewDate='2026-08-28',now='2026-08-28T08:00:00+08:00';
function plan(input){return PlanV2.createPlan({...input,fullConditionStatus:input.fullConditionStatus||'unproven'},{source:'manual',now})}
function technical(symbol,price){return {technicalDataStatus:'fresh',symbol,technicalAsOf:reviewDate,latestCompleteBar:reviewDate,supportResistanceAsOf:reviewDate,price,supportLevels:[price*.9],resistanceLevels:[price*1.1],riskFlags:[]}}
function stock(code,name,currentPrice,currentValue,plans=[],extra={}){return {id:code,code,name,type:'holding',shares:currentValue/currentPrice,currentPrice,currentValue,capPct:extra.capPct||35,plans,priceHistory:[{date:reviewDate,close:currentPrice,low:currentPrice*.95,high:currentPrice*1.05,is_complete_bar:true}],technicalData:technical(code,currentPrice),allocationDecision:{recommendedMaxWeight:extra.upperLimit||extra.capPct||35,updatedAt:reviewDate},...extra}}
function makeFixture(){
  const a=plan({id:'plan-a',action:'add',triggerPrice:10,triggerDirection:'above',allocationConstraint:{maxPositionPct:20,targetWeightRange:null},note:'价格条件出现后复核其他前提'}),c=plan({id:'plan-c',action:'observe',triggerPrice:50,triggerDirection:'above',note:'等待结构确认'}),d=plan({id:'plan-d',action:'observe',triggerPrice:45,triggerDirection:'above',note:'复核核心前提'}),legacy=PlanV2.normalizePlan({id:'legacy-b',action:'buy',price:18,note:'旧计划'});
  const stocks=[stock('600001.SS','甲公司',12,40000,[a],{capPct:25,upperLimit:25}),stock('600002.SS','乙公司',19,12000,[legacy]),stock('600003.SS','丙公司',30,18000,[c]),stock('600004.SS','丁公司',40,20000,[d]),stock('600005.SS','戊公司',8,10000,[])];
  const reviews=[{symbol:'600003.SS',plan:c,outcome:'still_valid',id:'review-c',summary:'计划近期已复核。'},{symbol:'600004.SS',plan:d,outcome:'likely_invalid',id:'review-d',summary:'计划可能已不适用。'}].map(item=>PlanReview.normalizePlanReview({reviewId:item.id,symbol:item.symbol,planId:item.plan.id,planVersion:item.plan.planVersion,planSnapshotHash:PlanReview.planSnapshotHash(item.plan),reviewDate,reviewedAt:now,reviewOutcome:item.outcome,summary:item.summary,confidence:'medium'}));
  const planReviews=PlanReview.normalizeStore({schemaVersion:PlanReview.STORE_SCHEMA_VERSION,currentByPlan:Object.fromEntries(reviews.map(item=>[PlanReview.reviewKey(item.symbol,item.planId),item])),history:[],snapshots:[]}),base=PortfolioContext.buildPortfolioContext(stocks,{allStocks:stocks,reviewDate,generatedAt:now,planReviewStore:planReviews});
  const review={reviewDate,summary:'今天优先复核仓位与计划冲突，其余保持观察。',marketContext:'未提供权威市场环境。',portfolioRiskLevel:'moderate',priorityStocks:[{symbol:'600001.SS',priority:'high',reason:'仓位与计划前提冲突。',focus:'确认计划是否仍有效。',planRelation:'价格已触发，完整条件待确认。'},{symbol:'600004.SS',priority:'high',reason:'计划复核判断提示可能失效。',focus:'由用户确认有效性。',planRelation:'正式计划尚未失效。'},{symbol:'600003.SS',priority:'low',reason:'近期已复核且未触发。',focus:'保持观察。',planRelation:'当前计划仍有效。'}],riskAttention:[{symbol:'600001.SS',reason:'仓位高于上限。'}],planWatch:[{symbol:'600001.SS',status:'triggered',reason:'计划价格已触发，仍需确认其他条件。'}],candidateReview:[],portfolioRisks:['所选标的存在集中度风险。'],todayFocus:['先复核甲公司与丁公司。'],dataLimitations:['缺少权威市场环境判断。'],confidence:'medium'};
  const portfolioReview={current:{reviewDate,generatedAt:now,savedAt:now,selectedSymbols:stocks.map(item=>item.code),planReferences:base.planReferences,review},history:[]},state={stocks,planReviews,portfolioReview,decisionCompression:{schemaVersion:Contract.STORE_SCHEMA_VERSION,current:null,history:[]},updatedAt:1},context=DecisionContext.buildDecisionContext(portfolioReview.current,stocks,{allStocks:stocks,reviewDate,generatedAt:now,planReviewStore:planReviews});
  return {state,context,plans:{a,c,d,legacy}};
}
function validDecision(context,overrides={}){return {decisionCompression:{reviewDate,overallSummary:'今天先复核仓位与计划有效性，其他标的保持观察。',items:[{symbol:'600001.SS',priority:'high',actionCategory:'review_now',reason:'仓位高于已知上限且计划价格已触发，先确认计划是否仍有效。',blockerPriority:['allocation_conflict','full_conditions_unproven'],planState:'current_valid',confidence:'medium'},{symbol:'600004.SS',priority:'high',actionCategory:'review_now',reason:'计划可能已不适用，但尚未由用户确认失效。',blockerPriority:['plan_needs_review'],planState:'likely_invalid_unconfirmed',confidence:'medium'},{symbol:'600003.SS',priority:'medium',actionCategory:'watch',reason:'计划近期已复核且价格条件尚未触发，今天保持观察。',blockerPriority:[],planState:'recently_reviewed',confidence:'medium'}],noActionSymbols:['600002.SS','600005.SS'],confidence:'medium',limitations:['当前没有权威市场环境判断，相关结论保持谨慎。'],...overrides}}
}

test('current Plan, trigger, allocation conflict, review freshness, and no-action facts are compact and authoritative',()=>{const {context}=makeFixture(),bySymbol=Object.fromEntries(context.stocks.map(item=>[item.symbol,item]));assert.equal(bySymbol['600001.SS'].plans[0].validity,'current');assert.equal(bySymbol['600001.SS'].plans[0].priceTrigger,'triggered');assert.equal(bySymbol['600001.SS'].plans[0].fullConditions,'unproven');assert.equal(bySymbol['600001.SS'].allocationConflict.conflict,true);assert.ok(bySymbol['600003.SS'].allowedPlanStates.includes('recently_reviewed'));assert.ok(bySymbol['600004.SS'].allowedPlanStates.includes('likely_invalid_unconfirmed'));assert.deepEqual(bySymbol['600005.SS'].allowedPlanStates,['no_current_plan']);assert.equal(context.marketContext.status,'unavailable')});

test('legacy historical-only Plan cannot silently drive high priority',()=>{const {context}=makeFixture(),legacy=context.stocks.find(item=>item.symbol==='600002.SS');assert.ok(legacy.allowedPlanStates.includes('historical_only'));assert.equal(legacy.highAttentionEligible,false);const value=validDecision(context);value.decisionCompression.items.unshift({symbol:'600002.SS',priority:'high',actionCategory:'review_now',reason:'旧计划价格附近需要复核。',blockers:['plan_needs_review'],planState:'historical_only',confidence:'medium'});value.decisionCompression.noActionSymbols=['600005.SS'];assert.equal(Contract.validate(value,{context}).code,'unsupported_high_priority')});

test('needs-review and likely-invalid Plans produce review workflow without mutating formal Plans',()=>{const {state,context}=makeFixture(),before=JSON.stringify(state.stocks.map(stock=>stock.plans)),result=Contract.validate(validDecision(context),{context});assert.equal(result.ok,true);assert.equal(result.decision.items[1].actionCategory,'review_now');assert.equal(JSON.stringify(state.stocks.map(stock=>stock.plans)),before)});

test('Plan version change makes the old PlanReview stale and it is not treated as current',()=>{const {state}=makeFixture(),stockC=state.stocks.find(stock=>stock.code==='600003.SS');stockC.plans[0]=PlanV2.applyAuthoritativeEdit(stockC.plans[0],{note:'计划已由用户修改'},{now:'2026-08-28T09:00:00+08:00'});const context=DecisionContext.buildDecisionContext(state.portfolioReview.current,state.stocks,{allStocks:state.stocks,reviewDate,generatedAt:now,planReviewStore:state.planReviews}),facts=context.stocks.find(item=>item.symbol==='600003.SS');assert.ok(facts.allowedPlanStates.includes('changed_since_review'));assert.equal(facts.plans[0].currentReview,null);assert.match(facts.plans[0].staleReview.meaning,/计划已更新|计划事实已变化/)});

test('price-triggered unproven conditions remain program-owned when AI does not emphasize them',()=>{const {context}=makeFixture(),value=validDecision(context);value.decisionCompression.items[0].blockerPriority=['allocation_conflict'];const result=Contract.validate(value,{context});assert.equal(result.ok,true);assert.ok(result.decision.items[0].blockerFacts.includes('full_conditions_unproven'));assert.deepEqual(Contract.displayBlockers(result.decision.items[0]),['full_conditions_unproven','allocation_conflict'])});

test('stale technical facts lower confidence',()=>{const {state}=makeFixture();state.stocks[0].technicalData.technicalDataStatus='stale';const context=DecisionContext.buildDecisionContext(state.portfolioReview.current,state.stocks,{allStocks:state.stocks,reviewDate,generatedAt:now,planReviewStore:state.planReviews}),value=validDecision(context);value.decisionCompression.items[0].confidence='high';assert.equal(Contract.validate(value,{context}).code,'unsupported_confidence')});

test('missing news surfaces only when decision-relevant',()=>{const {context}=makeFixture(),high=context.stocks.find(item=>item.symbol==='600001.SS'),low=context.stocks.find(item=>item.symbol==='600003.SS');assert.equal(high.eligibleBlockers.missing_news,true);assert.equal(low.eligibleBlockers.missing_news,false);const value=validDecision(context);value.decisionCompression.items[2].blockerPriority=['missing_news'];assert.equal(Contract.validate(value,{context}).code,'unsupported_blocker')});

test('contract bounds detailed items and collapses low-value stocks into exact no-action coverage',()=>{const {context}=makeFixture(),result=Contract.validate(validDecision(context),{context});assert.equal(result.ok,true);assert.equal(result.decision.items.length,3);assert.deepEqual(result.decision.noActionSymbols,['600002.SS','600005.SS']);const tooMany=validDecision(context);tooMany.decisionCompression.items=Array.from({length:6},(_,index)=>({...tooMany.decisionCompression.items[2],symbol:`60000${index+1}.SS`}));assert.equal(Contract.validate(tooMany,{context}).code,'invalid_items')});

test('unknown and duplicate symbols are rejected',()=>{const {context}=makeFixture(),unknown=validDecision(context),duplicate=validDecision(context);unknown.decisionCompression.noActionSymbols[0]='AAPL';duplicate.decisionCompression.noActionSymbols[0]='600001.SS';assert.equal(Contract.validate(unknown,{context}).code,'unknown_symbol');assert.equal(Contract.validate(duplicate,{context}).code,'duplicate_symbol')});

test('high-attention symbols cannot be silently placed in noActionSymbols',()=>{const {context}=makeFixture(),value=validDecision(context);value.decisionCompression.items=value.decisionCompression.items.filter(item=>item.symbol!=='600001.SS');value.decisionCompression.noActionSymbols.unshift('600001.SS');assert.equal(Contract.validate(value,{context}).code,'material_symbol_in_no_action')});

test('malformed and truncated JSON are zero-write failures',()=>{const {context}=makeFixture();for(const raw of ['not json','{"decisionCompression":']){const result=Contract.process(raw,{context});assert.equal(result.ok,false);assert.equal(result.writes,0);assert.equal(result.previewReady,false)}});

test('Decision Compression consumes shared fenced smart-quote recovery without changing its contract',()=>{const {context}=makeFixture(),value=validDecision(context,{overallSummary:'今天先复核“计划有效性”，其他标的保持观察。'}),raw=JSON.stringify(value).replace(/"([^"\\]*(?:\\.[^"\\]*)*)"/g,'“$1”'),result=Contract.process(`\n\`\`\`json\n${raw}\n\`\`\`\n`,{context});assert.equal(result.ok,true,result.message);assert.equal(result.input.smartQuotesRecovered,true);assert.equal(result.input.fenceRemoved,true);assert.equal(result.decision.overallSummary,value.decisionCompression.overallSummary)});

test('dangerous trade commands and unsupported market claims are rejected',()=>{const {context}=makeFixture();for(const phrase of ['立即买入甲公司。','大盘已突破，先复核甲公司。']){const value=validDecision(context);value.decisionCompression.overallSummary=phrase;assert.equal(Contract.validate(value,{context}).code,'unsafe_text')}});

test('one successful save creates one auditable snapshot and leaves Plan, PlanReview, Portfolio Review, and holdings unchanged',async()=>{const {state,context}=makeFixture(),result=Contract.validate(validDecision(context),{context}),plans=JSON.stringify(state.stocks.map(stock=>stock.plans)),reviews=JSON.stringify(state.planReviews),portfolio=JSON.stringify(state.portfolioReview),holdings=JSON.stringify(state.stocks.map(stock=>({shares:stock.shares,currentValue:stock.currentValue}))),saved=await Contract.commit(result,state,{saveCandidate:async candidate=>candidate},{context,now});assert.equal(saved.status,'completed');assert.equal(saved.writes,1);assert.equal(saved.state.decisionCompression.history.length,1);assert.equal(JSON.stringify(saved.state.stocks.map(stock=>stock.plans)),plans);assert.equal(JSON.stringify(saved.state.planReviews),reviews);assert.equal(JSON.stringify(saved.state.portfolioReview),portfolio);assert.equal(JSON.stringify(saved.state.stocks.map(stock=>({shares:stock.shares,currentValue:stock.currentValue}))),holdings);assert.match(saved.snapshot.auditReferences.portfolioReview.reviewHash,/^portfolio_/);assert.ok(saved.snapshot.auditReferences.plans.some(item=>item.plans.some(plan=>plan.planReviewId==='review-d')))});

test('save failure preserves the previous Decision Compression snapshot',async()=>{const {state,context}=makeFixture(),first=Contract.validate(validDecision(context),{context}),seeded=Contract.buildCandidate(state,first,{context,savedAt:now}).candidate,before=JSON.stringify(seeded),failed=await Contract.commit(first,seeded,{saveCandidate:async()=>{throw new Error('disk full')},rollback:()=>{}},{context});assert.equal(failed.status,'failed');assert.equal(failed.writes,1);assert.equal(JSON.stringify(seeded),before)});

test('facts changing after preview fails before persistence',async()=>{const {state,context}=makeFixture(),result=Contract.validate(validDecision(context),{context});state.stocks[0].currentValue=45000;let writes=0;const saved=await Contract.commit(result,state,{saveCandidate:async candidate=>{writes++;return candidate}},{context});assert.equal(saved.status,'invalid');assert.equal(saved.writes,0);assert.equal(writes,0)});

test('request contains the compact authority contract and no Market Regime or Intraday invention route',()=>{const {state}=makeFixture(),request=DecisionContext.buildRequest(state.portfolioReview.current,state.stocks,{allStocks:state.stocks,reviewDate,generatedAt:now,planReviewStore:state.planReviews});for(const phrase of ['程序拥有持仓','AI 只判断','historical_only 仅作历史参考','当前没有权威市场环境或盘中模块','最多 5 个详细处理','blockerPriority','blockerFacts','noActionSymbols','确定性交易指令','计划变化后应写'])assert.match(request,new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.ok(request.length<28000)});

test('mobile first layer is width-safe, Chinese-only at render boundaries, and detailed Portfolio Review remains expandable',()=>{const ui=fs.readFileSync(path.join(__dirname,'../src/portfolio-review-ui.js'),'utf8');for(const phrase of ['今日组合结论','今日处理','立即复核','等待确认','风险控制','观察','暂不处理','查看详细组合复核','已选但暂不处理 · ${noAction.length}只'])assert.match(ui,new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(ui,/@media\(max-width:640px\)/);assert.match(ui,/overflow-x:hidden/);assert.match(ui,/max-width:100%/);assert.match(ui,/decision\.items\.map\(decisionRow\)/);assert.doesNotMatch(ui,/data-m05c[^\n]+>review_now</)});

test('index loads Decision Compression after its dependencies and before the UI',()=>{const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),positions=['src/plan-review.js','src/portfolio-review-context.js','src/decision-compression-context.js','src/decision-compression-contract.js','src/portfolio-review-ui.js'].map(name=>html.indexOf(name));assert.ok(positions.every(position=>position>=0));assert.deepEqual(positions,[...positions].sort((a,b)=>a-b))});
