'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/discussion-state-contract'),W=require('../src/discussion-workbench'),H=require('../src/homepage-attention'),F=require('./fixtures/discussion-protected-facts');
function setup(shares=6000){const stock=F.stock('none',shares),state={stocks:[stock],trades:[],orders:[],executionLog:[]},p=W.buildDiscussionRequest(stock,{state}),raw=F.judgment(p);return {stock,state,p,raw}}
function save(s){const result=C.process(JSON.stringify(s.raw),F.options(s.p));assert.equal(result.ok,true,result.message);assert.equal(result.previewReady,true);assert.doesNotMatch(C.renderPreview(result),/discussion-post-import-diagnostics/);return C.buildCandidate(s.state,result,{prepared:s.p,now:'2026-09-12T01:00:00Z'})}
for(const raw of ['{','{"currentState":','{}','null','[]','{"currentState":[]}'])test(`unusable JSON stays blocked: ${raw}`,()=>{const s=setup();assert.equal(C.process(raw,F.options(s.p)).previewReady,false)});
for(const mutate of [r=>r.currentState.userDecision=null,r=>r.currentState.userDecision=[],r=>r.currentState.userDecision.headline={},r=>r.currentState.summary=4,r=>r.currentState.confidence='certain',r=>delete r.currentState.trendAssessment,r=>r.currentState.risks=[2]])test(`unusable typed schema blocks: ${mutate}`,()=>{const s=setup();mutate(s.raw);assert.equal(C.process(JSON.stringify(s.raw),F.options(s.p)).ok,false)});
for(const prose of ['当前价格是60元','建议关注60–65','建议仓位2%–3%','建议减仓20%','建议买入1000股','2026-09-12调整判断','当前建议减仓','当前可以建仓','跌破50元止损，70元止盈','突破确认已经成立，完整条件已满足','已卖出1000股，订单已经执行'])test(`explicit content saves unchanged and cannot mutate authority: ${prose}`,()=>{
  const s=setup(),before=structuredClone(s.state);s.raw.currentState.userDecision.headline=prose;const built=save(s);
  assert.equal(built.currentState.userDecision.headline,prose);assert.deepEqual(built.candidate.discussionDecisionsV4.decisions,{});assert.deepEqual(s.state,before);
  const copy=structuredClone(built.candidate);delete copy.discussionDecisionsV4;for(const obj of [copy,before])for(const key of ['discussionState','updatedAt'])delete obj.stocks[0][key];assert.deepEqual(copy,before);
});
for(const [shares,claim,warnings] of [[6000,'当前持有6000股',0],[6000,'当前持有4000股',1],[6000,'当前持仓数量为 4,000 股',1]])test(`snapshot shares comparison: ${claim}`,()=>{const s=setup(shares);s.raw.currentState.userDecision.holding.summary=claim;const built=save(s),rows=C.postImportDiagnostics(built.currentState);assert.equal(rows.filter(d=>d.code==='holding_fact_mismatch').length,warnings);assert.equal(built.currentState.references.holding.shares,shares);assert.ok(rows.every(d=>['warning','info'].includes(d.severity)))});
for(const [shares,claim] of [[0,'继续持有'],[0,'建议减仓'],[0,'保护已有利润'],[0,'持仓止盈'],[100,'当前没有持仓']])test(`position discrepancy warns only after import: ${shares} ${claim}`,()=>{const s=setup(shares);s.raw.currentState.userDecision.headline=claim;const built=save(s);assert.ok(C.postImportDiagnostics(built.currentState).some(d=>d.code==='position_semantic_mismatch'));assert.match(C.renderDiagnostics(built.currentState),/核对提示/)});
for(const claim of ['建议关注60–65','建议卖出1000股','建议买入1000股','如果当前持有4000股，则先观察','此前持有4000股','AI说“当前持有4000股”','目前建议持有4000股','无需减仓','如果未来持仓，可以减仓','不建议继续持有'])test(`ambiguous/proposal text does not create a current-fact warning: ${claim}`,()=>{const s=setup(0);s.raw.currentState.userDecision.warning.summary=claim;assert.deepEqual(C.postImportDiagnostics(save(s).currentState),[])});
test('historical agreement is independent of later applicability and survives serialization',()=>{
  const s=setup();s.raw.currentState.userDecision.holding.summary='当前持有6000股';const first=save(s);const stock=first.candidate.stocks[0];stock.shares=3200;
  const saved=W.normalizeStore(JSON.parse(JSON.stringify(stock.discussionState))).current;assert.deepEqual(C.postImportDiagnostics(saved),[]);assert.notEqual(W.stateFreshness(stock,saved,{state:first.candidate}).status,'current');
  const p=W.buildDiscussionRequest(stock,{state:first.candidate}),raw=F.judgment(p);const second=save({state:first.candidate,p,raw}).candidate.stocks[0].discussionState;
  assert.equal(second.history[0].references.holding.shares,6000);assert.deepEqual(C.postImportDiagnostics(second.history[0]),[]);assert.equal(second.history[0].userDecision.holding.summary,'当前持有6000股');
});
test('historical mismatch remains tied to original snapshot even when live shares later match AI',()=>{const s=setup();s.raw.currentState.summary='当前持有4000股';const b=save(s);b.candidate.stocks[0].shares=4000;const current=W.normalizeStore(b.candidate.stocks[0].discussionState).current;assert.equal(C.postImportDiagnostics(current)[0].code,'holding_fact_mismatch')});
test('Homepage respects canonical zero shares with imported held-position statuses',()=>{const s=setup(0);s.raw.currentState.userDecision=F.judgment(setup(100).p).currentState.userDecision;s.raw.currentState.actionAssessment.category='reduce_review';const b=save(s);assert.equal(H.selectActionSignal(b.currentState,false).debug.suppressionReason,'position_mismatch');assert.deepEqual(b.candidate.discussionDecisionsV4.decisions,{})});
test('warning markup escapes AI content and never exposes a disabling control',()=>{const s=setup(0);s.raw.currentState.userDecision.headline='继续持有<script>alert(1)</script>';const b=save(s),html=C.renderDiagnostics(b.currentState);assert.doesNotMatch(html,/<script|disabled|<button/);assert.match(html,/仓位语义核对/)});
