'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const W=require('../src/discussion-workbench.js'),C=require('../src/discussion-state-contract.js'),F=require('./fixtures/discussion-reliability.js');
const ui=fs.readFileSync(require.resolve('../src/ui-render.js'),'utf8');
function renderer(){const sandbox={window:{DiscussionWorkbench:W,DiscussionStateContract:C},discussionOptions:()=>({}),discussionReadinessPanel:()=>'',esc:String,formatChineseText:String,zhConfidence:String,arrSafe:v=>Array.isArray(v)?v:[]};vm.createContext(sandbox);vm.runInContext(ui.slice(ui.indexOf('function discussionStatusPresentation'),ui.indexOf('function discussionHistoryPanel')),sandbox);vm.runInContext(ui.slice(ui.indexOf('function aiDiscussionWorkspacePanel'),ui.indexOf('const DETAIL_WORKSPACE_META')),sandbox);return sandbox}
for(const kind of ['v1','v2','v3','none','pending','historical'])test(`shared CTA renders exactly once for ${kind}`,()=>{const stock=F.stock(kind),html=renderer().aiDiscussionWorkspacePanel(stock);for(const action of ['start-stock-discussion','prepare-discussion-archive'])assert.equal(html.split(`data-detail-action="${action}"`).length-1,1);assert.ok(html.indexOf('>开始讨论<')<html.indexOf('>导入结论<'));const prompt=W.buildDiscussionRequest(stock);assert.ok(prompt.request);if(kind==='pending')assert.equal(C.assessTechnicalAnchorReadiness(prompt).ready,false)});
for(const kind of ['none','v1','v2','v3','historical','pending'])test(`zero holding fact and shared prompt rules survive ${kind}`,()=>{const stock=F.stock(kind,0),p=W.buildDiscussionRequest(stock),a=W.buildArchiveRequest(p);for(const request of [p.request,a.request]){assert.match(request,/当前持仓数量：0/);assert.match(request,/当前为零持仓标的/);assert.match(request,/当前 canonical 持仓事实优先于历史结论/);assert.match(request,/内容差异不会阻断 Discussion 导入/)}assert.equal(p.context.currentFacts.holding.shares,0);if(kind==='pending')assert.match(p.request,/技术.*|日K/)});
for(const shares of [0,100])test(`valid ${shares} shares output saves with program-owned facts`,async()=>{const stock=F.stock('none',shares),p=W.buildDiscussionRequest(stock),raw=F.judgment(p),parsed=C.process(JSON.stringify(raw),F.options(p));assert.equal(parsed.previewReady,true,parsed.message);let writes=0,saved;const result=await C.commit(parsed,{stocks:[stock]},{saveCandidate:async c=>{writes++;saved=c}},{prepared:p});assert.equal(result.status,'completed',result.error?.message);assert.equal(writes,1);assert.equal(saved.stocks[0].discussionState.current.references.holding.shares,shares);assert.equal(stock.discussionState.current,null);assert.equal(raw.currentState.shares,undefined)});
for(const wording of ['继续持有','建议减仓','关注止盈','继续持有，关注止盈'])test(`zero-position content saves without changing holdings: ${wording}`,async()=>{const stock=F.stock('none',0),p=W.buildDiscussionRequest(stock),raw=F.judgment(p);raw.currentState.userDecision.headline=wording;const result=C.process(JSON.stringify(raw),F.options(p));assert.equal(result.ok,true);assert.equal(result.previewReady,true);let saved;const done=await C.commit(result,{stocks:[stock]},{saveCandidate:c=>{saved=c}},{prepared:p});assert.equal(done.status,'completed');assert.equal(saved.stocks[0].shares,0);assert.equal(saved.stocks[0].discussionState.current.userDecision.headline,wording)});
test('archive example is valid for zero and held facts',()=>{for(const shares of [0,100]){const p=W.buildDiscussionRequest(F.stock('none',shares)),request=W.buildArchiveRequest(p).request,raw=request.slice(request.lastIndexOf('\n{')+1);const result=C.process(raw,F.options(p));assert.equal(result.ok,true,result.message)}});
