'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/entry-decision'),W=require('../src/discussion-workbench'),C=require('../src/discussion-state-contract'),F=require('./fixtures/discussion-protected-facts');
function setup(shares=0){const stock=F.stock('none',shares),state={stocks:[stock],trades:[],orders:[]},p=W.buildDiscussionRequest(stock,{state});return {state,p,raw:F.judgment(p)}}
function ready(path='breakout_confirmation'){return {...E.example(),state:'entry_ready',path,directionConfirmed:true,confirmationSatisfied:true,position:'acceptable',completedConditions:['突破近期压力并稳定保持']}}
function apply(s,e){s.raw.currentState.actionAssessment.entryDecision=e;const d=s.raw.currentState.userDecision;for(const [key,summary] of Object.entries({holding:'当前无持仓。',takeProfit:'当前无持仓，不适用。',stopLoss:'尚未持有，无需处理。'}))d[key]={status:'not_applicable',summary};d.positionDirection.status=e.state==='setup_forming'||e.state==='entry_ready'?'add_review':e.state==='entry_extended'?'add_watch':'not_applicable';d.addAssessment.status=e.state==='entry_ready'?'add_review':'wait';if(e.state==='entry_ready'){d.headline='建仓条件已经满足。';d.addAssessment.summary='当前已经满足首次建仓复核条件。'}s.raw.currentState.actionAssessment.category={entry_ready:'entry_review',entry_extended:'wait_confirmation',setup_forming:'wait_confirmation',wait_setup:'no_action',setup_failed:'no_action'}[e.state];return s}
function save(s){const result=C.process(JSON.stringify(s.raw),F.options(s.p));assert.equal(result.previewReady,true,result.message);return C.buildCandidate(s.state,result,{prepared:s.p,now:'2026-09-19T01:00:00Z'})}
function prior(path='breakout_confirmation'){const s=apply(setup(),{...E.example(),state:'setup_forming',path});s.raw.currentState.actionAssessment.upgradeConditions=['突破近期压力并稳定保持'];return save(s).currentState}
function codes(current,previous){return E.evaluate(current,previous,0).diagnostics.map(d=>d.code)}
for(const path of Object.keys(E.PATHS).filter(p=>p!=='none'))test(`independent ready path round-trip: ${path}`,()=>{const s=apply(setup(),ready(path)),b=save(s),stored=W.normalizeStore(JSON.parse(JSON.stringify(b.candidate.stocks[0].discussionState))).current;assert.deepEqual(stored.actionAssessment.entryDecision,ready(path));assert.equal(E.evaluate(stored,null,0).expectedState,'entry_ready');assert.deepEqual(codes(stored),[]);assert.deepEqual(W.buildDiscussionRequest(b.candidate.stocks[0],{state:b.candidate}).context.currentState.actionAssessment.entryDecision,ready(path))});
test('Case A old upgrade condition satisfied cannot become another pullback requirement',()=>{const previous=prior(),s=apply(setup(),{...ready(),state:'setup_forming',previousConditions:[{condition:previous.actionAssessment.upgradeConditions[0],status:'satisfied',evidence:'新增完整日K站稳压力上方'}],pendingConditions:['再等一次回踩']}),b=save(s);assert.ok(codes(b.currentState,previous).includes('entry_goalpost_moved'));assert.equal(E.evaluate(b.currentState,previous,0).expectedState,'entry_ready');assert.deepEqual(b.currentState.actionAssessment.entryDecision,s.raw.currentState.actionAssessment.entryDecision);assert.ok(C.postImportDiagnostics(b.currentState,previous).some(d=>d.code==='entry_new_requirement'))});
test('Case B pullback migrates to direct breakout without waiting for both paths',()=>{const previous=prior('pullback_confirmation'),s=apply(setup(),{...ready(),previousConditions:[{condition:previous.actionAssessment.upgradeConditions[0],status:'satisfied',evidence:'已突破并稳定保持'}],transitionReason:'没有深回踩，新增突破并稳定保持证据'});assert.deepEqual(codes(save(s).currentState,previous),[])});
test('Case C breakout failure cannot be ready and can form or fail',()=>{for(const state of ['entry_ready','setup_forming','setup_failed']){const s=apply(setup(),{...ready(),state,negativeEvidence:[{type:'breakout_failure',detail:'突破后快速跌回原区域',isNew:true}]});assert.equal(codes(save(s).currentState).includes('entry_ready_conflict'),state==='entry_ready')}});
test('Case D extension is distinct from failure',()=>{const s=apply(setup(),{...ready(),state:'entry_extended',position:'extended'}),b=save(s);assert.equal(E.evaluate(b.currentState,null,0).expectedState,'entry_extended');assert.deepEqual(codes(b.currentState),[]);b.currentState.actionAssessment.entryDecision.state='setup_failed';assert.ok(codes(b.currentState).includes('entry_failure_unsupported'))});
test('Case E extended breakout migrates to a confirmed platform',()=>{const previous=save(apply(setup(),{...ready(),state:'entry_extended',position:'extended'})).currentState;previous.actionAssessment.upgradeConditions=[];const s=apply(setup(),{...ready('platform_breakout'),completedConditions:['平台波动收敛','承接稳定、结构修复','再次突破并保持'],transitionReason:'首次上涨后整理收敛，新增平台突破证据'});assert.deepEqual(codes(save(s).currentState,previous),[])});
test('Case F a large rise alone does not veto an intact structure',()=>{const s=apply(setup(),ready());s.raw.currentState.risks=['涨幅较大'];assert.deepEqual(codes(save(s).currentState),[]);s.raw.currentState.actionAssessment.entryDecision.state='setup_failed';s.raw.currentState.actionAssessment.entryDecision.position='extended';s.raw.currentState.userDecision.addAssessment.status='avoid';assert.ok(codes(save(s).currentState).includes('entry_extension_not_failure'))});
test('ready downgrade requires new negative evidence, not repeated old risk',()=>{const previous=save(apply(setup(),ready())).currentState;previous.actionAssessment.upgradeConditions=[];const s=apply(setup(),{...ready(),state:'setup_forming',confirmationSatisfied:false,negativeEvidence:[{type:'support_failure',detail:'承接失败',isNew:false}]});assert.ok(codes(save(s).currentState,previous).includes('entry_downgrade_unexplained'));s.raw.currentState.actionAssessment.entryDecision.negativeEvidence[0].isNew=true;assert.ok(!codes(save(s).currentState,previous).includes('entry_downgrade_unexplained'))});
test('missing previous commitment and unexplained path switch are diagnostic only',()=>{const s=apply(setup(),ready('platform_breakout')),previous=prior();const b=save(s);assert.ok(codes(b.currentState,previous).includes('entry_commitment_missing'));assert.ok(codes(b.currentState,previous).includes('entry_path_change_unexplained'))});
test('old V3 without entryDecision imports and displays without inferred entry state',()=>{const s=setup(),b=save(s);assert.equal(b.currentState.schemaVersion,'stock-discussion.state.v3');assert.equal(b.currentState.actionAssessment.entryDecision,undefined);assert.equal(E.render(b.currentState,0,C.escapeHtml),'');const previous=b.currentState,current=save(apply(setup(),ready())).currentState;assert.ok(codes(current,previous).includes('entry_commitment_missing'))});
test('held and unknown shares never run the entry evaluator or render entry status',()=>{for(const shares of [100,null,undefined]){const s=apply(setup(100),ready()),b=save(s);assert.equal(E.evaluate(b.currentState,prior(),shares).applicable,false);assert.equal(E.render(b.currentState,shares,C.escapeHtml),'')}const p=setup(100).p;assert.doesNotMatch(p.request,/ENTRY_DECISION_PATH_ENGINE/);assert.doesNotMatch(W.buildArchiveRequest(p).request,/ENTRY_DECISION_PATH_ENGINE/)});
test('Plan, holdings and all protected domains remain unchanged, original candidate is untouched',()=>{const s=apply(setup(),ready()),before=structuredClone(s.state),b=save(s);assert.deepEqual(s.state,before);const candidate=structuredClone(b.candidate);delete candidate.discussionDecisionsV4;for(const x of [candidate,before])for(const k of ['discussionState','updatedAt'])delete x.stocks[0][k];assert.deepEqual(candidate,before);assert.deepEqual(b.candidate.discussionDecisionsV4.decisions,{})});
for(const mutate of [e=>e.state='invalid',e=>e.path='buy',e=>e.directionConfirmed='yes',e=>e.position=4,e=>e.completedConditions=[{}],e=>e.previousConditions=[{condition:'x',status:'satisfied',evidence:4}],e=>e.negativeEvidence=[{type:'breakout_failure',detail:'x',isNew:'yes'}],e=>e.extra=true])test(`structural errors still reject entry extension: ${mutate}`,()=>{const s=apply(setup(),ready());mutate(s.raw.currentState.actionAssessment.entryDecision);assert.equal(C.process(JSON.stringify(s.raw),F.options(s.p)).ok,false)});
test('both prompt phases contain commitments, three paths, mappings and zero-position contracts',()=>{const s=setup();for(const prompt of [s.p.request,W.buildArchiveRequest(s.p).request]){for(const term of [...Object.keys(E.PATHS),...Object.keys(E.STATES),'Previous upgrade conditions are commitments','当前无持仓。','尚未持有，无需处理。','不得写回 Plan'])assert.ok(prompt.includes(term),term)}const a=JSON.parse(W.buildArchiveRequest(s.p).request.split('\n').at(-1));assert.equal(E.validate(a.currentState.actionAssessment.entryDecision).ok,true)});
test('renderer escapes evidence and exposes distinct state and progress',()=>{const s=apply(setup(),{...ready(),completedConditions:['<script>x</script>']}),html=E.render(s.raw.currentState,0,C.escapeHtml);assert.match(html,/建仓条件已满足/);assert.match(html,/突破确认/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>/)});
test('entry omission after a tracked path stays importable but raises a continuity warning',()=>{const previous=save(apply(setup(),ready())).currentState,current=save(setup()).currentState;assert.ok(codes(current,previous).includes('entry_review_missing'))});
test('a previous held-position condition does not become a new entry commitment',()=>{const held=setup(100),b=save(held);b.candidate.stocks[0].shares=0;const p=W.buildDiscussionRequest(b.candidate.stocks[0],{state:b.candidate});assert.match(E.rules(p.context),/上一轮判断.*：null/);assert.deepEqual(codes(save(apply(setup(),ready())).currentState,b.currentState),[])});
test('ready wording and zero position text mismatches warn without rejecting import',()=>{const s=apply(setup(),ready());s.raw.currentState.userDecision.headline='等待进一步确认';s.raw.currentState.userDecision.holding.summary='当前状态稳定。';const b=save(s);assert.ok(codes(b.currentState).includes('entry_ready_wording_conflict'));assert.ok(codes(b.currentState).includes('entry_zero_position_contract'))});
test('preview shows the structured entry state only from canonical zero shares',()=>{const s=apply(setup(),ready()),result=C.process(JSON.stringify(s.raw),F.options(s.p));assert.match(C.renderPreview(result,{holdingShares:0}),/当前建仓状态/);assert.doesNotMatch(C.renderPreview(result,{holdingShares:100}),/当前建仓状态/)});

function migratedFixture(){const previous=prior('pullback_confirmation');previous.actionAssessment.upgradeConditions=['回踩460附近稳定承接后重新转强。','或突破478并稳定保持。'];const s=apply(setup(),{...ready(),previousConditions:[{condition:previous.actionAssessment.upgradeConditions[0],status:'invalidated',evidence:'没有回踩，已改走直接突破路径。'},{condition:previous.actionAssessment.upgradeConditions[1],status:'satisfied',evidence:'已突破478并稳定保持。'}],transitionReason:'没有回踩，直接突破478并站稳，合法平行路径完成。'});return {s,previous}}
test('real AI regression: confirmed parallel migration can supersede an untriggered path',()=>{const {s,previous}=migratedFixture();assert.deepEqual(codes(save(s).currentState,previous),[])});
for(const mutate of [e=>e.state='setup_forming',e=>e.confirmationSatisfied=false,e=>e.pendingConditions=['再等一天'],e=>e.transitionReason='',e=>e.previousConditions[1].status='pending'])test(`migration exception cannot excuse unsupported invalidation: ${mutate}`,()=>{const {s,previous}=migratedFixture();mutate(s.raw.currentState.actionAssessment.entryDecision);assert.ok(codes(save(s).currentState,previous).includes('entry_invalidation_unexplained'))});
test('archive template copies whole previous commitments without splitting compound conditions',()=>{const s=apply(setup(),{...E.example(),state:'setup_forming',path:'breakout_confirmation'}),conditions=['价格有效突破478并稳定保持、不快速跌回、位置可接受时，升级为entry_ready。','或回踩460承接后转强。'];s.raw.currentState.actionAssessment.upgradeConditions=conditions;const b=save(s),p=W.buildDiscussionRequest(b.candidate.stocks[0],{state:b.candidate}),request=W.buildArchiveRequest(p).request,example=JSON.parse(request.split('\n').at(-1));assert.deepEqual(example.currentState.actionAssessment.entryDecision.previousConditions.map(x=>x.condition),conditions);assert.ok(C.process(JSON.stringify(example),F.options(p)).ok);assert.match(request,/不得缩写、改写、拆分或合并/)});
test('empty and held previous state do not seed false entry commitments',()=>{for(const shares of [0,100]){const p=setup(shares).p,example=JSON.parse(W.buildArchiveRequest(p).request.split('\n').at(-1));assert.deepEqual(example.currentState.actionAssessment.entryDecision?.previousConditions||[],[])}});
test('both prompt phases distinguish general high-price warnings from actual veto evidence',()=>{const p=setup().p;for(const request of [p.request,W.buildArchiveRequest(p).request]){assert.match(request,/已经发生、实质否定建仓条件/);assert.match(request,/不得放进 negativeEvidence.other/);assert.match(request,/negativeEvidence=\[\]/)}});

test('archive reinforces nested object closure and exact zero-position wording',()=>{const request=W.buildArchiveRequest(setup().p).request;assert.match(request,/必须先闭合 actionAssessment/);assert.match(request,/summary 不得追加说明或改写/)});

function extensionFixture(){const previous=prior();const s=apply(setup(),{...ready(),state:'entry_extended',position:'extended',pendingConditions:['等待位置修复后重新评估'],previousConditions:[{condition:previous.actionAssessment.upgradeConditions[0],status:'satisfied',evidence:'原突破已站稳'}],transitionReason:'突破已经确认，随后快速延伸至550，等待合理位置修复。'});s.raw.currentState.actionAssessment.category='wait_confirmation';s.raw.currentState.userDecision.positionDirection.status='add_watch';return {s,previous}}
test('real AI regression: acknowledged extension may await position repair without a goalpost warning',()=>{const {s,previous}=extensionFixture();assert.ok(!codes(save(s).currentState,previous).includes('entry_new_requirement'))});
for(const mutate of [e=>e.position='acceptable',e=>e.confirmationSatisfied=false,e=>e.transitionReason='',e=>e.state='setup_forming'])test(`position repair exception requires a confirmed explained extension: ${mutate}`,()=>{const {s,previous}=extensionFixture();mutate(s.raw.currentState.actionAssessment.entryDecision);assert.ok(codes(save(s).currentState,previous).includes('entry_new_requirement'))});
