'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),F=require('./fixtures/discussion-protected-facts'),E=require('../src/entry-decision');
const output=path.resolve(process.env.CLARITY_OUTPUT||'test-results/entry-clarity/browser'),url='http://127.0.0.1:8768/';
const viewports=[{width:360,height:800},{width:390,height:844},{width:1280,height:900}];
const cases=[{id:'A-forming-pullback',state:'setup_forming',path:'pullback_confirmation',completed:['已出现承接'],pending:['收回关键结构并保持']},{id:'B-forming-breakout',state:'setup_forming',path:'breakout_confirmation',pending:['突破压力并稳定保持']},{id:'C-ready-conflict',state:'entry_ready',path:'breakout_confirmation',completed:['突破压力并稳定保持']},{id:'D-extended',state:'entry_extended',path:'breakout_confirmation',completed:['原突破已确认']},{id:'E-failed',state:'setup_failed',path:'none'},{id:'F-old-v3'},{id:'G-intermediate',state:'setup_forming',path:'pullback_confirmation',pending:['确认已出现承接'],reason:'这是中间观察条件，并非最终升级条件'},{id:'H-wait',state:'wait_setup',path:'none'}];
function rawFor(p,c){const raw=F.judgment(p),a=raw.currentState.actionAssessment,d=raw.currentState.userDecision;d.headline='当前暂不建仓，继续空仓观察';d.positionDirection.summary='继续空仓观察';d.addAssessment.summary='满足后再评估';d.warning={summary:'波动仍然较高，请留意已有风险。',items:['原有风险提示必须保留']};if(!c.state)return raw;for(const [key,summary] of Object.entries({holding:'当前无持仓。',takeProfit:'当前无持仓，不适用。',stopLoss:'尚未持有，无需处理。'}))d[key]={status:'not_applicable',summary};d.positionDirection.status=['setup_forming','entry_ready'].includes(c.state)?'add_review':c.state==='entry_extended'?'add_watch':'not_applicable';d.addAssessment.status='wait';
 a.entryDecision={...E.example(),state:c.state,path:c.path,directionConfirmed:c.state!=='wait_setup'&&c.state!=='setup_failed',confirmationSatisfied:['entry_ready','entry_extended'].includes(c.state),position:c.state==='entry_extended'?'extended':'acceptable',completedConditions:c.completed||[],pendingConditions:c.pending||[],transitionReason:c.reason||'',negativeEvidence:c.state==='setup_failed'?[{type:'breakout_failure',detail:'突破后快速跌回原区间',isNew:true}]:[]};a.upgradeConditions=c.pending||[];a.category={wait_setup:'no_action',setup_forming:'wait_confirmation',entry_ready:'entry_review',entry_extended:'wait_confirmation',setup_failed:'no_action'}[c.state];return raw;}
function stock(){const s=F.stock('none',0);Object.assign(s,{id:'clarity-yofc-copy',code:'601869.SS',name:'长飞光纤·Clarity测试副本',currentPrice:482});return s;}
(async()=>{fs.mkdirSync(output,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||undefined}),report=[];try{for(const viewport of viewports){const context=await browser.newContext({viewport}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());await context.route('**/*',r=>new URL(r.request().url()).origin===new URL(url).origin?r.continue():r.abort());await page.goto(url);await page.waitForFunction(()=>document.getElementById('main')?.dataset.storageState==='ready');await page.waitForLoadState('networkidle');assert.equal(await page.locator('meta[name="app-asset-version"]').getAttribute('content'),'entry-decision-clarity-v1-20260920');
 const card=page.locator('.discussion-workbench > .discussion-user-decision-card'),authority=()=>page.evaluate(()=>JSON.stringify({shares:state.stocks[0].shares,plans:state.stocks[0].plans,price:state.stocks[0].currentPrice,bars:state.stocks[0].priceHistory,technical:state.stocks[0].technicalData,runtime:state.planRuntimeStates,orders:state.orders,trades:state.trades}));
 async function reset(sample){await page.evaluate(async ({s,sample})=>{s.plans=[420,400].map((price,i)=>{const p=PlanV2.createPlan({id:'clarity-plan-'+i,action:'buy',triggerPrice:price,triggerDirection:'below',quantity:100,note:'既有计划，隔离测试副本'},{source:'manual'});p.validityStatus='needs_review';return p});if(sample)s.discussionState=DiscussionWorkbench.normalizeStore({current:sample.current,history:sample.history});state=createValidatedCandidateSnapshot({stocks:[s]});await persistCandidateSnapshot(state);discussionPreparedContexts.clear();render();openStockDetail(s.id,'ai')},{s:stock(),sample});}
 for(const c of cases){await reset(null);const before=await authority();await page.locator('[data-detail-action="start-stock-discussion"]').click();await page.locator('#discussionPromptCloseBtn').click();const p=await page.evaluate(()=>discussionPreparedContexts.get(discussionStockKey(state.stocks[0]))),raw=rawFor(p,c);await page.locator('[data-detail-action="import-discussion-state"]').click();await page.locator('#discussionImportText').fill(JSON.stringify(raw));await page.locator('#discussionImportPreviewBtn').click();assert.equal(await page.locator('#discussionImportConfirmBtn').isEnabled(),true);assert.equal(await page.locator('#discussionImportPreview .discussion-entry-decision').count(),c.state?1:0);assert.equal(await page.locator('#discussionImportPreview .discussion-post-import-diagnostics').count(),0);if(c.state)assert.equal(await page.locator('#discussionImportPreview .discussion-original-decision').getAttribute('open'),null);await page.locator('#discussionImportConfirmBtn').click();await page.waitForFunction(()=>!document.getElementById('discussionImportDialog').classList.contains('show'));assert.equal(await authority(),before);
 const entry=card.locator('.discussion-entry-decision');if(c.state){assert.match(await entry.locator('.discussion-entry-status').innerText(),new RegExp(E.STATES[c.state]));assert.match(await entry.locator('.discussion-entry-path').innerText(),new RegExp(E.PATHS[c.path]));assert.equal(await card.locator('.discussion-original-decision').getAttribute('open'),null);assert.equal(await card.locator('.discussion-user-headline').isVisible(),false);assert.equal(await entry.locator('.discussion-entry-outcome').count(),c.state==='setup_forming'&&!c.reason?1:0);if(c.state==='setup_forming'&&!c.reason)assert.match(await entry.locator('.discussion-entry-outcome').innerText(),/满足后：[\s\S]*建仓条件成立/);assert.match(await card.locator('.is-warning').innerText(),/原有风险提示必须保留/);assert.match(await card.locator('.discussion-program-references').innerText(),/既有 Plan[\s\S]*420[\s\S]*400[\s\S]*needs_review[\s\S]*不作为当前建仓路径的唯一条件/);if(c.state==='entry_ready'){assert.doesNotMatch(await entry.innerText(),/暂不建仓|继续等待|再评估/);assert.ok(await card.locator('[data-diagnostic="entry_ready_wording_conflict"]').count());assert.equal(await entry.locator('.is-pending li').count(),0)}if(c.state==='entry_extended')assert.doesNotMatch(await entry.innerText(),/本轮建仓结构已失效/);if(c.state==='setup_failed')assert.match(await entry.innerText(),/失效依据[\s\S]*突破后快速跌回/);
 }else{assert.equal(await entry.count(),0);assert.equal(await card.locator('.discussion-user-headline').isVisible(),true)}
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await card.screenshot({path:path.join(output,`${c.id}-${viewport.width}.png`)});if(['A-forming-pullback','C-ready-conflict'].includes(c.id)){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(output,`screen-${c.id}-${viewport.width}.png`)});}const saved=await page.evaluate(()=>state.stocks[0].discussionState.current);assert.deepEqual(saved.userDecision,raw.currentState.userDecision);if(c.state){await card.locator('.discussion-original-decision > summary').click();assert.equal(await card.locator('.discussion-user-headline').isVisible(),true);assert.match(await card.locator('.discussion-original-decision').innerText(),/当前暂不建仓/);assert.equal(await authority(),before)}report.push({viewport:viewport.width,case:c.id,pass:true,protectedFactsUnchanged:true,originalAiPreserved:true});}
 // Re-render authentic, previously imported AI records without changing their judgments or bindings.
 if(process.env.CLARITY_REAL_AI_SAMPLES){for(const [kind,file] of Object.entries({forming:'final-real-ai/case2-round1-saved.json',ready:'final-case1-repeat/case1-round2-saved.json',extended:'fix2-real-ai/case4-round2-saved.json',failed:'fix2-case7-normalized-retry/case7-round2-saved.json'})){const sample=JSON.parse(fs.readFileSync(path.join(process.env.CLARITY_REAL_AI_SAMPLES,file),'utf8'));await reset(sample);const before=await authority(),saved=await page.evaluate(()=>state.stocks[0].discussionState.current);assert.deepEqual(saved,sample.current);assert.match(await card.locator('.discussion-entry-status').innerText(),new RegExp(E.STATES[saved.actionAssessment.entryDecision.state]));assert.match(await card.locator('.discussion-entry-path').innerText(),new RegExp(E.PATHS[saved.actionAssessment.entryDecision.path]));assert.equal(await card.locator('.discussion-user-headline').isVisible(),false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await card.screenshot({path:path.join(output,`real-${kind}-${viewport.width}.png`)});assert.equal(await authority(),before);assert.deepEqual(await page.evaluate(()=>state.stocks[0].discussionState.current),sample.current);report.push({viewport:viewport.width,realSample:kind,source:file,pass:true,originalAiPreserved:true,protectedFactsUnchanged:true});}}
 await page.evaluate(()=>{state.stocks[0].shares=100;renderStockDetail()});assert.equal(await card.locator('.discussion-entry-decision').count(),0);assert.equal(await card.locator('.discussion-user-headline').isVisible(),true);assert.deepEqual(errors,[]);await context.close();}
 }finally{await browser.close()}fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.length,viewports:viewports.map(v=>v.width),realSamplesIncluded:!!process.env.CLARITY_REAL_AI_SAMPLES,results:report}));})().catch(e=>{console.error(e);process.exitCode=1});
