'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const E=require('../src/entry-decision'),W=require('../src/discussion-workbench'),C=require('../src/discussion-state-contract'),F=require('./fixtures/discussion-protected-facts');
function fixture(state='setup_forming',shares=0){const stock=F.stock('none',shares),snapshot={stocks:[stock],orders:[],trades:[]},p=W.buildDiscussionRequest(stock,{state:snapshot}),raw=F.judgment(p),a=raw.currentState.actionAssessment,d=raw.currentState.userDecision;
 a.entryDecision={...E.example(),state,path:'breakout_confirmation',directionConfirmed:true,confirmationSatisfied:state==='entry_ready',position:state==='entry_extended'?'extended':'acceptable',completedConditions:['已出现承接'],pendingConditions:state==='setup_forming'?['收回关键结构并保持']:[]};a.upgradeConditions=['收回关键结构并保持'];a.reasons=['原结构已经破坏'];a.category=state==='entry_ready'?'entry_review':'wait_confirmation';d.positionDirection.status='add_review';d.addAssessment.status=state==='entry_ready'?'add_review':'wait';return {stock,snapshot,p,raw};}
function saved(f){const result=C.process(JSON.stringify(f.raw),F.options(f.p));assert.ok(result.ok,result.message);return C.buildCandidate(f.snapshot,result,{prepared:f.p,now:'2026-09-20T01:00:00Z'})}
const ui=fs.readFileSync(require.resolve('../src/ui-render'),'utf8'),sandbox={window:{DiscussionWorkbench:W,DiscussionStateContract:C},esc:C.escapeHtml,arrSafe:v=>Array.isArray(v)?v:[],formatChineseText:s=>s,zhConfidence:s=>s};vm.createContext(sandbox);vm.runInContext(ui.slice(ui.indexOf('function discussionProgramPriceReferences'),ui.indexOf('function discussionHistoryPanel')),sandbox);
function card(f){const b=saved(f);return sandbox.discussionStateCard(b.currentState,'当前结论',b.candidate.stocks[0]);}
const stateLabels={wait_setup:'尚未形成建仓条件',setup_forming:'建仓条件正在形成',entry_ready:'建仓条件已成立',entry_extended:'建仓逻辑仍成立，但当前位置已明显延伸',setup_failed:'本轮建仓结构已失效'};
for(const [state,label] of Object.entries(stateLabels))test(`clarity state label: ${state}`,()=>{const f=fixture(state),html=E.render(f.raw.currentState,0,C.escapeHtml);assert.ok(html.includes(label));if(state==='entry_extended')assert.doesNotMatch(html,/本轮建仓结构已失效/);});
for(const [path,label] of Object.entries({pullback_confirmation:'回踩确认',breakout_confirmation:'突破确认',platform_breakout:'平台后二次突破',none:'暂无明确建仓路径'}))test(`clarity path label: ${path}`,()=>{const f=fixture();f.raw.currentState.actionAssessment.entryDecision.path=path;assert.ok(E.render(f.raw.currentState,0,C.escapeHtml).includes(label));});
test('completed and pending conditions remain separate verbatim lists',()=>{const html=E.render(fixture().raw.currentState,0,C.escapeHtml);assert.match(html,/is-complete[\s\S]*✓[\s\S]*已出现承接/);assert.match(html,/is-pending[\s\S]*○[\s\S]*收回关键结构并保持/)});
for(const path of ['pullback_confirmation','breakout_confirmation'])test(`final upgrade result is explicit for ${path}`,()=>{const f=fixture();f.raw.currentState.actionAssessment.entryDecision.path=path;assert.match(E.render(f.raw.currentState,0,C.escapeHtml),/满足后：[\s\S]*→ 建仓条件成立/)});
for(const place of ['pending','transition','upgrade'])test(`explicit intermediate ${place} does not promise entry_ready`,()=>{const f=fixture(),a=f.raw.currentState.actionAssessment;if(place==='pending')a.entryDecision.pendingConditions=['这是中间观察条件'];if(place==='transition')a.entryDecision.transitionReason='这是阶段性确认条件，并非最终升级条件';if(place==='upgrade')a.upgradeConditions=['该条件只是中间条件'];assert.doesNotMatch(E.render(f.raw.currentState,0,C.escapeHtml),/discussion-entry-outcome/)});
test('missing upgrade commitments never acquire an invented final outcome',()=>{const f=fixture();f.raw.currentState.actionAssessment.upgradeConditions=[];assert.doesNotMatch(E.render(f.raw.currentState,0,C.escapeHtml),/discussion-entry-outcome/)});
test('empty condition arrays stay empty and do not borrow lower Plan prices',()=>{const f=fixture('entry_ready'),a=f.raw.currentState.actionAssessment;a.entryDecision.completedConditions=[];const html=E.render(f.raw.currentState,0,C.escapeHtml);assert.match(html,/AI 未列出已完成条件/);assert.match(html,/无待满足条件/);assert.doesNotMatch(html,/<li>|420|400|继续等待|再评估/)});
test('failed state exposes only supplied failure evidence',()=>{const f=fixture('setup_failed');f.raw.currentState.actionAssessment.entryDecision.negativeEvidence=[{type:'breakout_failure',detail:'突破后快速跌回原区间',isNew:true}];assert.match(E.render(f.raw.currentState,0,C.escapeHtml),/失效依据[\s\S]*突破后快速跌回原区间/)});
test('ready wins display priority while contradictory originals and diagnostics survive',()=>{const f=fixture('entry_ready');f.raw.currentState.userDecision.headline='继续等待进一步确认';f.raw.currentState.userDecision.addAssessment.summary='满足后再评估';const before=structuredClone(f),html=card(f);assert.ok(html.indexOf('discussion-entry-decision')<html.indexOf('discussion-original-decision'));assert.match(html,/<details class="discussion-original-decision">[\s\S]*继续等待进一步确认[\s\S]*满足后再评估/);assert.match(html,/data-diagnostic="entry_ready_wording_conflict"/);assert.deepEqual(f,before)});
test('preview uses same priority, keeps risks visible and stays diagnostic-free',()=>{const f=fixture('entry_ready');f.raw.currentState.userDecision.headline='暂不建仓';f.raw.currentState.userDecision.warning.items=['波动较高'];const result=C.process(JSON.stringify(f.raw),F.options(f.p)),html=C.renderPreview(result,{holdingShares:0});assert.ok(html.indexOf('discussion-entry-decision')<html.indexOf('discussion-original-decision'));assert.match(html,/<\/details><div class="discussion-preview-risk">[\s\S]*波动较高/);assert.doesNotMatch(html,/discussion-post-import-diagnostics/)});
test('Plan references stay distinct with understandable needs_review guidance',()=>{const f=fixture(),b=saved(f);f.stock.plans=[{id:'existing',action:'buy',triggerPrice:420,status:'active',validityStatus:'needs_review'}];const html=sandbox.discussionStateCard(b.currentState,'当前结论',f.stock);assert.match(html,/既有 Plan · 程序事实/);assert.match(html,/既有计划待复核，不作为当前建仓路径的唯一条件/);assert.ok(html.indexOf('discussion-program-references')>html.indexOf('discussion-entry-decision'));assert.doesNotMatch(E.render(b.currentState,0,C.escapeHtml),/420/)});
for(const shares of [100,null])test(`canonical ${shares} does not acquire zero-position presentation`,()=>{const f=fixture('entry_ready'),b=saved(f),stock=b.candidate.stocks[0];stock.shares=shares;const html=sandbox.discussionStateCard(b.currentState,'当前结论',stock);assert.doesNotMatch(html,/discussion-entry-decision|discussion-original-decision/);assert.match(html,/discussion-user-headline/)});
test('old V3 falls back without synthesizing Entry Decision',()=>{const f=fixture();delete f.raw.currentState.actionAssessment.entryDecision;const html=card(f);assert.doesNotMatch(html,/discussion-entry-decision|discussion-original-decision/);assert.match(html,/discussion-user-headline/)});
test('render and permissive import preserve AI content and all protected facts',()=>{const f=fixture('entry_ready');f.raw.currentState.userDecision.headline='当前暂不建仓';const before=structuredClone(f.snapshot),b=saved(f);assert.deepEqual(b.currentState.userDecision,f.raw.currentState.userDecision);E.render(b.currentState,0,C.escapeHtml);card(f);assert.deepEqual(f.snapshot,before);const stripped=structuredClone(b.candidate);delete stripped.discussionDecisionsV4;for(const key of ['discussionState','updatedAt']){delete stripped.stocks[0][key];delete before.stocks[0][key]}assert.deepEqual(stripped,before)});
test('conditions and original explanation are escaped without changing saved text',()=>{const f=fixture();f.raw.currentState.actionAssessment.entryDecision.pendingConditions=['<img src=x onerror=alert(1)>'];const html=E.render(f.raw.currentState,0,C.escapeHtml);assert.match(html,/&lt;img/);assert.doesNotMatch(html,/<img/)});

for(const field of ['headline','positionDirection','addAssessment'])test(`ready conflict wording in ${field} stays diagnostic only`,()=>{const f=fixture('entry_ready'),d=f.raw.currentState.userDecision;if(field==='headline')d.headline='当前暂不建仓，继续空仓观察';else d[field].summary='继续空仓观察';const before=structuredClone(f.raw),b=saved(f);assert.ok(C.postImportDiagnostics(b.currentState).some(x=>x.code==='entry_ready_wording_conflict'));assert.deepEqual(f.raw,before);assert.match(E.render(b.currentState,0,C.escapeHtml),/建仓条件已成立/)});

for(const text of ['这并非最终条件','这只是一项观察信号'])test(`intermediate outcome qualifier stays conditional: ${text}`,()=>{const f=fixture();f.raw.currentState.actionAssessment.entryDecision.transitionReason=text;assert.doesNotMatch(E.render(f.raw.currentState,0,C.escapeHtml),/discussion-entry-outcome/)});
