const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Sync=require('../src/manual-analysis-sync.js'),Adapter=require('../src/long-term-logic-sync-adapter.js');
const payload={investmentThesis:'验证需求增长和利润改善能否持续。',coreDrivers:['需求增长'],keyRisks:['竞争加剧'],reviewTriggers:['利润率恶化'],logicStatus:'valid',confidence:'medium',nextReviewDate:'2026-12-01'};
const state=()=>({stocks:[{id:'fixture',code:'1810.HK',name:'小米',longTermLogic:{schemaVersion:'long-term-logic.v2',...payload}}]});
const row=async()=>({moduleType:'long_term_logic',entityKey:'1810.HK',moduleSchemaVersion:'long-term-logic.v2',revision:1,payloadHash:await Sync.payloadHash(payload),publishedAt:'2026-09-05T00:00:00Z',payload});
for(const [name,change] of Object.entries({unknown:r=>({...r,status:'future_unknown_status'}),missing:()=>null,revision:r=>({...r,module:{...r.module,revision:null}}),hash:r=>({...r,module:{...r.module,payloadHash:null}}),wrongIdentity:r=>({...r,module:{...r.module,entityKey:'0700.HK'}}),shortTimestamp:r=>({...r,module:{...r.module,publishedAt:'2026'}}),badTimestamp:r=>({...r,module:{...r.module,publishedAt:'bad'}}),wrongRevision:r=>({...r,module:{...r.module,revision:7}}),stringRevision:r=>({...r,module:{...r.module,revision:'1'}}),badPayload:r=>({...r,module:{...r.module,payload:{...payload,investmentThesis:'changed'}}}),extra:r=>({...r,extra:true})}))test(`publish fails closed: ${name}`,async()=>{
  const module=await row(),engine=Sync.createEngine({transport:{getCurrent:async()=>null,publish:async()=>change({status:'published',module})}});engine.register(Adapter);
  const result=await engine.confirmPublish(await engine.preparePublish('long_term_logic','1810.HK',state()),state());assert.equal(result.status,'verification_failed');assert.equal(result.cloudCommitUnknown,true);assert.equal(result.writes,0);
});
for(const status of ['published','no_change','conflict'])test(`RPC contract accepts ${status}`,async()=>{
 const module=await row(),engine=Sync.createEngine({transport:{getCurrent:async()=>null,publish:async()=>({status,module})}});engine.register(Adapter);
 assert.equal((await engine.confirmPublish(await engine.preparePublish('long_term_logic','1810.HK',state()),state())).status,status==='conflict'?'stale_cloud':status);
});
test('missing stock blocks fetch/preview/confirm without canonical writes; explicit add unlocks same revision',async()=>{
 const module=await row();let writes=0;const engine=Sync.createEngine({transport:{listCurrent:async()=>[module],getCurrent:async()=>module}});engine.register(Adapter);let local={stocks:[]};const before=JSON.stringify(local);
 const updates=await engine.fetchUpdates(local);assert.equal(updates.updates.length,1);assert.equal(updates.updates[0].eligibility.ok,false);
 const preview=await engine.prepareApply(updates.updates[0],local);assert.equal(preview.status,'unavailable');assert.equal((await engine.confirmApply(preview,local,{saveCandidate:()=>writes++})).status,'invalid_preview');assert.equal(writes,0);assert.equal(JSON.stringify(local),before);
 local={stocks:[{id:'fixture',code:'1810.HK'}]};const available=(await engine.fetchUpdates(local)).updates[0];assert.equal(available.eligibility.ok,true);assert.equal(available.envelope.revision,1);
 const ready=await engine.prepareApply(available,local);const result=await engine.confirmApply(ready,local,{saveCandidate:c=>{writes++;return c}});assert.equal(result.status,'applied');assert.equal(writes,1);
 assert.equal((await engine.confirmApply(ready,{stocks:[]},{saveCandidate:()=>writes++})).status,'unavailable');assert.equal(writes,1);
});
test('one client restores legacy storage, shares refresh/concurrent requests, signs out once and resumes pending work',async()=>{
 const owner='11111111-1111-4111-8111-111111111111',storage=new Map([['universe-auth-fixture',JSON.stringify({user:{id:owner},access_token:'fixture-initial'})]]);let session,callback,constructs=0,subscriptions=0,signouts=0,committed;const inserts=[],rpcs=[],events=[];
 const sdk={auth:{getSession:async()=>({data:{session},error:null}),onAuthStateChange:fn=>{subscriptions++;callback=fn},signInWithPassword:async()=>{session={user:{id:owner},access_token:'fixture-login'};callback('SIGNED_IN',session);return {data:{session}}},signOut:async()=>{signouts++;session=null;callback('SIGNED_OUT',null);return {}}},from:()=>({upsert:async value=>{inserts.push({value,session});return {}}}),rpc:async()=>{rpcs.push(session);return {data:[]}}};
 const ctx={console,Promise,URL,TextEncoder,crypto:require('node:crypto').webcrypto,setTimeout:(fn,ms)=>setTimeout(fn,Math.min(ms,2)),clearTimeout,navigator:{onLine:true},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)},addEventListener:()=>{},StorageManager:{subscribeStateCommits:fn=>{committed=fn}},UNIVERSE_CLOUD_CONFIG:{projectRef:'fixture',url:'https://fixture.supabase.co',publishableKey:'sb_publishable_fixture'},UniverseSupabaseSdk:{createClient:(_url,_key,options)=>{constructs++;assert.equal(options.auth.storageKey,'universe-auth-fixture');session=JSON.parse(storage.get(options.auth.storageKey));return sdk}}};ctx.window=ctx;ctx.globalThis=ctx;vm.createContext(ctx);
 for(const file of ['symbol-identity','strict-ai-json','universe-handoff','long-term-logic-contract','long-term-logic-sync-adapter','manual-analysis-sync','supabase-browser-client','universe-auto-add','manual-analysis-sync-cloud'])vm.runInContext(fs.readFileSync(`src/${file}.js`,'utf8'),ctx);
 const wait=()=>new Promise(r=>setTimeout(r,20));await ctx.UniverseAutoAdd.initialize({stocks:[]});const engine=ctx.ManualAnalysisSyncCloud.initialize();ctx.SupabaseBrowserClient.onAuthStateChange((event,value)=>events.push(value?.user?.id||null));await wait();
 assert.equal(constructs,1);assert.equal(subscriptions,1);assert.equal(ctx.UniverseAutoAdd.getClient(),ctx.ManualAnalysisSyncCloud.getClient());assert.equal((await ctx.SupabaseBrowserClient.getUser()).id,owner);assert.equal(ctx.UniverseAutoAdd.status().signedIn,true);
 session={user:{id:owner},access_token:'fixture-refreshed'};callback('TOKEN_REFRESHED',session);callback('TOKEN_REFRESHED',session);await wait();
 await Promise.all([committed(state()).then(()=>ctx.UniverseAutoAdd.retry()),engine.fetchUpdates(state())]);assert.equal(inserts[0].session,session);assert.equal(rpcs[0],session);assert.equal(events.length,2);
 await ctx.UniverseAutoAdd.signOut();await wait();assert.equal(signouts,1);assert.equal(ctx.UniverseAutoAdd.status().signedIn,false);await assert.rejects(engine.fetchUpdates(state()),e=>e.status===401);
 await committed({stocks:[...state().stocks,{id:'two',code:'0700.HK'}]});await wait();assert.equal(ctx.UniverseAutoAdd.status().pending,1);
 await ctx.UniverseAutoAdd.signIn('fixture','fixture');await wait();await ctx.UniverseAutoAdd.retry();await engine.fetchUpdates(state());assert.equal(ctx.UniverseAutoAdd.status().pending,0);assert.equal(constructs,1);assert.equal(subscriptions,1);assert.equal(events.filter(v=>v===null).length,1);
 ctx.ManualAnalysisSyncCloud.setRole('publisher');assert.equal(ctx.ManualAnalysisSyncCloud.publisherUi(),true);assert.equal(storage.get('analysis_sync_role'),'publisher');
});
