const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const M=require('../src/management-category'),I=require('../src/symbol-identity'),D=require('../src/discussion-workbench');
const stock=(category='core',shares=100,type='holding')=>({id:'fixture',code:'600001.SS',name:'隔离生命周期',managementCategory:category,shares,type,avgCost:10,plans:[]});
for(const category of ['core','watch','etf'])test(`${category} clear atomically derives candidate and preserves asset type`,()=>{const before=stock(category,100,category==='etf'?'etf':'holding'),copy=JSON.stringify(before),after={...before,shares:0};const result=M.transition(before,after);assert.deepEqual(result,{kind:'clear',category:'candidate'});after.managementCategory=result.category;M.validateState({stocks:[after]});assert.equal(after.type,before.type);assert.equal(JSON.stringify(before),copy)});
for(const category of ['core','watch'])test(`individual rebuild requires explicit ${category}`,()=>{const before=stock('candidate',0),after={...before,shares:1340};assert.throws(()=>M.transition(before,after));for(const invalid of ['candidate','etf','',null])assert.throws(()=>M.transition(before,after,invalid));assert.deepEqual(M.transition(before,after,category),{kind:'build',category})});
test('ETF candidate rebuild derives ETF without changing permanent asset',()=>{const before=stock('candidate',0,'etf');assert.deepEqual(M.transition(before,{...before,shares:10000}),{kind:'build',category:'etf'});assert.equal(before.type,'etf');assert.equal(M.isETF({...before,type:'holding',assetType:'ETF'}),true)});
for(const [old,next] of [[1000,500],[500,1500],[1000,1000]])test(`partial ${old} to ${next} has no lifecycle category write`,()=>{const before=stock('core',old);assert.deepEqual(M.transition(before,{...before,shares:next}),{kind:'none',category:'core'})});
for(const [category,shares,type] of [['candidate',100,'holding'],['core',0,'holding'],['watch',0,'holding'],['etf',0,'etf'],['etf',100,'holding'],['core',100,'etf'],['watch',100,'etf']])test(`save guard blocks ${category}/${shares}/${type}`,()=>{assert.throws(()=>M.validateState({stocks:[stock(category,shares,type)]}),/需要修复/)});
test('read-only inconsistent inventory and explicit repair never infer on load',()=>{const state={stocks:[stock('core',0),{...stock('candidate',100),id:'second',code:'600002.SS'}, {id:'cash',type:'etf',shares:0}]},binding=JSON.stringify(state);assert.equal(M.pending(state.stocks).length,2);assert.equal(JSON.stringify(state),binding);const next=M.buildAssignmentCandidate(state,[{id:'fixture',symbol:'600001.SS',managementCategory:'candidate'},{id:'second',symbol:'600002.SS',managementCategory:'watch'}],I.canonicalMarketSymbol,M.assignmentSession(state.stocks,I.canonicalMarketSymbol));M.validateState(next);assert.equal(JSON.stringify(state),binding);assert.deepEqual(next.stocks[2],state.stocks[2])});
test('legacy and special records remain readable without category creation',()=>{const legacy=stock();delete legacy.managementCategory;const state={stocks:[legacy,{id:'cash',shares:100,type:'etf',managementCategory:'candidate'}]},binding=JSON.stringify(state);M.validateState(state);assert.equal(JSON.stringify(state),binding);assert.equal(M.pending(state.stocks).length,1)});
test('category-only Discussion context remains byte equivalent; cross-zero meaningful holding fact only',()=>{const before=stock(),a=D.buildContext(before,{state:{stocks:[before]}}),after={...before,managementCategory:'watch'};assert.deepEqual(D.buildContext(after,{state:{stocks:[after]}}),a);const cleared={...before,shares:0,managementCategory:'candidate'},other={...cleared,managementCategory:'core'};assert.deepEqual(D.buildContext(cleared,{state:{stocks:[cleared]}}),D.buildContext(other,{state:{stocks:[other]}}));assert.equal(D.buildContext(cleared,{state:{stocks:[cleared]}}).context.currentFacts.holding.shares,0)});
test('actual operation applies detached shares/category/audit once and rejects false/failed/stale/duplicate saves',async()=>{
 const drafts=new Map(),ctx={console,TextEncoder,crypto:require('node:crypto').webcrypto,ManagementCategory:M,StorageManager:{getDraft:(kind,key)=>drafts.get(key),saveDraft:async(kind,key,value)=>drafts.set(key,value)}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('src/operation-entry.js','utf8'),ctx);const O=ctx.OperationEntry;
 const state={stocks:[stock()],operationApplicationAudits:[]},context=O.manualContext(state.stocks[0]),draft={...O.defaultDraft(context),new_shares:0,new_avg_cost:0};await O.saveDraft(context,draft,O.validate(draft,context),await O.snapshotHash(context.stock));const item=O.saved(O.contextKey(context)),before=JSON.stringify(state),options={category:'candidate',confirmed:true,binding:before};
 let writes=0;await assert.rejects(O.applyDirectResult(state,context,item,()=>{writes++}));assert.equal(writes,0);
 for(const save of [async()=>false,async()=>{throw Error('fixture failure')}]){await assert.rejects(O.applyDirectResult(state,context,item,async candidate=>{assert.equal(JSON.stringify(state),before);assert.equal(candidate.stocks[0].managementCategory,'candidate');return save()},undefined,options));assert.equal(JSON.stringify(state),before)}
 await assert.rejects(O.applyDirectResult(state,context,item,()=>{writes++},undefined,{...options,binding:'stale'}));assert.equal(writes,0);
 await O.applyDirectResult(state,context,item,async candidate=>{M.validateState(candidate);assert.equal(JSON.stringify(state),before);writes++},undefined,options);assert.equal(writes,1);assert.equal(state.stocks[0].shares,0);assert.equal(state.stocks[0].managementCategory,'candidate');assert.equal(state.operationApplicationAudits.length,1);await assert.rejects(O.applyDirectResult(state,context,item,()=>{writes++},undefined,options));assert.equal(writes,1);
});
