'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),F=require('./fixtures/discussion-reliability');
const output=path.resolve('test-results/lifecycle-browser'),url='http://127.0.0.1:8768/';
(async()=>{fs.mkdirSync(output,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||undefined}),results=[];
try{for(const viewport of [{width:360,height:800},{width:390,height:844},{width:1280,height:900}]){
const context=await browser.newContext({viewport,acceptDownloads:true}),page=await context.newPage(),errors=[],dialogs=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{dialogs.push(d.message());await d.dismiss()});
await context.route('**/*',r=>new URL(r.request().url()).origin===new URL(url).origin?r.continue():r.abort());
await page.goto(url);await page.waitForFunction(()=>document.getElementById('main')?.dataset.storageState==='ready');
await page.evaluate(()=>{globalThis.lifePersist=persistCandidateSnapshot;globalThis.lifeWrites=0;persistCandidateSnapshot=async candidate=>{if(globalThis.lifeFail==='throw')throw Error('模拟失败');if(globalThis.lifeFail==='false')return false;lifeWrites++;return lifePersist(candidate)}});
const setup=async(category,shares,type='holding')=>{const s=F.stock('none',shares);Object.assign(s,{id:'life',managementCategory:category,type,role:'核心仓'});await page.evaluate(async stock=>{document.getElementById('holdingLifecycleDialog')?.remove();closeModal(true);globalThis.lifeFail=null;const candidate=createValidatedCandidateSnapshot({stocks:[stock,{id:'cash',name:'现金(手动维护)',type:'etf',role:'现金',shares:0,currentValue:500}],updatedAt:Date.now()});await lifePersist(candidate);state=candidate;lifeWrites=0;discussionPreparedContexts.clear();navigateWorkbench('targets');openStockDetail(stock.id,'ai');globalThis.lifeBefore=structuredClone(state)},s)};
const pair=()=>page.evaluate(()=>[state.stocks[0].shares,state.stocks[0].managementCategory,state.stocks[0].type]);
const edit=async shares=>{await page.evaluate(()=>openModal('life'));await page.locator('#fShares').fill(String(shares));await page.locator('#saveBtn').click()};
const confirm=async choice=>{if(choice)await page.locator('#holdingLifecycleCategory').selectOption(choice);await page.locator('#holdingLifecycleConfirm').click();await page.waitForFunction(()=>!document.getElementById('modal').classList.contains('show'))};
for(const [category,before,after,type,choice,expected] of [['core',1000,500,'holding',null,'core'],['core',1000,0,'holding',null,'candidate'],['watch',100,0,'holding',null,'candidate'],['etf',10000,0,'etf',null,'candidate'],['candidate',0,100,'holding','core','core'],['candidate',0,1340,'holding','watch','watch'],['candidate',0,10000,'etf',null,'etf']]){
 await setup(category,before,type);await page.evaluate(()=>{globalThis.lifeDiscussion=DiscussionWorkbench.buildDiscussionRequest(state.stocks[0],discussionOptions())});await edit(after);
 if((before>0)!==(after>0)){assert.equal(await page.evaluate(()=>lifeWrites),0);assert.deepEqual(await pair(),[before,category,type]);const choices=await page.locator('#holdingLifecycleCategory option').evaluateAll(nodes=>nodes.map(n=>n.value));assert.deepEqual(choices,after===0?['candidate']:type==='etf'?['etf']:['','core','watch']);if(choice){await page.locator('#holdingLifecycleConfirm').click();assert.match(await page.locator('#holdingLifecycleError').innerText(),/请选择|选择/);assert.equal(await page.evaluate(()=>lifeWrites),0)}await page.screenshot({path:path.join(output,`preview-${category}-${before}-${after}-${viewport.width}.png`)});await confirm(choice)}
 else await page.waitForFunction(()=>!document.getElementById('modal').classList.contains('show'));
 assert.deepEqual(await pair(),[after,expected,type]);assert.equal(await page.evaluate(()=>lifeWrites),1);assert.equal(await page.evaluate(()=>detailStockId),'life');
 assert.equal(await page.evaluate(()=>JSON.stringify(state.executionLog||[])===JSON.stringify(lifeBefore.executionLog||[])&&JSON.stringify(state.operationApplicationAudits||[])===JSON.stringify(lifeBefore.operationApplicationAudits||[])),true);
 const reconciliation=await page.evaluate(()=>DiscussionStateContract.reconcileContext(lifeDiscussion,DiscussionWorkbench.buildContext(state.stocks[0],discussionOptions()),{transport:'manual'}));assert.notEqual(reconciliation.status,'hard_block');
 await page.evaluate(()=>{detailStockId=null;render()});assert.equal(await page.locator(`[data-target-filter="${expected}"]`).getAttribute('aria-pressed'),'true');assert.equal(await page.locator('[data-target-edit="life"]').count(),1);
 assert.equal(await page.evaluate(()=>ManagementCategory.values.reduce((n,k)=>n+state.stocks.filter(s=>ManagementCategory.matches(s,k)).length,0)),1);
}
// Current State import after real confirmed cross-zero edits retains Holding Reconciliation.
for(const [before,after,category,choice] of [[100,0,'core',null],[0,100,'candidate','watch']]){
 await setup(category,before);await page.evaluate(()=>{startStockDiscussion(state.stocks[0]);closeDiscussionPromptDialog();globalThis.lifeOriginal=discussionPreparedContexts.get(discussionStockKey(state.stocks[0]))});await edit(after);await confirm(choice);
 await page.locator('[data-detail-action="import-discussion-state"]').click();const current=await page.evaluate(()=>DiscussionWorkbench.buildContext(state.stocks[0],discussionOptions())),raw=F.judgment(current);raw.currentState.sourceDiscussionVersion=await page.evaluate(()=>lifeOriginal.sourceDiscussionVersion);
 await page.locator('#discussionImportText').fill(JSON.stringify(raw));await page.locator('#discussionImportPreviewBtn').click();assert.equal(await page.locator('#discussionHoldingAcknowledgeBtn').isVisible(),true);await page.locator('#discussionHoldingAcknowledgeBtn').click();assert.equal(await page.locator('#discussionImportConfirmBtn').isEnabled(),true);await page.locator('#discussionImportConfirmBtn').click();await page.waitForFunction(()=>!document.getElementById('discussionImportDialog').classList.contains('show'));assert.equal(await page.evaluate(()=>Boolean(state.stocks[0].discussionState.current)),true);
}
// Invalid field and shared StorageManager gate both block, with no writes.
await setup('core',100);await page.evaluate(()=>openModal('life'));await page.locator('#fManagementCategory').selectOption('candidate');await page.locator('#saveBtn').click();assert.match(await page.locator('#fManagementCategoryError').innerText(),/候选仓/);assert.equal(await page.evaluate(()=>lifeWrites),0);
assert.equal(await page.evaluate(async()=>{const invalid=structuredClone(state);invalid.stocks[0].managementCategory='candidate';try{await StorageManager.saveState(invalid,{critical:true});return false}catch(e){return /需要修复/.test(e.message)}}),true);
// Two kinds of storage failure preserve canonical pair and all unrelated data.
for(const failure of ['throw','false']){await setup('watch',100);await page.evaluate(value=>lifeFail=value,failure);await edit(0);await page.locator('#holdingLifecycleConfirm').click();await page.waitForFunction(()=>!categorySaveBusy);assert.deepEqual(await pair(),[100,'watch','holding']);assert.equal(await page.evaluate(()=>JSON.stringify(state)===JSON.stringify(lifeBefore)),true);await page.evaluate(()=>closeModal(true))}
// Stale preview and duplicate click cannot save twice.
await setup('core',100);await edit(0);await page.evaluate(()=>state.stocks[0].managementCategory='watch');await page.locator('#holdingLifecycleConfirm').click();assert.match(await page.locator('#holdingLifecycleError').innerText(),/数据已变化/);assert.equal(await page.evaluate(()=>lifeWrites),0);await page.locator('#holdingLifecycleCancel').click();await page.evaluate(()=>closeModal(true));
await setup('core',100);await edit(0);await page.evaluate(()=>{const b=document.getElementById('holdingLifecycleConfirm');b.click();b.click()});await page.waitForFunction(()=>!categorySaveBusy);assert.equal(await page.evaluate(()=>lifeWrites),1);
// Category-only change preserves exact protected context and has no holding confirmation.
await setup('core',100);await page.evaluate(()=>{globalThis.lifeContext=JSON.stringify(DiscussionWorkbench.buildContext(state.stocks[0],discussionOptions()));openModal('life')});await page.locator('#fManagementCategory').selectOption('watch');await page.locator('#saveBtn').click();await page.waitForFunction(()=>!categorySaveBusy);assert.equal(await page.locator('#holdingLifecycleDialog').count(),0);assert.equal(await page.evaluate(()=>JSON.stringify(DiscussionWorkbench.buildContext(state.stocks[0],discussionOptions()))===lifeContext),true);
// Explicit inconsistent-backup repair adopts only after Preview/Confirm; old legacy loads unchanged.
await setup('core',100);await page.evaluate(()=>{const backup=structuredClone(state);backup.stocks[0].shares=0;globalThis.lifeBadBackup=backup;openCategoryAssignment(backup)});assert.equal(await page.locator('#categoryAssignmentDialog').isVisible(),true);assert.deepEqual(await pair(),[100,'core','holding']);await page.locator('[data-category-id="life"]').selectOption('candidate');await page.locator('#categoryAssignmentReview').click();assert.equal(await page.evaluate(()=>lifeWrites),0);await page.locator('#categoryAssignmentConfirm').click();await page.waitForFunction(()=>!document.getElementById('categoryAssignmentDialog'));assert.deepEqual(await pair(),[0,'candidate','holding']);assert.equal(await page.evaluate(()=>Object.hasOwn(state.stocks[1],'managementCategory')),false);
await page.evaluate(async()=>{const backup=alpha3ExportSnapshot(state);const restored=createValidatedCandidateSnapshot(backup,{touchUpdatedAt:false});if(JSON.stringify(backup.stocks.map(s=>[s.shares,s.managementCategory,s.type]))!==JSON.stringify(restored.stocks.map(s=>[s.shares,s.managementCategory,s.type])))throw Error('round trip mismatch');delete restored.stocks[0].managementCategory;await lifePersist(restored);state=restored;navigateWorkbench('targets')});assert.equal(await page.locator('#targetAssign').count(),1);
// Actual operation UI uses the same clear/build confirmation and creates just one factual audit.
for(const [category,before,after,type,choice,expected] of [['watch',100,0,'holding',null,'candidate'],['candidate',0,100,'holding','watch','watch'],['candidate',0,100,'etf',null,'etf']]){
 await setup(category,before,type);await page.evaluate(()=>{document.getElementById('main').innerHTML=operationWorkspacePanel(state.stocks[0])});
 await page.locator('#operationEntryNewShares').fill(String(after));await page.locator('#operationEntryNewAvgCost').fill(after?'10':'0');await page.evaluate(()=>{globalThis.lifeOperation=confirmOperationEntry(state.stocks[0])});await page.waitForSelector('#holdingLifecycleDialog');if(choice)await page.locator('#holdingLifecycleCategory').selectOption(choice);await page.locator('#holdingLifecycleConfirm').click();await page.waitForFunction(()=>!operationConfirmBusy);assert.deepEqual(await pair(),[after,expected,type]);assert.equal(await page.evaluate(()=>state.operationApplicationAudits.length),1);assert.equal(await page.evaluate(()=>lifeWrites),1);
}
// Compatibility execution is a user-recorded event; only its explicit auto-update mode changes holdings.
await setup('core',100);await page.evaluate(()=>{state.stocks[0].plans=[PlanV2.createPlan({id:'life-plan',action:'sell',triggerPrice:10,triggerDirection:'above',quantity:100},{source:'manual'})];globalThis.lifeNativeConfirm=confirm;confirm=()=>true;globalThis.lifeExecute=executePlan('life','life-plan')});await page.waitForSelector('#holdingLifecycleDialog');await page.locator('#holdingLifecycleConfirm').click();await page.evaluate(async()=>{await lifeExecute;confirm=lifeNativeConfirm});assert.deepEqual(await pair(),[0,'candidate','holding']);assert.equal(await page.evaluate(()=>state.executionLog.length),1);assert.equal(await page.evaluate(()=>lifeWrites),1);
// Stale tab cannot overwrite newer canonical category/shares.
await setup('core',100);await edit(0);const other=await context.newPage();await other.goto(url);await other.waitForFunction(()=>document.getElementById('main')?.dataset.storageState==='ready');await other.evaluate(async()=>{const candidate=structuredClone(state);candidate.stocks[0].managementCategory='watch';candidate.updatedAt=Date.now()+100;await persistCandidateSnapshot(candidate);state=candidate});await page.locator('#holdingLifecycleConfirm').click();await page.waitForFunction(()=>!categorySaveBusy);assert.deepEqual(await pair(),[100,'core','holding']);assert.equal(await other.evaluate(async()=>(await StorageManager.loadState()).stocks[0].managementCategory),'watch');await other.close();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);results.push({viewport,clearBuildPartial:true,directCorrection:true,categoryOnlyDiscussion:true,operation:true,storageFailure:true,stalePreview:true,duplicate:true,backupRepair:true,noOverflow:true,errors});await context.close();
}}finally{await browser.close()}
fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results));
})().catch(e=>{console.error(e);process.exitCode=1});
