'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const PlanV2=require('../src/plan-v2.js');
const PortfolioContext=require('../src/portfolio-review-context.js');
const PortfolioContract=require('../src/portfolio-review-contract.js');

const now='2026-08-27T10:00:00.000Z';
function plan(overrides={}){return PlanV2.createPlan({action:'buy',triggerPrice:100,triggerDirection:'below',quantity:100,note:'分批复核',allocationConstraint:{maxPositionPct:12,targetWeightRange:'8%-12%'},conditions:{technical:['支撑确认'],fundamental:['逻辑未破坏']},...overrides},{now,source:overrides.source||'manual'})}
function stock(plans,currentPrice=105){return {id:'s1',name:'测试标的',code:'600000.SS',type:'holding',shares:100,currentPrice,targetPct:10,capPct:12,plans}}

test('canonical normalization exposes the Plan V2 schema',()=>{const value=plan();for(const key of ['id','schemaVersion','planVersion','action','triggerPrice','triggerDirection','status','validityStatus','createdAt','updatedAt','lastReviewedAt','nextReviewDate','validUntil','priceTriggerStatus','triggeredAt','fullConditionStatus','conditions','invalidationReason','terminatedAt','source','note'])assert.ok(Object.hasOwn(value,key),key);assert.equal(value.schemaVersion,'plan.v2')});
test('new plan timestamps are program owned',()=>{const value=plan();assert.equal(value.createdAt,now);assert.equal(value.updatedAt,now);assert.equal(value.lastReviewedAt,null)});
test('AI timestamps cannot override authoritative timestamps',()=>{const value=PlanV2.createPlan({action:'sell',triggerPrice:120,triggerDirection:'above',createdAt:'1999-01-01T00:00:00Z',updatedAt:'1999-01-02T00:00:00Z'},{now,source:'ai_refresh'});assert.equal(value.createdAt,now);assert.equal(value.updatedAt,now)});
test('legacy AI timestamps are retained only as audit provenance',()=>{const value=PlanV2.normalizePlan({action:'sell',price:120,triggerOn:'above',source:'ai_plan_refresh',createdAt:'1999-01-01T00:00:00Z',updatedAt:'1999-01-02T00:00:00Z',lastReviewedAt:'1999-01-03T00:00:00Z',triggeredAt:'1999-01-04T00:00:00Z',fullConditionStatus:'confirmed'});assert.equal(value.createdAt,null);assert.equal(value.updatedAt,null);assert.equal(value.lastReviewedAt,null);assert.equal(value.triggeredAt,null);assert.equal(value.fullConditionStatus,'unproven');assert.equal(value.legacy.originalTimestamps.createdAt,'1999-01-01T00:00:00Z');assert.equal(value.legacy.originalTimestamps.updatedAt,'1999-01-02T00:00:00Z')});
test('legacy price-only plan preserves unknown original fields',()=>{const value=PlanV2.normalizePlan({id:'old',action:'buy',price:88,note:'旧计划',customPremise:{x:1}});assert.equal(value.triggerPrice,88);assert.deepEqual(value.legacy.originalFields.customPremise,{x:1})});
test('legacy plan without review date becomes needs review',()=>{assert.equal(PlanV2.normalizePlan({action:'sell',price:120,triggerOn:'above'}).validityStatus,'needs_review')});
test('legacy migration does not invent created or reviewed dates',()=>{const value=PlanV2.normalizePlan({action:'buy',price:88,updatedAt:'2025-01-01T00:00:00Z'});assert.equal(value.createdAt,null);assert.equal(value.lastReviewedAt,null)});
test('legacy migration is idempotent',()=>{const first=PlanV2.normalizePlan({action:'buy',price:88,triggerOn:'below',extra:'keep'});assert.deepEqual(PlanV2.normalizePlan(first),first)});
test('ordinary edit preserves rich fields',()=>{const current=plan({validUntil:'2026-12-31'}),edited=PlanV2.applyAuthoritativeEdit(current,{triggerPrice:98,note:'调整价位'},{now:'2026-08-28T00:00:00Z'});assert.deepEqual(edited.conditions,current.conditions);assert.deepEqual(edited.allocationConstraint,current.allocationConstraint);assert.equal(edited.createdAt,current.createdAt);assert.equal(edited.source,current.source)});
test('authoritative edit increments plan version',()=>{const current=plan(),edited=PlanV2.applyAuthoritativeEdit(current,{note:'新备注'},{now:'2026-08-28T00:00:00Z'});assert.equal(edited.planVersion,current.planVersion+1);assert.equal(edited.updatedAt,'2026-08-28T00:00:00Z')});
test('no-op edit does not increment plan version',()=>{const current=plan(),edited=PlanV2.applyAuthoritativeEdit(current,{note:current.note},{now:'2026-08-28T00:00:00Z'});assert.equal(edited.planVersion,current.planVersion);assert.equal(edited.updatedAt,current.updatedAt)});
test('reconfirm sets review date and next review',()=>{const legacy=PlanV2.normalizePlan({id:'legacy',action:'sell',price:120,triggerOn:'above'}),reviewed=PlanV2.reconfirmPlan(legacy,{now:'2026-08-28T00:00:00Z',nextReviewDate:'2026-09-27'});assert.equal(reviewed.validityStatus,'active');assert.equal(reviewed.lastReviewedAt,'2026-08-28T00:00:00Z');assert.equal(reviewed.nextReviewDate,'2026-09-27');assert.equal(reviewed.planVersion,2)});
test('reconfirm refuses confirmed invalidation evidence',()=>{const value=plan({conditions:{invalidation:[{text:'逻辑破坏',status:'confirmed'}]}});assert.throws(()=>PlanV2.reconfirmPlan(value,{now}),/失效证据/)});
test('price trigger never confirms full conditions',()=>{const value=plan(),observed=PlanV2.observePriceTrigger(PlanV2.observePriceTrigger(value,110,{now}),95,{now:'2026-08-28T00:00:00Z'});assert.equal(observed.priceTriggerStatus,'triggered');assert.equal(observed.fullConditionStatus,'unproven')});
test('triggeredAt is set on first proven crossing',()=>{const before=PlanV2.observePriceTrigger(plan(),110,{now}),crossed=PlanV2.observePriceTrigger(before,99,{now:'2026-08-28T00:00:00Z'});assert.equal(before.triggeredAt,null);assert.equal(crossed.triggeredAt,'2026-08-28T00:00:00Z')});
test('triggeredAt preserves the original crossing time',()=>{const before=PlanV2.observePriceTrigger(plan(),110,{now}),first=PlanV2.observePriceTrigger(before,99,{now:'2026-08-28T00:00:00Z'}),later=PlanV2.observePriceTrigger(first,90,{now:'2026-08-29T00:00:00Z'});assert.equal(later.triggeredAt,first.triggeredAt)});
test('already-triggered legacy plan receives no fabricated triggeredAt',()=>{const value=PlanV2.normalizePlan({action:'buy',price:100,triggerOn:'below'},{currentPrice:90,observePrice:true,now});assert.equal(value.priceTriggerStatus,'triggered');assert.equal(value.triggeredAt,null)});
test('completed plan remains a historical object',()=>{const current=plan(),done=PlanV2.terminatePlan(current,'completed',{now});assert.equal(done.id,current.id);assert.equal(done.status,'completed');assert.equal(done.validityStatus,'completed');assert.ok(done.terminatedAt)});
test('cancelled plan remains a historical object',()=>{const value=PlanV2.terminatePlan(plan(),'cancelled',{now});assert.equal(value.status,'cancelled');assert.equal(value.validityStatus,'invalid')});
test('replaced plan remains a historical object',()=>{const value=PlanV2.terminatePlan(plan(),'replaced',{now});assert.equal(value.status,'replaced');assert.equal(value.validityStatus,'invalid')});
test('execution implementation records Plan ID and version',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/rebalance.js'),'utf8');assert.match(source,/planId:completed\.id/);assert.match(source,/planVersion:completed\.planVersion/);assert.doesNotMatch(source,/\.filter\(x=>x\.id!==planId\)/)});
test('buy plan preserves allocation constraint',()=>{const value=plan();assert.deepEqual(value.allocationConstraint,{maxPositionPct:12,targetWeightRange:'8%-12%'})});
test('missing legacy allocation premise lowers validity without fabrication',()=>{const value=PlanV2.normalizePlan({action:'buy',price:100,triggerOn:'below'});assert.equal(value.validityStatus,'needs_review');assert.equal(value.allocationConstraint.maxPositionPct,null)});
test('condition categories survive JSON round trip',()=>{const value=plan({conditions:{technical:['均线确认'],fundamental:['盈利未恶化'],catalyst:['公告确认'],allocation:['不超过上限'],market:['市场稳定'],invalidation:['逻辑破坏']}}),round=PlanV2.normalizePlan(JSON.parse(JSON.stringify(value)));for(const key of ['technical','fundamental','catalyst','allocation','market','invalidation'])assert.equal(round.conditions[key].length,1,key)});
test('Plan V2 export/import normalization preserves lifecycle and provenance',()=>{const value=PlanV2.terminatePlan(plan({source:'tradeplan_import'}),'completed',{now:'2026-09-01T00:00:00Z'}),round=PlanV2.normalizePlan(JSON.parse(JSON.stringify(value)));assert.deepEqual(round,value)});
test('malformed candidate produces zero authoritative writes',async()=>{let writes=0;const result=await PlanV2.commitCandidate({stocks:[stock([])]},candidate=>{candidate.stocks[0].plans=[null];return candidate},{save:async()=>{writes++}});assert.equal(result.status,'invalid');assert.equal(result.writes,0);assert.equal(writes,0)});
test('failed critical save restores authoritative state',async()=>{const current={stocks:[stock([plan()])]},before=JSON.stringify(current);let rolled=false;const result=await PlanV2.commitCandidate(current,candidate=>{candidate.stocks[0].plans[0]=PlanV2.applyAuthoritativeEdit(candidate.stocks[0].plans[0],{note:'changed'},{now});return candidate},{save:async()=>{throw new Error('fail')},rollback:original=>{rolled=JSON.stringify(original)===before}});assert.equal(result.status,'failed');assert.equal(rolled,true);assert.equal(JSON.stringify(current),before)});
test('near threshold uses trigger-price denominator',()=>{const value=plan();assert.equal(PlanV2.evaluatePriceTrigger(value,105).status,'near');assert.equal(PlanV2.evaluatePriceTrigger(value,106).status,'not_triggered');assert.equal(PlanV2.evaluatePriceTrigger(value,105).distancePct,5)});
test('ambiguous legacy direction is unavailable instead of guessed',()=>{const value=PlanV2.normalizePlan({action:'buy',price:100},{currentPrice:90});assert.equal(value.triggerDirection,null);assert.equal(value.priceTriggerStatus,'unavailable');assert.equal(value.validityStatus,'needs_review')});
test('freshness prioritizes terminal, hard expiry, review date, and legacy uncertainty',()=>{assert.equal(PlanV2.freshness(PlanV2.terminatePlan(plan(),'completed',{now}),'2026-08-27'),'inactive');assert.equal(PlanV2.freshness(plan({validUntil:'2026-08-26'}),'2026-08-27'),'inactive');assert.equal(PlanV2.freshness(plan({nextReviewDate:'2026-08-26'}),'2026-08-27'),'needs_review');assert.equal(PlanV2.freshness(PlanV2.normalizePlan({action:'sell',price:120,triggerOn:'above'}),'2026-08-27'),'historical_only')});
test('Portfolio Review excludes terminal plans and marks legacy caution',()=>{const legacy={id:'legacy',action:'buy',price:100,triggerOn:'below',note:'旧计划'},completed=PlanV2.terminatePlan(plan({action:'sell',triggerDirection:'above'}),'completed',{now}),ctx=PortfolioContext.buildPortfolioContext([stock([legacy,completed],95)],{reviewDate:'2026-08-27'});assert.equal(ctx.stocks[0].plans.length,1);assert.equal(ctx.stocks[0].plans[0].validityStatus,'needs_review');assert.equal(ctx.stocks[0].plans[0].freshness,'historical_only');assert.equal(ctx.stocks[0].plans[0].fullConditionStatus,'unproven')});
test('Portfolio Review receives freshness fields and compact conditions',()=>{const ctx=PortfolioContext.buildPortfolioContext([stock([plan({nextReviewDate:'2026-09-20'})],99)],{reviewDate:'2026-08-27'}),value=ctx.stocks[0].plans[0];for(const key of ['id','planVersion','createdAt','updatedAt','lastReviewedAt','nextReviewDate','validUntil','conditions','allocationConstraint','priceTriggerStatus'])assert.ok(Object.hasOwn(value,key),key)});
test('saved Portfolio Review snapshot keeps plan IDs versions and context hash',()=>{const ctx=PortfolioContext.buildPortfolioContext([stock([plan()],99)],{reviewDate:'2026-08-27'}),review={ok:true,review:{reviewDate:'2026-08-27'}},snapshot=PortfolioContract.buildSnapshot(review,{expectedSymbols:['600000.SS'],planReferences:ctx.planReferences,generatedAt:now,savedAt:now});assert.equal(snapshot.planReferences.stocks[0].plans[0].id,ctx.stocks[0].plans[0].id);assert.equal(snapshot.planReferences.stocks[0].plans[0].planVersion,1);assert.match(snapshot.planReferences.contextHash,/^planctx_/)});
test('mobile Plan UI removes dead script and user-facing internal-plan debug copy',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/ui-render.js'),'utf8');assert.doesNotMatch(source,/apply_plan_update\.py/);assert.doesNotMatch(source,/只展示 active plans/);assert.doesNotMatch(source,/数据来源：v13DisplayActivePlans/);assert.match(source,/历史计划，日期未知/);assert.match(source,/确认继续有效/)});
test('canonical stable ID survives repeated reload normalization',()=>{const first=PlanV2.normalizePlan({action:'sell',price:120,triggerOn:'above',note:'legacy'}),second=PlanV2.normalizePlan(JSON.parse(JSON.stringify(first)));assert.equal(second.id,first.id);assert.equal(second.planVersion,first.planVersion)});
