'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const W=require('../src/discussion-plan-workflow'),D=require('../src/discussion-v4'),V=require('../src/plan-v4'),P=require('../src/plan-v2'),C=require('../src/plan-context-contract'),F=require('./fixtures/homepage-attention');
function definition(intent='reduce',quantity=20){return V.legacyDefinition(P.createPlan({action:{entry:'buy',increase:'add',reduce:'reduce'}[intent]||'observe',triggerPrice:40,triggerDirection:'below',quantity,conditions:{invalidation:['长期前提不再成立']},allocationConstraint:{maxPositionPct:10,targetWeightRange:null},note:'长期规则'}),intent)}
async function fixture(shares=100){let state=F.state({shares,plans:shares?[P.createPlan({action:'reduce',triggerPrice:50,triggerDirection:'above',quantity:10,conditions:{invalidation:['结构变化']}})]:[]});const p=D.prepareDecision(state,'home-stock',{outcome:'review_plan_change'}),saved=await D.commitDecision(state,p,{saveCandidate:async()=>true},{confirmed:true});assert.equal(saved.status,'completed');state=saved.state;return {state,decision:saved.decision}}
function preview(state,decision,operation,def=null,planId=state.stocks[0].plans[0]?.id){const prepared=W.prepareV4(state,'home-stock',{decisionId:decision.decisionId,operation,planId:operation==='create'?null:planId});const raw=JSON.stringify({...prepared.example,definition:def});const result=W.processV4(raw,{state,prepared});assert.equal(result.ok,true,result.message);return result}
async function commit(result,state){const saved=await W.commitV4(result,state,{saveCandidate:async candidate=>{assert.equal(V.validate(candidate),true);return {state:candidate}}},{confirmed:true});assert.equal(saved.status,'completed',saved.error?.stack);return saved}
test('create entry and held increase: preview never writes; one atomic candidate contains decision/draft/receipt',async()=>{for(const shares of [0,100]){const {state,decision}=await fixture(shares),before=C.clone(state),r=preview(state,decision,'create',definition(shares?'increase':'entry',null));assert.deepEqual(state,before);const saved=await commit(r,state);assert.equal(saved.state.stocks[0].plans.length,before.stocks[0].plans.length+1);assert.equal(saved.receipt.source.decisionId,decision.decisionId);assert.deepEqual(saved.receipt.draft,r.draft);for(const k of ['shares','avgCost','managementCategory'])assert.deepEqual(saved.state.stocks[0][k],before.stocks[0][k]);for(const k of ['trades','orders','executionLog'])assert.deepEqual(saved.state[k],before[k]);assert.equal(saved.state.planDefinitionsV4.byId[saved.receipt.newPlanRef.planId].revisions.length,1)}});
test('keep records audit without any Plan changes or revisions',async()=>{const {state,decision}=await fixture(),before=C.clone(state.stocks[0].plans),saved=await commit(preview(state,decision,'no_change'),state);assert.deepEqual(saved.state.stocks[0].plans,before);assert.deepEqual(saved.state.planDefinitionsV4.byId,{});assert.deepEqual(saved.state.discussionDecisionsV4,state.discussionDecisionsV4)});
test('update has exact diff, same identity, immutable prior revision and blocked stale target',async()=>{const {state,decision}=await fixture(),id=state.stocks[0].plans[0].id,r=preview(state,decision,'update',definition());assert.ok(r.diff.some(d=>d.field==='rules.triggerPrice'));const stale=C.clone(state);stale.stocks[0].plans[0].conditions.invalidation[0].text='新规则';const rejected=await W.commitV4(r,stale,{saveCandidate:()=>assert.fail('no save')},{confirmed:true});assert.equal(rejected.writes,0);const saved=await commit(r,state);assert.equal(saved.receipt.newPlanRef.planId,id);const d=definition();d.rules.note='新增纪律';const second=await commit(preview(saved.state,decision,'update',d),saved.state);assert.equal(second.state.planDefinitionsV4.byId[id].revisions.length,2);assert.deepEqual(second.state.planDefinitionsV4.byId[id].revisions[0],saved.state.planDefinitionsV4.byId[id].revisions[0])});
for(const operation of ['cancel','complete','supersede'])test(operation+' requires user confirmation; preserves lifecycle refs',async()=>{const {state,decision}=await fixture(),id=state.stocks[0].plans[0].id,r=preview(state,decision,operation,operation==='supersede'?definition():null),before=C.clone(state);assert.equal((await W.commitV4(r,state,{})).status,'confirmation_required');assert.deepEqual(state,before);const saved=await commit(r,state);assert.equal(saved.state.stocks[0].plans[0].status,{cancel:'cancelled',complete:'completed',supersede:'replaced'}[operation]);assert.equal(saved.receipt.priorPlanRef.planId,id);if(operation==='supersede'){assert.notEqual(saved.receipt.newPlanRef.planId,id);assert.equal(saved.state.stocks[0].plans[1].legacy.discussionPlanSource.replacesPlanId,id)}});
test('quantity changes without conflict allowed; excess quantity or cross-zero rejected',async()=>{for(const shares of [80,10,0]){const {state,decision}=await fixture(),r=preview(state,decision,'update',definition('reduce',20));state.stocks[0].shares=shares;const saved=await W.commitV4(r,state,{saveCandidate:async()=>true},{confirmed:true});assert.equal(saved.status,shares===80?'completed':'failed',saved.error?.message);if(shares!==80)assert.equal(saved.writes,0)}});
test('save failure, duplicate click, mutated preview and malformed import cannot partially save',async()=>{const {state,decision}=await fixture(),r=preview(state,decision,'update',definition()),before=C.clone(state);const failed=await W.commitV4(r,state,{saveCandidate:async()=>{throw new Error('quota')}},{confirmed:true});assert.equal(failed.writes,0);assert.deepEqual(state,before);assert.equal((await W.commitV4(C.clone(r),state,{}, {confirmed:true})).status,'invalid');const unresolved=W.processV4(JSON.stringify({...r.draft,unresolvedItems:['核对']}),{state,prepared:r.prepared});assert.equal(unresolved.confirmReady,false);assert.equal(W.processV4('prefix '+JSON.stringify(r.draft),{state,prepared:r.prepared}).ok,false);const saved=await commit(r,state);assert.equal((await W.commitV4(r,saved.state,{saveCandidate:()=>assert.fail('duplicate')},{confirmed:true})).writes,0);const broken=C.clone(saved.state);delete broken.planDefinitionsV4.receipts[saved.receipt.receiptId];assert.throws(()=>V.validate(broken),/回执/)});
test('legacy AI userDecision alone cannot prepare user-owned change',()=>{const state=F.state();assert.throws(()=>W.prepareV4(state,'home-stock',{operation:'create',decisionId:state.stocks[0].discussionState.current.stateId}),/真实用户确认/)});
