'use strict';
// Synthetic loopback-only acceptance; external requests are blocked and no paid AI is called.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const output=path.resolve(process.argv[2]||'.'),url='http://127.0.0.1:8768/';
const response=(phase,transitionAssessment,summary)=>JSON.stringify({planRuntimeReview:{suggestedPhase:phase,transitionAssessment,summary,evidence:['最近结论显示结构仍在发展'],watchPoints:['继续观察确认条件是否完成'],risks:['关键结构破坏时需要降级'],confidence:'medium'}});
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||undefined}),results=[];
  async function ready(page){await page.waitForFunction(()=>document.getElementById('main')?.dataset.storageState==='ready')}
  async function noOverflow(page,label){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label+' document');assert.equal(await page.locator('.runtime-dialog').evaluate(el=>el.scrollWidth>el.clientWidth+1).catch(()=>false),false,label+' dialog')}
  async function openReview(page){await page.locator('[data-runtime-review]').first().click();await page.locator('#runtimeResultText').waitFor({state:'visible'})}
  async function review(page,payload){await page.locator('#runtimeResultText').fill(payload);await page.locator('#runtimePreviewBtn').click()}
  async function closeReview(page){await page.locator('#runtimeDoneBtn').click()}
  try{
    for(const viewport of [{width:1280,height:900},{width:390,height:844}]){
      const context=await browser.newContext({viewport}),page=await context.newPage(),errors=[],dialogs=[];
      page.on('pageerror',error=>errors.push(error.message));page.on('dialog',async dialog=>{dialogs.push(dialog.message());await dialog.dismiss()});
      await context.route('**/*',route=>new URL(route.request().url()).origin===new URL(url).origin?route.continue():route.abort());await page.goto(url);await ready(page);
      await page.evaluate(async()=>{
        const plan=PlanV2.createWatchPlan({planMode:'state_watch',name:'运行状态隔离验收',applicableConditions:['中期趋势仍可观察'],entryConditions:['进入约定结构区域时开始观察'],confirmationConditions:['结构得到进一步确认'],invalidationConditions:['关键结构被有效破坏'],reviewAction:'hold_watch',priceReferences:[],allocationConstraint:{maxPositionPct:15,targetWeightRange:null},note:'保持人工复核',validUntil:null,nextReviewDate:null},{now:'2026-09-04T00:00:00.000Z'});
        const current=DiscussionWorkbench.normalizeState({schemaVersion:DiscussionWorkbench.LEGACY_STATE_SCHEMA_VERSION,stateId:'runtime_acceptance_state_v1',symbol:'600000.SS',sourceDiscussionVersion:'runtime_acceptance_discussion_v1',stage:'结构观察',summary:'当前处于结构观察阶段，仍需等待进一步确认。',keyChanges:[],risks:['结构可能转弱'],watchPoints:['观察确认条件'],planRelation:'与观察纪律一致',confidence:'medium',technicalAsOf:'2026-09-03',confirmedAt:'2026-09-04T01:00:00.000Z',confirmedDate:'2026-09-04',technicalSnapshot:{anchorBar:{date:'2026-09-03',close:10,adjustment:'qfq',priceBasis:'close',provider:'fixture'}},references:{technical:{technicalAsOf:'2026-09-03',latestCompleteBar:'2026-09-03',anchorBar:{date:'2026-09-03',close:10,adjustment:'qfq',priceBasis:'close',provider:'fixture'}},plans:[],planReviews:[],holding:{},longTermLogic:{},modules:{}}});
        const candidate=createValidatedCandidateSnapshot({stocks:[{id:'runtime-acceptance',name:'运行状态隔离验收',code:'600000.SS',type:'holding',shares:0,avgCost:0,currentPrice:10,capPct:20,plans:[plan],discussionState:{schemaVersion:DiscussionWorkbench.STORE_SCHEMA_VERSION,current,history:[]}}],updatedAt:null,executionLog:[]});await persistCandidateSnapshot(candidate);state=candidate;globalThis.runtimePlanId=plan.id;globalThis.runtimePlanBefore=JSON.stringify(plan);globalThis.runtimePlanHash=PlanReview.planSnapshotHash(plan);globalThis.runtimeWrites=0;const persist=persistCandidateSnapshot;globalThis.runtimePersist=persist;persistCandidateSnapshot=async candidate=>{const saved=await persist(candidate);runtimeWrites++;return saved};openStockDetail('runtime-acceptance','plan');openPlanCenter();
      });
      await page.evaluate(()=>UniverseAutoAdd.flush());const universeLedgerBefore=await page.evaluate(()=>{const key=Object.keys(localStorage).find(item=>item.startsWith('universe-add-queue-'));return key?localStorage.getItem(key):null});assert(universeLedgerBefore);
      assert.match(await page.locator('[data-runtime-plan-card]').first().innerText(),/尚未建立状态/);assert.match(await page.locator('[data-runtime-plan-card]').first().innerText(),/复核状态/);await noOverflow(page,'empty state');
      await page.screenshot({path:path.join(output,`runtime-${viewport.width}-empty.png`),fullPage:true});
      await openReview(page);const prompt=await page.locator('#runtimePromptText').inputValue();assert.match(prompt,/planRuntimeReview/);assert.match(prompt,/runtime_acceptance_state_v1/);assert.match(prompt,/价格进入参考区不等于确认条件完成/);assert.doesNotMatch(prompt,/自动执行交易/);await review(page,response('forming','advance','已经进入观察窗口，结构正在形成但确认尚未完成。'));
      assert.match(await page.locator('#runtimePreview').innerText(),/首次建立运行状态/);assert.match(await page.locator('#runtimePreview').innerText(),/尚未建立/);assert.match(await page.locator('#runtimePreview').innerText(),/形成中/);assert.match(await page.locator('#runtimePreview').innerText(),/Plan Definition、持仓、配置与执行记录均保持不变/);assert.equal(await page.locator('#runtimeConfirmBtn').isEnabled(),true);assert.equal(await page.evaluate(()=>runtimeWrites),0);await noOverflow(page,'first preview');await page.screenshot({path:path.join(output,`runtime-${viewport.width}-preview.png`)});await page.locator('#runtimeConfirmBtn').click();await page.waitForFunction(()=>!document.getElementById('planRuntimeDialog').classList.contains('show'));
      const first=await page.evaluate(()=>{const plan=state.stocks[0].plans[0],runtime=PlanRuntime.runtimeFor(state,runtimePlanId);return {runtime,plan:JSON.stringify(plan),hash:PlanReview.planSnapshotHash(plan),writes:runtimeWrites,shares:state.stocks[0].shares,execution:state.executionLog.length,orders:state.orders}});assert.equal(first.runtime.runtimeRevision,1);assert.equal(first.runtime.phase,'forming');assert.equal(first.runtime.history.length,1);assert.equal(first.plan,await page.evaluate(()=>runtimePlanBefore));assert.equal(first.hash,await page.evaluate(()=>runtimePlanHash));assert.equal(first.writes,1);assert.equal(first.shares,0);assert.equal(first.execution,0);assert.equal(first.orders,undefined);
      assert.match(await page.locator('[data-runtime-plan-card]').first().innerText(),/形成中/);assert.match(await page.locator('[data-runtime-plan-card]').first().innerText(),/状态记录（1）/);await page.locator('[data-runtime-plan-card]').first().locator('summary').click();assert.match(await page.locator('[data-runtime-plan-card]').first().innerText(),/首次建立 → 形成中/);await noOverflow(page,'history');
      await openReview(page);await review(page,response('forming','hold','已经进入观察窗口，结构正在形成但确认尚未完成。'));assert.match(await page.locator('#runtimePreview').innerText(),/维持不变/);assert.equal(await page.locator('#runtimeConfirmBtn').isEnabled(),false);assert.equal(await page.evaluate(()=>runtimeWrites),1);await closeReview(page);
      // A real second tab changes unrelated canonical state after Preview; stale-tab protection still blocks the Runtime save.
      await openReview(page);await review(page,response('confirmed','advance','结构与确认条件已经得到实质满足。'));const other=await context.newPage();other.on('pageerror',error=>errors.push(error.message));await other.goto(url);await ready(other);await other.evaluate(async()=>{const candidate=structuredClone(state);candidate.stocks[0].notes='另一标签页已保存';await persistCandidateSnapshot(candidate);state=candidate});await page.waitForFunction(()=>document.getElementById('multiTabConflictBanner').textContent.includes('只读保护'));await page.locator('#runtimeConfirmBtn').dispatchEvent('click');await page.waitForFunction(()=>document.getElementById('runtimeStatus').textContent.includes('未保存'));assert.equal(await page.evaluate(()=>PlanRuntime.runtimeFor(state,runtimePlanId).runtimeRevision),1);await page.locator('#multiTabConflictBanner').getByRole('button').click();await ready(page);await other.close();await page.evaluate(()=>{globalThis.runtimePlanId=state.stocks[0].plans[0].id;globalThis.runtimeWrites=0;globalThis.runtimePersist=persistCandidateSnapshot;persistCandidateSnapshot=async candidate=>{const saved=await runtimePersist(candidate);runtimeWrites++;return saved};openStockDetail('runtime-acceptance','plan');openPlanCenter()});
      // Definition changes after Preview: the old judgment must not commit.
      await openReview(page);await review(page,response('confirmed','advance','结构与确认条件已经得到实质满足。'));await page.evaluate(async()=>{const candidate=structuredClone(state),plan=candidate.stocks[0].plans[0],definition=PlanV2.watchDefinition(plan);definition.name='定义已在另一写入中更新';candidate.stocks[0].plans[0]=PlanV2.editWatchPlan(plan,definition,{now:'2026-09-04T04:00:00.000Z'});await runtimePersist(candidate);state=candidate});await page.locator('#runtimeConfirmBtn').click();await page.waitForFunction(()=>document.getElementById('runtimeStatus').textContent.includes('未保存'));assert.match(await page.locator('#runtimeStatus').innerText(),/计划定义已经变化/);assert.equal(await page.evaluate(()=>PlanRuntime.runtimeFor(state,runtimePlanId).runtimeRevision),1);await closeReview(page);await page.evaluate(()=>{render();openStockDetail('runtime-acceptance','plan');openPlanCenter()});
      // Re-review the changed Definition, then explicitly acknowledge action_review.
      await openReview(page);await review(page,response('confirmed','advance','新定义下的确认条件已经得到实质满足。'));await page.locator('#runtimeConfirmBtn').click();await page.waitForFunction(()=>!document.getElementById('planRuntimeDialog').classList.contains('show'));
      await openReview(page);await review(page,response('action_review','advance','条件足以进入人工操作复核，但不构成执行指令。'));assert.equal(await page.locator('#runtimeConfirmBtn').innerText(),'确认进入操作复核');assert.match(await page.locator('#runtimePreview').innerText(),/不会执行交易/);await page.screenshot({path:path.join(output,`runtime-${viewport.width}-action-review.png`)});await page.locator('#runtimeConfirmBtn').click();await page.waitForFunction(()=>!document.getElementById('planRuntimeDialog').classList.contains('show'));
      const final=await page.evaluate(async()=>{await UniverseAutoAdd.flush();const runtime=PlanRuntime.runtimeFor(state,runtimePlanId),plan=state.stocks[0].plans[0],key=Object.keys(localStorage).find(item=>item.startsWith('universe-add-queue-'));return {phase:runtime.phase,revision:runtime.runtimeRevision,ack:runtime.history.at(-1).acknowledgedAt,planVersion:plan.planVersion,shares:state.stocks[0].shares,execution:state.executionLog.length,universe:UniverseAutoAdd.projection(state),universeLedger:key?localStorage.getItem(key):null,overflow:document.documentElement.scrollWidth>innerWidth}});assert.equal(final.phase,'action_review');assert.equal(final.revision,3);assert(final.ack);assert.equal(final.planVersion,2);assert.equal(final.shares,0);assert.equal(final.execution,0);assert.equal(final.overflow,false);assert.equal(final.universeLedger,universeLedgerBefore);assert.match(await page.locator('[data-runtime-plan-card]').first().innerText(),/不代表自动执行/);assert.deepEqual(errors,[]);assert.deepEqual(dialogs,[]);
      await page.evaluate(async()=>{persistCandidateSnapshot=runtimePersist;const empty=createValidatedCandidateSnapshot({stocks:[],updatedAt:null});await persistCandidateSnapshot(empty);state=empty;StorageManager.close();MultiTabProtection.close();localStorage.clear();for(const db of await indexedDB.databases())await new Promise(resolve=>{const req=indexedDB.deleteDatabase(db.name);req.onsuccess=resolve;req.onerror=resolve;req.onblocked=resolve})});await context.close();results.push({viewport,firstRevision:first.runtime.runtimeRevision,finalRevision:final.revision,finalPhase:final.phase,noChange:true,staleTabRejected:true,definitionStaleRejected:true,actionReviewAcknowledged:true,universeQueueUnchanged:true,execution:final.execution,overflow:final.overflow,errors,dialogs});console.log('PASS '+viewport.width+'x'+viewport.height);
    }
  }finally{await browser.close()}
  fs.writeFileSync(path.join(output,'plan-runtime-browser-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
})().catch(error=>{console.error(error);process.exitCode=1});
