'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),F=require('./fixtures/homepage-attention'),P=require('../src/plan-v2');
const base=process.env.V4_RAW_TEST_URL||'http://127.0.0.1:8768/',output=path.resolve(process.env.V4_RAW_TEST_OUTPUT||'test-results/v4-raw-state-fix/browser');
const oldVersion=process.argv.includes('--expect-old-failure');
function fixture(){
 const day='2026-09-08';const stock=(id,code,shares)=>F.stock({id,code,name:'隔离草稿回归 '+id,shares,avgCost:shares?40:0,managementCategory:shares?'core':'candidate',capPct:20,priceHistory:[{date:day,close:50,is_complete_bar:true,adjustment:'qfq',price_basis:'adjusted',provider:'raw-state-test'}],technicalData:{technicalDataStatus:'fresh',technicalAsOf:day,latestCompleteBar:day,price:50},technicalIndicators:{last_trade_date:day,ma20:48,ma60:46,macd:{dif:2,dea:0,histogram:4}}});
 const zero=stock('raw-zero','688997.SS',0),held=stock('raw-held','688998.SS',100);
 zero.plans=[P.createPlan({id:'entry-legacy',action:'buy',triggerPrice:50,triggerDirection:'below',conditions:{invalidation:['前提变化']},allocationConstraint:{maxPositionPct:10,targetWeightRange:null}})];
 held.plans=['cancel','complete','supersede'].map(id=>P.createPlan({id,action:'reduce',triggerPrice:50,triggerDirection:'above',quantity:10,conditions:{invalidation:['长期前提变化']}}));
 return {stocks:[zero,held],executionLog:[],trades:[],orders:[],updatedAt:null};
}
const protectedFacts=()=>state.stocks.map(s=>({id:s.id,shares:s.shares,avgCost:s.avgCost,category:s.managementCategory,trades:state.trades,orders:state.orders,executionLog:state.executionLog}));
const planState=()=>JSON.stringify({plans:state.stocks.map(s=>s.plans),v4:state.planDefinitionsV4});
async function run(browser,viewport,timing){
 const name=viewport.width+'-'+timing,dir=path.join(output,name);fs.mkdirSync(dir,{recursive:true});
 const context=await browser.newContext({viewport}),page=await context.newPage(),network=[],errors=[];let release;
 const gate=new Promise(r=>release=r);page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());
 await context.addInitScript(()=>{globalThis.rawTestRenders=[];const original=Object.getOwnPropertyDescriptor(Element.prototype,'innerHTML');Object.defineProperty(Element.prototype,'innerHTML',{...original,set(v){const stack=new Error().stack;original.set.call(this,v);if(this.id==='main')rawTestRenders.push({stack,value:document.getElementById('v4PlanInput')?.value??null})}})});
 await context.route('**/*',async route=>{const req=route.request(),url=new URL(req.url()),allowed=url.origin===new URL(base).origin&&['GET','HEAD'].includes(req.method());network.push({url:url.origin+url.pathname,method:req.method(),allowed,ai:/deepseek|openai\.com|anthropic|chat\/completions|\/api\/ai(?:\/|$)/i.test(url.href)});if(!allowed)return route.abort();if(/\/social_(posts|summary)\.json$/.test(url.pathname)){const response=await route.fetch();await gate;return route.fulfill({response}).catch(()=>{})}return route.continue()});
 await context.tracing.start({screenshots:true,snapshots:true,sources:true});
 const q=s=>page.locator(s),countReceipts=()=>page.evaluate(()=>Object.keys(PlanV4.store(state).receipts).length);
 async function finishBackground(){release();await page.waitForFunction(()=>rawTestRenders.some(e=>/app\.js.*:488:/.test(e.stack)))}
 async function decision(outcome){const n=await page.evaluate(()=>Object.keys(DiscussionV4.store(state).decisions).length);await q('#v4DecisionOutcome').selectOption(outcome);await q('[data-v4-confirm-decision]').click();await page.waitForFunction(n=>Object.keys(DiscussionV4.store(state).decisions).length===n,n+1)}
 async function prepare(operation='create',target=''){
  await q('#workspace-tab-plan').click();await q('#v4PlanTarget').selectOption(target);await q('#v4PlanOperation').selectOption(operation);await q('[data-v4-prepare-plan]').click();assert.equal(await q('#v4PlanInput').inputValue(),'');
  const example=JSON.parse((await q('#v4PlanRequest').inputValue()).split('输出结构：\n')[1]);
  const definition=await page.evaluate(()=>{const stock=state.stocks.find(s=>s.id===detailStockId),intent=stock.shares?'increase':'entry';return PlanV4.legacyDefinition(PlanV2.createPlan({action:stock.shares?'add':'buy',triggerPrice:45,triggerDirection:'below',conditions:{technical:['重新稳定后人工复核'],invalidation:['长期前提变化']},allocationConstraint:{maxPositionPct:10,targetWeightRange:null},note:'长期关注规则'}),intent)});
  return JSON.stringify({...example,definition:['create','update','supersede'].includes(operation)?definition:null,reason:'用户确认的长期条件 A',risks:['后续证据变化需复核'],unresolvedItems:[]});
 }
 async function preview(raw){const before=await page.evaluate(planState);await q('#v4PlanInput').fill(raw);await q('[data-v4-preview-plan]').click();assert.equal(await q('[data-v4-diff]').count(),1,await q('#v4PlanStatus').innerText());assert.equal(await q('[data-v4-confirm-plan]').isEnabled(),true);assert.equal(await page.evaluate(planState),before)}
 async function confirm(){const n=await countReceipts();await q('[data-v4-confirm-plan]').click();await page.waitForFunction(n=>Object.keys(PlanV4.store(state).receipts).length===n,n+1);return page.evaluate(()=>Object.values(PlanV4.store(state).receipts).at(-1))}
 try{
  await page.goto(base,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.getElementById('main')?.dataset.storageState==='ready');await page.waitForFunction(()=>rawTestRenders.some(e=>/app\.js.*:485:/.test(e.stack)));
  await page.evaluate(async sample=>{if(state.stocks.length)throw Error('Requires empty isolated profile');if(sample.stocks.some(s=>(MARKET_DATA_BRIDGE?.stocks||[]).some(m=>m.symbol===s.code)))throw Error('Synthetic fixture matches market bridge');const candidate=createValidatedCandidateSnapshot(sample);await persistCandidateSnapshot(candidate);state=candidate;currentTab='dashboard';detailStockId=null;render()},fixture());
  const facts=await page.evaluate(protectedFacts);if(timing==='before')await finishBackground();
  await q('[data-home-attention-action="discussion"][data-stock-id="raw-zero"]').click();assert.match(await q('[data-v4-decision-panel]').innerText(),/从今日关注进入/);await decision('consider_entry');const raw=await prepare(),before=await page.evaluate(planState);
  if(timing==='during'){
   const partial=raw.slice(0,Math.floor(raw.length/2));await q('#v4PlanInput').fill(partial);await finishBackground();assert.equal(await q('#v4PlanInput').inputValue(),partial);await q('#v4PlanInput').fill(raw);
  }else {await q('#v4PlanInput').fill(raw);assert.equal(await q('#v4PlanInput').inputValue(),raw);if(timing==='after')await finishBackground()}
  if(oldVersion){assert.equal(await q('#v4PlanInput').inputValue(),'');await q('[data-v4-preview-plan]').click();assert.match(await q('#v4PlanStatus').innerText(),/复制的 JSON 内容发生格式异常/);assert.equal(await q('[data-v4-diff]').count(),0);assert.equal(await page.evaluate(planState),before);return {name,oldRaceReproduced:true}}
  assert.equal(await q('#v4PlanInput').count(),1);assert.equal(await q('#v4PlanInput').inputValue(),raw);await q('[data-v4-preview-plan]').click();assert.equal(await q('[data-v4-diff]').count(),1,await q('#v4PlanStatus').innerText());assert.equal(await page.evaluate(planState),before);
  const stale=await q('[data-v4-confirm-plan]').elementHandle(),rawB=JSON.stringify({...JSON.parse(raw),reason:'用户编辑后的长期条件 B'}),input=await q('#v4PlanInput').elementHandle();
  await q('#v4PlanInput').fill(rawB);assert.equal(await input.evaluate(n=>n===document.getElementById('v4PlanInput')),true);assert.equal(await q('[data-v4-diff]').count(),0);assert.equal(await q('[data-v4-confirm-plan]').count(),0);
  // Reattach the old control so its click reaches the real handler: it must reject.
  await stale.evaluate(n=>{document.getElementById('v4PlanDraft').append(n);n.click();n.remove()});assert.equal(await page.evaluate(planState),before);
  if(timing==='after')await page.setViewportSize(viewport.width===1280?{width:390,height:844}:{width:1280,height:900});
  await page.evaluate(()=>renderStockDetail());assert.equal(await q('#v4PlanInput').inputValue(),rawB);if(timing==='after')await page.setViewportSize(viewport);await q('[data-v4-preview-plan]').click();const entry=await confirm();assert.equal(entry.draft.reason,'用户编辑后的长期条件 B');assert.equal(entry.draft.definition.actionIntent,'entry');
  if(timing==='after'){
   // Every supported operation uses the same input; explicit rerenders also cover
   // supporting cards, unrelated section renders and responsive page reconstruction.
   await page.evaluate(()=>openStockDetail('raw-held','ai'));await decision('review_plan_change');let created;
   for(const operation of ['create','update','no_change','cancel','supersede','complete']){
    if(operation==='no_change'){await q('#workspace-tab-ai').click();await decision('keep_current_plan')}
    if(operation==='cancel'){await q('#workspace-tab-ai').click();await decision('review_plan_change')}
    const target=operation==='create'?'':['update','no_change'].includes(operation)?created:operation;
    let candidate=await prepare(operation,target);if(operation==='update'){const v=JSON.parse(candidate);v.definition.rules.triggerPrice=42;candidate=JSON.stringify(v)}
    const oldPlans=await page.evaluate(()=>JSON.stringify(state.stocks.map(s=>s.plans)));await q('#v4PlanInput').fill(candidate);await page.evaluate(()=>render());assert.equal(await q('#v4PlanInput').inputValue(),candidate);assert.equal(await q('#v4PlanTarget').inputValue(),target);assert.equal(await q('#v4PlanOperation').inputValue(),operation);await q('[data-v4-preview-plan]').click();assert.equal(await q('[data-v4-diff]').count(),1,await q('#v4PlanStatus').innerText());const receipt=await confirm();if(operation==='create')created=receipt.newPlanRef.planId;if(operation==='update'){assert.equal(receipt.newPlanRef.planId,created);assert.equal(await page.evaluate(id=>PlanV4.store(state).byId[id].revisions.length,created),2)}if(operation==='no_change')assert.equal(await page.evaluate(()=>JSON.stringify(state.stocks.map(s=>s.plans))),oldPlans);
   }
   await prepare('create');for(const bad of ['', '{broken']){const b=await page.evaluate(planState);await q('#v4PlanInput').fill(bad);await page.evaluate(()=>renderStockDetail());await q('[data-v4-preview-plan]').click();assert.equal(await q('[data-v4-confirm-plan]').count(),0);assert.match(await q('#v4PlanStatus').innerText(),/JSON/);assert.equal(await page.evaluate(planState),b)}
   const a=await prepare('update',created);await preview(a);const oldInput=await q('#v4PlanInput').elementHandle(),otherTarget=await page.evaluate(id=>state.stocks.find(s=>s.id==='raw-held').plans.find(p=>p.status==='active'&&p.id!==id).id,created);await q('#v4PlanTarget').selectOption(otherTarget);assert.equal(await q('#v4PlanInput').count(),0);await q('#v4PlanTarget').selectOption(created);await q('[data-v4-prepare-plan]').click();assert.equal(await q('#v4PlanInput').inputValue(),'');await oldInput.evaluate(n=>{n.value='stale';n.dispatchEvent(new Event('input',{bubbles:true}))});assert.equal(await q('#v4PlanInput').inputValue(),'');
   await q('#v4PlanOperation').selectOption('no_change');assert.equal(await q('#v4PlanInput').count(),0);await q('[data-v4-prepare-plan]').click();assert.equal(await q('#v4PlanInput').inputValue(),'');
   const remembered=await prepare();await q('#v4PlanInput').fill(remembered);await page.evaluate(()=>openStockDetail('raw-zero','plan'));assert.equal(await q('#v4PlanInput').count(),0);await page.evaluate(()=>openStockDetail('raw-held','plan'));assert.equal(await q('#v4PlanInput').inputValue(),remembered);await q('[data-v4-prepare-plan]').click();assert.equal(await q('#v4PlanInput').inputValue(),'');await q('#v4PlanInput').fill(remembered);await q('#workspace-tab-ai').click();await decision('review_plan_change');await q('#workspace-tab-plan').click();assert.equal(await q('#v4PlanInput').count(),0);
  }
  assert.deepEqual(await page.evaluate(protectedFacts),facts);const durable=await page.evaluate(()=>JSON.stringify({p:state.planDefinitionsV4,d:state.discussionDecisionsV4}));
  release();await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.getElementById('main')?.dataset.storageState==='ready');assert.equal(await page.evaluate(()=>JSON.stringify({p:state.planDefinitionsV4,d:state.discussionDecisionsV4})),durable);assert.deepEqual(await page.evaluate(protectedFacts),facts);await page.evaluate(()=>openStockDetail('raw-zero','plan'));assert.equal(await q('#v4PlanInput').count(),0,'unconfirmed draft is not long-term storage');
  assert.deepEqual(errors,[]);assert.equal(network.filter(r=>r.ai).length,0);assert.equal(network.filter(r=>r.allowed&&!['GET','HEAD'].includes(r.method)).length,0);
  await page.screenshot({path:path.join(dir,'complete.png'),fullPage:true});return {name,viewport,timing,rawPreserved:true,previewEditInvalidation:true,staleConfirmWrites:0,confirmedEntry:true,allSixOperations:timing==='after',sessionIsolation:timing==='after',strictRejections:timing==='after',refreshPersistence:true,protectedFactsUnchanged:true,automaticAiAttempts:0};
 }catch(e){await page.screenshot({path:path.join(dir,'failure.png'),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(dir,'failure.html'),await page.content());fs.writeFileSync(path.join(dir,'failure.json'),JSON.stringify({error:e.stack,scene:await page.evaluate(()=>({state,raw:document.getElementById('v4PlanInput')?.value,status:document.getElementById('v4PlanStatus')?.textContent})),network,errors},null,2));throw e}
 finally{fs.writeFileSync(path.join(dir,'network.json'),JSON.stringify(network,null,2));await context.tracing.stop({path:path.join(dir,'trace.zip')});release();await context.close()}
}
(async()=>{fs.mkdirSync(output,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||undefined}),results=[];try{for(const viewport of [{width:1280,height:900},{width:390,height:844},{width:360,height:800}])for(const timing of oldVersion?['after']:['before','after','during','none']){console.log('RUN',viewport.width,timing);results.push(await run(browser,viewport,timing));fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(results,null,2));console.log('PASS',viewport.width,timing)}}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
