'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const D=require('../src/discussion-v4'),V=require('../src/plan-v4'),W=require('../src/discussion-plan-workflow'),P=require('../src/plan-v2'),C=require('../src/plan-context-contract'),B=require('../src/discussion-workbench'),F=require('./fixtures/homepage-attention');
const decode=s=>s.replace(/&(amp|lt|gt|quot|#39);/g,(_,k)=>({amp:'&',lt:'<',gt:'>',quot:'"','#39':"'"}[k]));
// Minimal DOM surface for the actual delegated UI handlers. Browser acceptance
// separately covers native input events, node replacement and background timing.
function dom(){
 const listeners={};let root;
 class Element{
  constructor(tag='div',attrs={}){this.tagName=tag.toUpperCase();this.attrs=attrs;this.children=[];this.parentNode=null;this._value=undefined;this.text=''}
  get id(){return this.attrs.id||''}get dataset(){return Object.fromEntries(Object.entries(this.attrs).filter(([k])=>k.startsWith('data-')).map(([k,v])=>[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase()),v]))}
  get isConnected(){return this===root||!!this.parentNode?.isConnected}get disabled(){return 'disabled' in this.attrs}set disabled(v){if(v)this.attrs.disabled='';else delete this.attrs.disabled}
  get textContent(){return this.text+this.children.map(n=>n.textContent).join('')}set textContent(v){this.children.forEach(n=>n.parentNode=null);this.children=[];this.text=String(v)}
  get value(){return this._value??(this.tagName==='SELECT'?(this.querySelector('option[selected]')||this.querySelector('option'))?.attrs.value||'':this.tagName==='TEXTAREA'?this.textContent:this.attrs.value||'')}set value(v){this._value=String(v)}
  hasAttribute(k){return k in this.attrs}getAttribute(k){return this.attrs[k]??null}
  matches(selector){return selector.split(',').some(s=>{s=s.trim();if(s.startsWith('#'))return this.id===s.slice(1);const m=s.match(/^(\w+)?(?:\[([^=\]]+)(?:="([^"]*)")?\])?$/);return !!m&&(!m[1]||this.tagName===m[1].toUpperCase())&&(!m[2]||(m[2] in this.attrs&&(m[3]===undefined||this.attrs[m[2]]===m[3])))})}
  closest(s){return this.matches(s)?this:this.parentNode?.closest(s)||null}
  querySelectorAll(s){return this.children.flatMap(n=>[...(n.matches(s)?[n]:[]),...n.querySelectorAll(s)])}querySelector(s){return this.querySelectorAll(s)[0]||null}
  remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(n=>n!==this);this.parentNode=null}
  set innerHTML(html){this.textContent='';const stack=[this];for(const token of html.match(/<[^>]*>|[^<]+/g)||[]){if(token.startsWith('</')){stack.pop();continue}if(token.startsWith('<')){const m=token.match(/^<(\w+)/);if(!m)continue;const attrs={};for(const a of token.slice(m[0].length).matchAll(/([\w-]+)(?:="([^"]*)")?/g))attrs[a[1]]=decode(a[2]||'');const n=new Element(m[1],attrs),parent=stack.at(-1);parent.children.push(n);n.parentNode=parent;if(!['BR','INPUT','HR'].includes(n.tagName))stack.push(n)}else stack.at(-1).text+=decode(token)}}
 }
 root=new Element();return {root,Element,addEventListener:(type,fn)=>(listeners[type]??=[]).push(fn),getElementById:id=>root.querySelector('#'+id),querySelector:s=>root.querySelector(s),querySelectorAll:s=>root.querySelectorAll(s),async fire(type,target){for(const fn of listeners[type]||[])await fn({target})}};
}
async function harness(){
 const document=dom();let saves=0;const state=F.state({plans:[P.createPlan({id:'target-a',action:'reduce',triggerPrice:50,triggerDirection:'above',conditions:{invalidation:['条件变化']}}),P.createPlan({id:'target-b',action:'reduce',triggerPrice:55,triggerDirection:'above',conditions:{invalidation:['条件变化']}})]});
 state.stocks.push(F.stock({id:'other-stock',code:'688997.SS',plans:[]}));
 const ctx={document,state,detailStockId:'home-stock',DiscussionV4:D,PlanV4:V,DiscussionPlanWorkflow:W,PlanContextContract:C,DiscussionWorkbench:B,createValidatedCandidateSnapshot:C.clone,persistCandidateSnapshot:async()=>{saves++},alert:assert.fail};
 ctx.renderStockDetail=()=>{document.root.innerHTML=ctx.PlanDiscussionV4UI.planPanel(ctx.state.stocks.find(s=>s.id===ctx.detailStockId))};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../src/plan-discussion-v4-ui.js'),'utf8'),ctx);
 async function decision(id=ctx.detailStockId){const prepared=D.prepareDecision(ctx.state,id,{outcome:'review_plan_change'}),saved=await D.commitDecision(ctx.state,prepared,{saveCandidate:async()=>true},{confirmed:true,now:new Date(Date.now()+1000*Object.keys(D.store(ctx.state).decisions).length).toISOString()});ctx.state=saved.state;ctx.renderStockDetail()}
 await decision();const q=s=>document.querySelector(s),click=s=>document.fire('click',typeof s==='string'?q(s):s);
 async function prepare(operation='create',target=''){q('#v4PlanOperation').value=operation;q('#v4PlanTarget').value=target;await click('[data-v4-prepare-plan]');assert.ok(q('#v4PlanInput'));return payload()}
 function payload(note='raw A'){const example=JSON.parse(q('#v4PlanRequest').value.split('输出结构：\n')[1]);return JSON.stringify({...example,definition:['create','update','supersede'].includes(example.operation)?V.legacyDefinition(P.createPlan({action:'reduce',triggerPrice:40,triggerDirection:'below',quantity:10,conditions:{invalidation:['长期前提变化']},note}),'reduce'):null,reason:note})}
 async function input(raw){const n=q('#v4PlanInput');n.value=raw;await document.fire('input',n);return n}
 return {ctx,document,q,click,prepare,payload,input,decision,saves:()=>saves,render:ctx.renderStockDetail};
}
test('input synchronizes the existing draft before any rerender, preserving all characters',async()=>{const h=await harness(),raw=await h.prepare();const original=await h.input(raw);for(let i=0;i<3;i++){h.render();assert.notEqual(h.q('#v4PlanInput'),original);assert.equal(h.q('#v4PlanInput').value,raw)}assert.equal(h.saves(),0)});
test('Preview uses latest input; editing removes old eligibility and stale Confirm writes nothing',async()=>{const h=await harness();await h.prepare();await h.input(h.payload('A'));await h.click('[data-v4-preview-plan]');const stale=h.q('[data-v4-confirm-plan]');assert.ok(stale);const rawB=h.payload('B'),node=await h.input(rawB);assert.equal(h.q('#v4PlanInput'),node,'editing must not replace the active textarea');assert.equal(h.q('[data-v4-diff]'),null);assert.equal(h.q('[data-v4-confirm-plan]'),null);const before=JSON.stringify(h.ctx.state);await h.click(stale);assert.equal(JSON.stringify(h.ctx.state),before);assert.equal(h.saves(),0);h.render();assert.equal(h.q('#v4PlanInput').value,rawB);await h.click('[data-v4-preview-plan]');await h.click('[data-v4-confirm-plan]');assert.equal(h.saves(),1);assert.equal(Object.values(V.store(h.ctx.state).receipts).at(-1).draft.reason,'B')});
for(const operation of ['create','update','no_change','cancel','supersede','complete'])test(operation+' shares raw preservation and strict Preview/Confirm',async()=>{const h=await harness(),raw=await h.prepare(operation,operation==='create'?'':'target-a');await h.input(raw);h.render();assert.equal(h.q('#v4PlanInput').value,raw);assert.equal(h.q('#v4PlanOperation').value,operation);assert.equal(h.q('#v4PlanTarget').value,operation==='create'?'':'target-a');await h.click('[data-v4-preview-plan]');assert.ok(h.q('[data-v4-confirm-plan]'));assert.equal(h.saves(),0);const plans=JSON.stringify(h.ctx.state.stocks[0].plans);await h.click('[data-v4-confirm-plan]');assert.equal(h.saves(),1);if(operation==='no_change')assert.equal(JSON.stringify(h.ctx.state.stocks[0].plans),plans)});
for(const raw of ['', '{broken'])test('invalid raw remains rejected with no Plan writes: '+JSON.stringify(raw),async()=>{const h=await harness();await h.prepare();await h.input(raw);h.render();const before=JSON.stringify(h.ctx.state);await h.click('[data-v4-preview-plan]');assert.equal(h.q('[data-v4-confirm-plan]'),null);assert.match(h.q('#v4PlanStatus').textContent,/JSON/);assert.equal(JSON.stringify(h.ctx.state),before);assert.equal(h.saves(),0)});
for(const control of ['#v4PlanOperation','#v4PlanTarget'])test(control+' change discards the old task and rejects stale buttons',async()=>{const h=await harness();await h.prepare('update','target-a');await h.input(h.payload());await h.click('[data-v4-preview-plan]');const oldInput=h.q('#v4PlanInput'),oldConfirm=h.q('[data-v4-confirm-plan]');h.q(control).value=control.endsWith('Operation')?'cancel':'target-b';await h.document.fire('change',h.q(control));assert.equal(h.q('#v4PlanInput'),null);await h.click(oldConfirm);assert.equal(h.saves(),0);await h.click('[data-v4-prepare-plan]');assert.equal(h.q('#v4PlanInput').value,'');oldInput.value='wrong task';await h.document.fire('input',oldInput);h.render();assert.equal(h.q('#v4PlanInput').value,'')});
test('stock, new session and new Discussion/decision isolate raw and Preview',async()=>{const h=await harness(),a=await h.prepare();const stale=await h.input(a);h.ctx.detailStockId='other-stock';await h.decision();assert.equal(h.q('#v4PlanInput'),null);await h.prepare();await h.input(h.payload('other'));h.ctx.detailStockId='home-stock';h.render();assert.equal(h.q('#v4PlanInput').value,a,'same legal A session can resume');await h.prepare();assert.equal(h.q('#v4PlanInput').value,'');stale.value='old session event';await h.document.fire('input',stale);h.render();assert.equal(h.q('#v4PlanInput').value,'');await h.input(h.payload());await h.decision();assert.equal(h.q('#v4PlanInput'),null,'new confirmed Discussion must require preparing a new task')});
