'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const C=require('../src/plan-context-contract'),P=require('../src/plan-v2'),R=require('../src/plan-review');
const watch=()=>P.createWatchPlan(require('./fixtures/state-watch-definitions.json')[0]);
const price=()=>P.createPlan({action:'sell',triggerPrice:10,triggerDirection:'above',quantity:100,conditions:{technical:['规则']}});
test('SHA-256 matches Node across unicode and block boundaries',()=>{for(const text of ['','abc','长期定义','x'.repeat(55),'x'.repeat(56),'x'.repeat(1000)])assert.equal(C.sha256(text),crypto.createHash('sha256').update(text).digest('hex'))});
test('every watch definition field participates; observations and identity do not',()=>{const p=watch(),hash=C.definitionRef(p).definitionHash;for(const patch of [{name:'不同主题'},{entryConditions:['另一规则']},{confirmationConditions:['另一确认']},{invalidationConditions:['另一失效']},{applicableConditions:['另一背景']},{reviewAction:'hold_watch'},{priceReferences:[]},{note:'另一备注'},{nextReviewDate:'2030-01-01'},{validUntil:'2030-02-01'},{allocationConstraint:{maxPositionPct:12,targetWeightRange:null}}])assert.notEqual(C.definitionRef({...p,...patch}).definitionHash,hash,JSON.stringify(patch));assert.equal(C.definitionRef({...p,id:'other',planVersion:9,updatedAt:new Date().toISOString()}).definitionHash,hash)});
test('price observations and condition confirmation caches do not change definition',()=>{const p=price(),hash=C.definitionRef(p).definitionHash;assert.equal(C.definitionRef(P.observePriceTrigger(p,11)).definitionHash,hash);assert.equal(C.definitionRef({...p,fullConditionStatus:'confirmed',conditions:{...p.conditions,technical:[{text:'规则',status:'confirmed'}]}}).definitionHash,hash);for(const patch of [{triggerPrice:12},{quantity:200},{action:'buy'},{triggerDirection:'below'},{conditions:{technical:['新规则']}}])assert.notEqual(C.definitionRef({...p,...patch}).definitionHash,hash)});
test('legacy hash is preserved and matching old assessments never silently bind',()=>{for(const p of [price(),watch()]){const state={stocks:[{id:'s',plans:[p]}]},old={planId:p.id,planVersion:p.planVersion,planSnapshotHash:R.planSnapshotHash(p)},before=JSON.stringify({state,old});const result=C.binding(state,null,old,R);assert.equal(result.bindingStatus,'legacy_unknown');assert.equal(result.legacyCompatibility.matches,true);assert.equal(JSON.stringify({state,old}),before)}});
test('exact identity and replacement stay separate and duplicate IDs fail closed',()=>{const p=price(),ref=C.definitionRef(p),q=price(),state={stocks:[{id:'s',plans:[P.terminatePlan(p,'replaced'),q]}]};assert.equal(C.binding(state,ref).planId,p.id);assert.equal(C.binding(state,{...ref,planId:'missing'}).bindingStatus,'missing');assert.equal(C.binding(state,C.definitionRef(q)).bindingStatus,'current');state.stocks[0].plans.push({...q});assert.equal(C.binding(state,C.definitionRef(q)).bindingStatus,'missing')});
test('pure context reads have no mutation and exact definition changes derive changed',()=>{const p=price(),state={stocks:[{id:'s',code:'600000.SS',shares:100,plans:[p],priceHistory:[]}]},ref=C.definitionRef(p),before=JSON.stringify(state);const context=C.context(state,'s');assert.equal(context.plans[0].definitionRef.definitionHash,ref.definitionHash);assert.equal(JSON.stringify(state),before);p.triggerPrice=12;assert.equal(C.binding(state,ref).bindingStatus,'changed')});

test('state-watch external Runtime observations leave definition hash unchanged',()=>{const p=watch(),state={stocks:[{id:'s',code:'600000.SS',shares:100,plans:[p]}],planRuntimeStates:{byPlanId:{}}},before=C.context(state,'s').plans[0].definitionRef;state.planRuntimeStates.byPlanId[p.id]={phase:'confirmed',runtimeRevision:5};assert.deepEqual(C.context(state,'s').plans[0].definitionRef,before)});
