'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),F=require('./fixtures/homepage-attention');
const output=path.resolve('test-results/v4/core-loop-browser'),url='http://127.0.0.1:8768/';
(async()=>{fs.mkdirSync(output,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||undefined}),results=[];
try{for(const viewport of [{width:1280,height:900},{width:390,height:844},{width:360,height:800}]){
 const context=await browser.newContext({viewport}),page=await context.newPage(),errors=[],ai=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());
 await context.route('**/*',route=>{if(/deepseek|\/ai\//i.test(route.request().url()))ai.push(route.request().url());return new URL(route.request().url()).origin===new URL(url).origin?route.continue():route.abort()});
 await page.goto(url);await page.waitForFunction(()=>document.getElementById('main')?.dataset.storageState==='ready');
 await page.evaluate(async fixture=>{state=createValidatedCandidateSnapshot(fixture);await persistCandidateSnapshot(state);openStockDetail(state.stocks[0].id);setDetailWorkspace('ai');renderStockDetail()},F.state());
 assert.equal(await page.locator('[data-v4-decision-panel]').count(),1);assert.equal(await page.evaluate(()=>Object.keys(DiscussionV4.store(state).decisions).length),0);
 await page.locator('#v4DecisionOutcome').selectOption('review_plan_change');await page.locator('#v4DecisionNote').fill('浏览器验收：我愿意复核长期计划。');await page.locator('[data-v4-confirm-decision]').click();
 await page.waitForFunction(()=>Object.keys(DiscussionV4.store(state).decisions).length===1);const originalFacts=await page.evaluate(()=>({shares:state.stocks[0].shares,avgCost:state.stocks[0].avgCost,category:state.stocks[0].managementCategory,trades:state.trades,orders:state.orders,executionLog:state.executionLog}));
 await page.locator('#workspace-tab-plan').click();await page.locator('#v4PlanOperation').selectOption('create');await page.locator('[data-v4-prepare-plan]').click();
 async function candidate(intent='increase',change={}){const prompt=await page.locator('#v4PlanRequest').inputValue(),example=JSON.parse(prompt.split('输出结构：\n')[1]);const def=await page.evaluate(intent=>PlanV4.legacyDefinition(PlanV2.createPlan({action:intent==='increase'?'add':'reduce',triggerPrice:40,triggerDirection:'below',quantity:intent==='increase'?null:20,conditions:{invalidation:['基本前提变化']},allocationConstraint:{maxPositionPct:10,targetWeightRange:null},note:'长期关注条件'}),intent),intent);return {...example,definition:def,...change}}
 await page.locator('#v4PlanInput').fill(JSON.stringify(await candidate()));await page.locator('[data-v4-preview-plan]').click();assert.equal(await page.locator('[data-v4-diff]').count(),1);assert.equal(await page.evaluate(()=>state.stocks[0].plans.length),0);
 // Inject a persistence failure through the actual UI. No global state adoption is allowed.
 await page.evaluate(()=>{window.v4OriginalPersist=persistCandidateSnapshot;persistCandidateSnapshot=async()=>{throw new Error('验收模拟容量不足')}});const beforeFailure=await page.evaluate(()=>JSON.stringify(state));await page.locator('[data-v4-confirm-plan]').click();await page.waitForFunction(()=>document.getElementById('v4PlanStatus')?.textContent.includes('容量不足'));assert.equal(await page.evaluate(()=>JSON.stringify(state)),beforeFailure);await page.evaluate(()=>{persistCandidateSnapshot=window.v4OriginalPersist});
 await page.locator('[data-v4-confirm-plan]').click();await page.waitForFunction(()=>state.stocks[0].plans.length===1);const planId=await page.evaluate(()=>state.stocks[0].plans[0].id);
 assert.equal(await page.evaluate(()=>Object.keys(PlanV4.store(state).receipts).length),1);assert.equal(await page.locator('[data-v4-plan]').count(),1);
 await page.locator('[data-v4-discuss-plan]').click();assert.equal(await page.locator('#workspace-tab-ai').getAttribute('aria-selected'),'true');assert.match(await page.locator('[data-v4-decision-panel]').innerText(),/复核此项长期计划/);
 await page.locator('[data-detail-action="start-stock-discussion"]').click();assert.match(await page.locator('#discussionPreparedPrompt').inputValue(),/进入时原因/);await page.locator('#discussionPromptCloseBtn').click();
 // Another confirmation records the exact Plan source, while no Plan mutation occurs.
 await page.locator('#v4DecisionOutcome').selectOption('review_plan_change');await page.locator('[data-v4-confirm-decision]').click();await page.waitForFunction(()=>Object.keys(DiscussionV4.store(state).decisions).length===2);
 await page.locator('#workspace-tab-plan').click();await page.locator('#v4PlanTarget').selectOption(planId);await page.locator('#v4PlanOperation').selectOption('update');await page.locator('[data-v4-prepare-plan]').click();const update=await candidate();update.definition.rules.triggerPrice=42;await page.locator('#v4PlanInput').fill(JSON.stringify(update));await page.locator('[data-v4-preview-plan]').click();assert.match(await page.locator('[data-v4-diff]').innerText(),/关注价格[\s\S]*40[\s\S]*42/);await page.locator('[data-v4-confirm-plan]').click();await page.waitForFunction(id=>PlanV4.store(state).byId[id].revisions.length===2,planId);
 await page.locator('[data-v4-audit]').click();assert.equal(await page.locator('#workspace-tab-history').getAttribute('aria-selected'),'true');assert.match(await page.locator('[data-v4-audit-panel]').innerText(),/当时 AI 判断|进入原因/);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(output,`audit-${viewport.width}.png`),fullPage:true});
 const exported=await page.evaluate(()=>JSON.stringify(state));assert.equal(await page.evaluate(raw=>{const roundtrip=createValidatedCandidateSnapshot(JSON.parse(raw),{touchUpdatedAt:false});return JSON.stringify(roundtrip.planDefinitionsV4)===JSON.stringify(state.planDefinitionsV4)&&JSON.stringify(roundtrip.discussionDecisionsV4)===JSON.stringify(state.discussionDecisionsV4)},exported),true);
 assert.equal(await page.evaluate(()=>{const bad=structuredClone(state);bad.planDefinitionsV4.byId[state.stocks[0].plans[0].id].revisions[0].definitionHash='bad';try{createValidatedCandidateSnapshot(bad);return false}catch(_){return true}}),true);
 await page.reload();await page.waitForFunction(()=>document.getElementById('main')?.dataset.storageState==='ready');assert.equal(await page.evaluate(()=>Object.keys(PlanV4.store(state).receipts).length),2);assert.equal(await page.evaluate(id=>PlanV4.store(state).byId[id].revisions.length,planId),2);
 assert.equal(await page.evaluate(()=>StorageManager.getActiveSource()),'localStorage');
 await page.evaluate(async()=>{await StorageManager.runShadowMigration();await StorageManager.executeActiveCutover()});
 await page.reload();await page.waitForFunction(()=>document.getElementById('main')?.dataset.storageState==='ready');assert.equal(await page.evaluate(()=>StorageManager.getActiveSource()),'indexeddb');assert.equal(await page.evaluate(id=>PlanV4.store(state).byId[id].revisions.length,planId),2);
 await page.evaluate(()=>{openStockDetail(state.stocks[0].id,'ai')});await page.locator('#v4DecisionOutcome').selectOption('keep_current_plan');await page.locator('[data-v4-confirm-decision]').click();await page.waitForFunction(()=>Object.keys(DiscussionV4.store(state).decisions).length===3);await page.reload();await page.waitForFunction(()=>document.getElementById('main')?.dataset.storageState==='ready');assert.equal(await page.evaluate(()=>Object.keys(DiscussionV4.store(state).decisions).length),3);
 // A real stale tab cannot save a decision over another tab's committed state.
 await page.evaluate(()=>{openStockDetail(state.stocks[0].id,'ai')});const other=await context.newPage();await other.goto(url);await other.waitForFunction(()=>document.getElementById('main')?.dataset.storageState==='ready');await other.evaluate(async()=>{const next=createValidatedCandidateSnapshot(state);next.stocks[0].notes='另一个标签页的记录';await persistCandidateSnapshot(next);state=next});await page.waitForFunction(()=>document.getElementById('multiTabConflictBanner')?.textContent.includes('只读保护'));const oldTabState=await page.evaluate(()=>JSON.stringify(state));await page.locator('[data-v4-confirm-decision]').dispatchEvent('click');await page.waitForFunction(()=>!!document.getElementById('v4DecisionStatus')?.textContent);assert.equal(await page.evaluate(()=>JSON.stringify(state)),oldTabState);await other.close();
 assert.deepEqual(await page.evaluate(()=>({shares:state.stocks[0].shares,avgCost:state.stocks[0].avgCost,category:state.stocks[0].managementCategory,trades:state.trades,orders:state.orders,executionLog:state.executionLog})),originalFacts);
 assert.deepEqual(errors,[]);assert.deepEqual(ai,[]);results.push({viewport,decision:true,create:true,updateSameId:true,atomicFailure:true,source:true,audit:true,roundtrip:true,reload:true,localStorage:true,indexedDB:true,staleTab:true,noOverflow:true,noAutoAI:true,errors});await context.close();
}}finally{await browser.close()}fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results))})().catch(e=>{console.error(e);process.exitCode=1});
