'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const Plan=require('../src/plan-v2'),Flow=require('../src/state-watch-workflow'),Review=require('../src/plan-review'),Portfolio=require('../src/portfolio-review-context'),Discussion=require('../src/discussion-plan-workflow'),Workbench=require('../src/discussion-workbench');
const fixtures=require('./fixtures/state-watch-definitions.json'),clone=Plan.clone;
const now='2026-09-03T06:00:00.000Z',later='2026-09-03T07:00:00.000Z';
const definition=()=>Plan.validateWatchDefinition(fixtures[0]).definition;
const stock=plans=>({id:'watch-test',name:'隔离观察验收',code:'600000.SS',type:'holding',shares:0,avgCost:0,currentPrice:null,capPct:20,plans});
const legacy=()=>Plan.createPlan({action:'buy',triggerPrice:25,triggerDirection:'below',quantity:100,note:'legacy',allocationConstraint:{maxPositionPct:10}},{now});
function setup(existing=false){const plan=existing?Plan.createWatchPlan(definition(),{now}):null,s=stock(plan?[legacy(),plan]:[legacy()]),state={stocks:[s],executionLog:[],discussionState:{unchanged:true},updatedAt:1},prepared=Flow.prepare(s,plan?{targetPlanId:plan.id}:{});return {plan,s,state,prepared,draft:Flow.envelope(prepared,plan?'update':'create',definition(),'合成测试的明确纪律变更')}}
const process=(fixture,draft=fixture.draft)=>Flow.process(JSON.stringify(draft),{stock:fixture.s,prepared:fixture.prepared});
async function commit(fixture,result,options={}){let writes=0,adopted=null;const saved=await Flow.commit(result,fixture.state,{saveCandidate:async candidate=>{writes++;return {state:candidate}},adoptCandidate:candidate=>{adopted=candidate}},{confirmed:true,now:later,...options});return {saved,writes,adopted}}

for(const fixture of fixtures)test('valid synthetic Definition: '+fixture.name,()=>{const plan=Plan.createPlan(fixture,{now});assert.equal(Plan.validatePlan(plan).ok,true);assert.equal(plan.schemaVersion,'plan.v2');assert.equal(plan.planVersion,1);assert.match(plan.id,/^plan_/);assert.equal(plan.name,fixture.name);for(const key of ['action','triggerPrice','triggerDirection','quantity'])assert.equal(plan[key],null);assert.equal(plan.priceTriggerStatus,'unavailable');assert.equal(plan.fullConditionStatus,'unproven');assert.deepEqual(plan.conditions,Plan.defaultPlan().conditions)});

const invalidDefinitions=[
  ['wrong mode',d=>d.planMode='legacy_price'],['missing explicit mode',d=>delete d.planMode],['missing name',d=>delete d.name],['blank name',d=>d.name='  '],['long name',d=>d.name='字'.repeat(81)],['numeric name',d=>d.name=12],
  ...['entryConditions','confirmationConditions','invalidationConditions'].flatMap(key=>[[key+' missing',d=>delete d[key]],[key+' empty',d=>d[key]=[]],[key+' object status',d=>d[key]=[{text:'规则',status:'confirmed'}]],[key+' whitespace',d=>d[key]=['  ']]]),
  ['too many conditions',d=>d.applicableConditions=Array(13).fill('约定背景')],['long condition',d=>d.entryConditions=['字'.repeat(241)]],['nonarray',d=>d.entryConditions='约定背景'],
  ['invalid reviewAction',d=>d.reviewAction='sell'],['prototype enum',d=>d.reviewAction='toString'],['unknown field',d=>d.extra=true],['planType deferred',d=>d.planType='custom_watch'],['runtime phase',d=>d.phase='confirmed'],['upgrade deferred',d=>d.upgradeConditions=['规则']],
  ['price quantity injection',d=>d.priceReferences=[{type:'reference',price:35,meaning:'支撑',quantity:100}]],['negative price',d=>d.priceReferences=[{type:'reference',price:-1,meaning:'支撑'}]],['NaN price',d=>d.priceReferences=[{type:'reference',price:NaN,meaning:'支撑'}]],['Infinity price',d=>d.priceReferences=[{type:'reference',price:Infinity,meaning:'支撑'}]],['string price',d=>d.priceReferences=[{type:'reference',price:'35',meaning:'支撑'}]],['range reversed',d=>d.priceReferences=[{type:'watch_zone',from:40,to:37,meaning:'压力区'}]],['range missing end',d=>d.priceReferences=[{type:'watch_zone',from:37,meaning:'压力区'}]],['unknown price type',d=>d.priceReferences=[{type:'trigger',price:35,meaning:'支撑'}]],['reference meaning required',d=>d.priceReferences=[{type:'reference',price:35}]],['too many references',d=>d.priceReferences=Array(9).fill({type:'reference',price:35,meaning:'支撑'})],
  ['invalid allocation type',d=>d.allocationConstraint=[]],['invalid allocation null',d=>d.allocationConstraint=null],['invalid allocation number',d=>d.allocationConstraint={maxPositionPct:-1}],['allocation above 100',d=>d.allocationConstraint={maxPositionPct:101}],['allocation string coercion',d=>d.allocationConstraint={maxPositionPct:'20'}],['allocation unknown instruction',d=>d.allocationConstraint={targetPct:12}],['allocation invalid range',d=>d.allocationConstraint={targetWeightRange:20}],
  ['invalid calendar date',d=>d.validUntil='2026-02-31'],['note length',d=>d.note='字'.repeat(1001)],
  ...['当前已经确认','今天已经触发','当前阶段为确认','已进入 action_review','支撑今天失守','当前已经进入关键支撑验证阶段'].map(value=>['runtime text '+value,d=>d.entryConditions=[value]])
];
for(const [label,mutate] of invalidDefinitions)test('reject invalid Definition with zero writes: '+label,async()=>{const f=setup(),input=definition();mutate(input);assert.equal(Plan.validateWatchDefinition(input).ok,false);f.draft.definition=input;const before=clone(f.state),result=process(f);assert.equal(result.ok,false,result.message);const saved=await commit(f,result);assert.equal(saved.writes,0);assert.equal(saved.saved.writes,0);assert.deepEqual(f.state,before)});

test('optional background references allocation note and dates normalize once; trimming is no semantic edit',()=>{const checked=Plan.validateWatchDefinition({...fixtures[1],name:'  回撤支撑观察  '});assert.equal(checked.ok,true);assert.equal(checked.definition.name,'回撤支撑观察');assert.deepEqual(checked.definition.applicableConditions,[]);assert.deepEqual(checked.definition.priceReferences,[]);assert.deepEqual(checked.definition.allocationConstraint,{maxPositionPct:null,targetWeightRange:null});const p=Plan.createPlan(checked.definition,{now});assert.deepEqual(Plan.editWatchPlan(p,{...checked.definition,name:' 回撤支撑观察 '}),p)});

test('create preview and explicit confirmation commit once, no price or holdings needed',async()=>{const f=setup(),before=clone(f.state),result=process(f);assert.equal(result.confirmReady,true);assert.deepEqual(f.state,before);assert.match(Flow.renderPreview(result),/高位风险观察/);assert.match(Flow.renderPreview(result),/减仓复核/);assert.doesNotMatch(Flow.renderPreview(result),/reduce_review|SELL|triggerPrice/);const missing=await commit(f,result,{confirmed:false});assert.equal(missing.saved.status,'confirmation_required');assert.equal(missing.writes,0);const done=await commit(f,result);assert.equal(done.saved.status,'completed');assert.equal(done.saved.writes,1);assert.equal(done.writes,1);assert.deepEqual(done.adopted.stocks[0].plans[0],before.stocks[0].plans[0]);assert.equal(done.adopted.stocks[0].plans[1].planVersion,1);assert.equal(done.adopted.stocks[0].shares,0);assert.equal(done.adopted.stocks[0].capPct,20);assert.deepEqual(f.state,before);assert.equal((await commit(f,result)).writes,0)});

test('ordinary update keeps ID, creation/source/lifecycle and increments one Definition version',async()=>{const f=setup(true);f.draft.definition.name='高位结构风险观察';f.draft.definition.confirmationConditions.push('反弹修复失败');f.draft.definition.note='更明确的条件规则';const result=process(f);assert.equal(result.ok,true,result.message);const fields=Flow.diff(f.plan,result.draft.definition).map(row=>row.field);assert.deepEqual(fields,['name','confirmationConditions','note']);const html=Flow.renderPreview(result);assert.match(html,/纪律变化/);assert.match(html,/原：高位风险观察/);assert.match(html,/新：高位结构风险观察/);const {adopted,writes}=await commit(f,result),next=adopted.stocks[0].plans[1];assert.equal(writes,1);assert.equal(adopted.stocks[0].plans.length,2);assert.equal(next.id,f.plan.id);assert.equal(next.planVersion,2);assert.equal(next.createdAt,now);assert.equal(next.updatedAt,later);assert.equal(next.lastReviewedAt,f.plan.lastReviewedAt);assert.equal(next.source,f.plan.source);assert.equal(next.status,'active')});

for(const [key,value] of Object.entries({applicableConditions:['中期上升结构有效'],entryConditions:['接近约定压力区域'],confirmationConditions:['反弹修复失败'],invalidationConditions:['原结构完全修复'],reviewAction:'risk_control',priceReferences:[{type:'reference',price:35,meaning:'支撑区域参考'}],allocationConstraint:{maxPositionPct:15,targetWeightRange:'未来复核不得越过上限'},note:'保留纪律'}))test('substantive Definition field change increments once: '+key,async()=>{const f=setup(true);f.draft.definition[key]=value;const result=process(f);assert.equal(result.ok,true,result.message);assert.ok(Flow.diff(f.plan,result.draft.definition).some(row=>row.field===key));const done=await commit(f,result);assert.equal(done.adopted.stocks[0].plans[1].id,f.plan.id);assert.equal(done.adopted.stocks[0].plans[1].planVersion,2)});

for(const operation of ['update','no_change'])test('no difference is zero write: '+operation,async()=>{const f=setup(true);f.draft.operation=operation;if(operation==='no_change')f.draft.definition=null;const before=clone(f.state),result=process(f);assert.equal(result.operation,'no_change');assert.equal(result.confirmReady,false);assert.match(Flow.renderPreview(result),/不写入/);const done=await commit(f,result);assert.equal(done.writes,0);assert.equal(done.saved.status,'no_change');assert.deepEqual(f.state,before)});

const invalidTargets=[['ID',d=>d.targetPlan.id='other'],['version',d=>d.targetPlan.planVersion++],['hash',d=>d.targetPlan.snapshotHash='wrong'],['name target',d=>d.targetPlan={name:'高位风险观察'}],['symbol',d=>d.symbol='AAPL'],['session ID',d=>d.draftSessionId='stale'],['session version type',d=>d.draftSessionVersion='1'],['session hash',d=>d.draftSessionHash='wrong'],['create on existing',d=>{d.operation='create';d.targetPlan=null}],['operation',d=>d.operation='replace'],['unknown top field',d=>d.phase='forming']];
for(const [label,mutate] of invalidTargets)test('exact targeting rejects '+label,async()=>{const f=setup(true);mutate(f.draft);const result=process(f);assert.equal(result.ok,false);assert.equal((await commit(f,result)).writes,0)});
for(const raw of ['{','{"operation":','[]','null','{"schemaVersion":"state-watch-draft.v1","extra":true}'])test('malformed draft is zero-write '+raw,async()=>{const f=setup(),result=Flow.process(raw,{stock:f.s,prepared:f.prepared});assert.equal(result.ok,false);assert.equal((await commit(f,result)).writes,0)});

for(const mutate of [f=>f.s.plans.splice(1,1),f=>f.s.plans[1].planVersion++,f=>f.s.plans[1].note='changed',f=>f.s.plans[1].entryConditions=['不同规则但恶意保留旧版本'],f=>f.s.shares=100,f=>f.s.capPct=15,f=>f.s.code='000001.SZ',f=>f.s.id='wrong-stock',f=>Flow.prepare(f.s,{targetPlanId:f.plan.id}),f=>Flow.release(f.prepared)])test('live recheck rejects stale confirmation '+mutate.toString(),async()=>{const f=setup(true);f.draft.definition.note='有效更新';const result=process(f);assert.equal(result.confirmReady,true);mutate(f);const done=await commit(f,result);assert.equal(done.saved.status,'stale');assert.equal(done.writes,0)});

test('Current State and market price changes do not increment or stale Definition',async()=>{const f=setup(true);f.draft.definition.note='规则说明';const result=process(f);f.s.currentPrice=39;f.s.discussionState={current:{note:'临时市场事实'}};const next=Plan.observePriceTrigger(f.plan,39,{now:later});assert.deepEqual(next,f.plan);const done=await commit(f,result);assert.equal(done.saved.status,'completed');assert.deepEqual(done.adopted.stocks[0].discussionState,f.s.discussionState);assert.equal(done.adopted.stocks[0].plans[1].planVersion,2)});

for(const operation of ['invalidate','complete'])test(operation+' requires preview and confirm; preserves ID and Definition',async()=>{const f=setup(true);f.draft.operation=operation;f.draft.definition=null;const result=process(f);assert.equal(result.ok,true,result.message);assert.match(Flow.renderPreview(result),/生命周期/);assert.equal((await commit(f,result,{confirmed:false})).writes,0);const done=await commit(f,result),p=done.adopted.stocks[0].plans[1];assert.equal(p.id,f.plan.id);assert.equal(p.status,operation==='invalidate'?'cancelled':'completed');assert.deepEqual(Plan.watchDefinition(p),Plan.watchDefinition(f.plan));assert.equal(p.planVersion,2)});

test('ordinary state-watch workflow has no implicit replacement or split; explicit independent create gets separate ID',async()=>{const f=setup(true),prepared=Flow.prepare(f.s),draft=Flow.envelope(prepared,'create',definition(),'明确新建独立观察纪律'),result=Flow.process(JSON.stringify(draft),{stock:f.s,prepared});const done=await commit(f,result);assert.equal(done.adopted.stocks[0].plans.length,3);assert.deepEqual(done.adopted.stocks[0].plans[1],f.plan);assert.notEqual(done.adopted.stocks[0].plans[2].id,f.plan.id);assert.equal(done.adopted.stocks[0].plans[2].planVersion,1)});

test('failed persistence never adopts candidate or mutates current Plan',async()=>{const f=setup(true);f.draft.definition.note='更新失败的合成案例';const result=process(f),before=clone(f.state);let attempts=0,adoptions=0;const done=await Flow.commit(result,f.state,{saveCandidate:async()=>{attempts++;throw Error('storage rejected')},adoptCandidate:()=>adoptions++},{confirmed:true});assert.equal(done.status,'failed');assert.equal(done.writes,0);assert.equal(attempts,1);assert.equal(adoptions,0);assert.deepEqual(f.state,before)});
test('double confirmation shares pending guard; forged preview rejected',async()=>{const f=setup(),result=process(f);assert.equal((await commit(f,{...result})).writes,0);let finish;const first=Flow.commit(result,f.state,{saveCandidate:()=>new Promise(resolve=>{finish=resolve})},{confirmed:true});assert.equal((await commit(f,result)).saved.status,'busy');finish(true);assert.equal((await first).status,'completed')});
test('protected allocation cap cannot be exceeded even for add_review',()=>{const f=setup();f.draft.definition.reviewAction='add_review';f.draft.definition.allocationConstraint.maxPositionPct=21;assert.equal(process(f).ok,false)});
test('prompt clearly separates Definition, current judgment, identity and execution',()=>{const f=setup(true),prompt=Flow.prompt(f.prepared);for(const text of ['不是交易指令','当前市场判断','reduce_review 不等于 sell','保留 ID','targetPlan','snapshotHash','priceReferences'])assert.ok(prompt.includes(text),text);assert.doesNotMatch(prompt,/"quantity"|"triggerPrice"|"action"\s*:/)});

test('roundtrip normalizer export import validation and reload preserve all canonical Definition fields',()=>{const plan=Plan.createPlan({...definition(),validUntil:'2026-12-31',nextReviewDate:'2026-09-30',allocationConstraint:{maxPositionPct:10,targetWeightRange:'未来复核不超过10%'}},{now});assert.deepEqual(Plan.normalizePlan(plan),plan);const context={console,PlanV2:Plan,PlanReview:Review,SymbolIdentity:require('../src/symbol-identity')};context.globalThis=context;vm.createContext(context);for(const file of ['src/state.js','src/import-export.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);context.input=clone({stocks:[stock([plan,legacy()])],updatedAt:1});const exported=vm.runInContext('alpha3ExportSnapshot(input)',context),candidate=context.createValidatedCandidateSnapshot(JSON.parse(JSON.stringify(exported)),{requireWatchDefinition:true});assert.deepEqual(clone(candidate.stocks[0].plans[0]),plan);for(const mutate of [p=>delete p.name,p=>p.entryConditions=[],p=>p.quantity=100,p=>p.action='buy',p=>p.triggerDirection='above',p=>p.phase='forming',p=>p.schemaVersion='unknown',p=>p.planVersion=0,p=>p.status='watch_zone']){const input=clone(exported);mutate(input.stocks[0].plans[0]);assert.throws(()=>context.createValidatedCandidateSnapshot(input,{requireWatchDefinition:true}))}});

test('storage validation fails closed for invalid Definition before normalizing',()=>{const context={console,PlanV2:Plan,SymbolIdentity:require('../src/symbol-identity')};context.globalThis=context;vm.createContext(context);for(const file of ['src/storage/storage-errors.js','src/storage/storage-validation.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);const plan=Plan.createWatchPlan(definition(),{now});context.payload=JSON.stringify({stocks:[stock([plan])]});vm.runInContext('InvestmentStorage.validation.validateState(JSON.parse(payload))',context);plan.confirmationConditions=[];context.payload=JSON.stringify({stocks:[stock([plan])]});assert.throws(()=>vm.runInContext('InvestmentStorage.validation.validateState(JSON.parse(payload))',context))});

test('canonical normalizer rejects non-finite allocation before JSON cloning can turn it into null',()=>{for(const max of [NaN,Infinity,-Infinity]){const p=Plan.createWatchPlan(definition(),{now});p.allocationConstraint.maxPositionPct=max;assert.equal(Plan.validatePlan(p).ok,false);assert.throws(()=>Plan.normalizePlan(p))}});
test('raw storage cannot bypass state-watch validation with a missing schema',()=>{const context={console,PlanV2:Plan,SymbolIdentity:require('../src/symbol-identity')};context.globalThis=context;vm.createContext(context);for(const file of ['src/storage/storage-errors.js','src/storage/storage-validation.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);const p=Plan.createWatchPlan(definition(),{now});delete p.schemaVersion;context.payload=JSON.stringify({stocks:[stock([p])]});assert.throws(()=>vm.runInContext('InvestmentStorage.validation.validateState(JSON.parse(payload))',context))});

test('state-watch remains neutral in legacy execution, event, recommendation and rebalance paths',async()=>{const p=Plan.createWatchPlan(definition(),{now}),s=stock([p]),alerts=[];const context={console,PlanV2:Plan,PlanReview:Review,alert:message=>alerts.push(message),confirm:()=>{throw Error('unexpected trade confirmation')},setTimeout:()=>0,clearTimeout(){}};context.globalThis=context;context.window=context;vm.createContext(context);for(const file of ['src/state.js','src/position.js','src/rebalance.js','src/v13-core-model.js','src/v13-event-engine.js','src/v13-plan-engine.js','src/v13-recommendation-engine.js','src/ui-render.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);vm.runInContext('state='+JSON.stringify({stocks:[s],executionLog:[]}),context);await context.executePlan(s.id,p.id);assert.match(alerts.join(' '),/不能记录/);assert.equal(context.v13DerivedPlanTriggered(s,p),false);assert.equal(context.checkPlanTriggerLevel(p,{price:39},{}),'none');assert.equal(context.v13RecommendationFromPlan({},p,{price:39},{}),null);assert.equal(context.getActivePlanByType([p],'sell'),null);assert.equal(context.v13PlanDisplayCategory(p),'observe');assert.equal(context.stockUrgency(s).triggered,0);assert.deepEqual(clone(vm.runInContext('state',context)),{stocks:[s],executionLog:[]})});

test('PlanReview Portfolio Discussion carry safe Definition summaries; legacy edit requests fail',async()=>{const p=Plan.createWatchPlan(definition(),{now}),s=stock([p]),context=Review.buildContext([s],{portfolioContext:Portfolio,reviewDate:'2026-09-03'}),compact=context.stocks[0].plans[0];assert.equal(compact.name,p.name);assert.equal(compact.reviewAction,'reduce_review');assert.equal(compact.action,'observe');assert.equal(compact.triggerPrice,null);assert.match(context.expectedPlans[0].planSummary,/高位风险观察/);assert.deepEqual(Discussion.compactPlan(p).definition,Plan.watchDefinition(p));const discussionContext=Workbench.buildContext(s);assert.match(JSON.stringify(discussionContext),/高位风险观察/);let writes=0;const result=await Review.applyPlanActions({stocks:[s]},[{symbol:s.code,planId:p.id,action:'edit',patch:{triggerPrice:40}}],{saveCandidate:()=>writes++});assert.equal(result.status,'invalid');assert.equal(writes,0);const draft={planReviews:[{symbol:s.code,planId:p.id,planVersion:p.planVersion,review:{outcome:'needs_review',summary:'复核观察规则',changedPremises:[],riskFlags:[],suggestedChanges:[{field:'triggerPrice',suggestion:'提高触发价'}],confidence:'low'}}]};assert.equal(Review.process(JSON.stringify(draft),{expectedPlans:context.expectedPlans}).ok,false)});
