(function planReviewModule(root,factory){
  const planV2=typeof module==='object'&&module.exports?require('./plan-v2.js'):root&&root.PlanV2;
  const identity=typeof module==='object'&&module.exports?require('./symbol-identity.js'):root&&root.SymbolIdentity;
  const batch=typeof module==='object'&&module.exports?require('./batch-technical-review.js'):root&&root.BatchTechnicalReview;
  const api=factory(planV2,identity,batch);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.PlanReview=Object.freeze(api);
})(typeof globalThis!=='undefined'?globalThis:this,function(PlanV2,SymbolIdentity,BatchTechnicalReview){
  'use strict';

  if(!PlanV2||!SymbolIdentity||!BatchTechnicalReview)throw new Error('PlanReview dependencies are unavailable.');
  const SCHEMA_VERSION='plan-review.v1';
  const STORE_SCHEMA_VERSION='plan-review.store.v1';
  const OUTCOMES=Object.freeze(['still_valid','needs_review','likely_invalid','completed_candidate']);
  const CONFIDENCE_LEVELS=Object.freeze(['high','medium','low']);
  const SUGGESTION_FIELDS=Object.freeze(['triggerPrice','triggerDirection','conditions','allocationConstraint','nextReviewDate','validUntil','note']);
  const MUTATION_ACTIONS=Object.freeze(['reconfirm','invalidate','complete','edit']);
  const OUTCOME_LABELS=Object.freeze({still_valid:'继续有效',needs_review:'需复核',likely_invalid:'可能失效',completed_candidate:'可能已完成'});
  const REVIEW_FIELDS=Object.freeze(['outcome','summary','changedPremises','riskFlags','suggestedChanges','confidence']);
  const ITEM_FIELDS=Object.freeze(['symbol','planId','planVersion','review']);

  function object(value){return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}
  function array(value){return Array.isArray(value)?value:[]}
  function clone(value){return value===undefined?undefined:JSON.parse(JSON.stringify(value))}
  function text(value){return String(value??'').trim()}
  function canonical(value){return SymbolIdentity.canonicalSymbol(value)}
  function dateValue(value){const result=text(value);return result&&Number.isFinite(Date.parse(result))?result:null}
  function dateOnly(value){const result=dateValue(value);return result?result.slice(0,10):null}
  function nowIso(options={}){const raw=typeof options.now==='function'?options.now():options.now;return dateValue(raw)||new Date().toISOString()}
  function uniqueStrings(value,limit=12){return [...new Set(array(value).filter(item=>typeof item==='string').map(text).filter(Boolean))].slice(0,limit)}
  function reviewKey(symbol,planId){return `${canonical(symbol)}|${text(planId)}`}
  function generatedId(seed){return `planreview_${PlanV2.hash(seed||`${Date.now()}_${Math.random()}`)}_${Date.now().toString(36)}`}
  function currentPrice(stock){const direct=Number(stock&&stock.currentPrice),unit=Number(stock&&stock.lastUnitPrice),shares=Number(stock&&stock.shares),value=Number(stock&&stock.currentValue);if(direct>0)return direct;if(unit>0)return unit;if(shares>0&&value>0)return value/shares;return null}
  function planSnapshot(plan){const p=PlanV2.normalizePlan(plan);return {id:p.id,planVersion:p.planVersion,action:p.action,triggerPrice:p.triggerPrice,triggerDirection:p.triggerDirection,status:p.status,validityStatus:p.validityStatus,createdAt:p.createdAt,updatedAt:p.updatedAt,lastReviewedAt:p.lastReviewedAt,nextReviewDate:p.nextReviewDate,validUntil:p.validUntil,priceTriggerStatus:p.priceTriggerStatus,triggeredAt:p.triggeredAt,fullConditionStatus:p.fullConditionStatus,conditions:p.conditions,allocationConstraint:p.allocationConstraint,invalidationReason:p.invalidationReason,terminatedAt:p.terminatedAt,source:p.source,note:p.note,quantity:p.quantity}}
  function planSnapshotHash(plan){return `plansnap_${PlanV2.hash(planSnapshot(plan))}`}
  function normalizeSuggestion(value){const source=object(value),field=text(source.field),suggestion=text(source.suggestion);if(!SUGGESTION_FIELDS.includes(field)||!suggestion)return null;return {field,suggestion}}
  function normalizePlanReview(value={}){
    const source=object(value),outcome=OUTCOMES.includes(text(source.reviewOutcome||source.outcome))?text(source.reviewOutcome||source.outcome):'needs_review',confidence=CONFIDENCE_LEVELS.includes(text(source.confidence))?text(source.confidence):'low';
    return {reviewId:text(source.reviewId),schemaVersion:SCHEMA_VERSION,symbol:canonical(source.symbol),planId:text(source.planId),planVersion:Number.isInteger(Number(source.planVersion))&&Number(source.planVersion)>0?Number(source.planVersion):1,planSnapshotHash:text(source.planSnapshotHash),reviewDate:dateOnly(source.reviewDate),reviewedAt:dateValue(source.reviewedAt),reviewOutcome:outcome,priceTriggerStatus:PlanV2.PRICE_TRIGGER_STATUSES.includes(text(source.priceTriggerStatus))?text(source.priceTriggerStatus):'unavailable',fullConditionStatus:PlanV2.FULL_CONDITION_STATUSES.includes(text(source.fullConditionStatus))?text(source.fullConditionStatus):'unproven',changedPremises:uniqueStrings(source.changedPremises),programPremiseFacts:array(source.programPremiseFacts).map(item=>({code:text(item&&item.code),meaning:text(item&&item.meaning)})).filter(item=>item.code&&item.meaning).slice(0,16),riskFlags:uniqueStrings(source.riskFlags),suggestedChanges:array(source.suggestedChanges).map(normalizeSuggestion).filter(Boolean).slice(0,12),summary:text(source.summary),confidence,source:'ai_batch_review'};
  }
  function validatePlanReview(value){const source=object(value),review=normalizePlanReview(source),errors=[];if(source.schemaVersion!==undefined&&source.schemaVersion!==SCHEMA_VERSION)errors.push('PlanReview schema invalid');if(!review.reviewId)errors.push('reviewId missing');if(!review.symbol)errors.push('symbol missing');if(!review.planId)errors.push('planId missing');if(!Number.isInteger(Number(source.planVersion))||Number(source.planVersion)<1)errors.push('planVersion missing or invalid');if(!review.planSnapshotHash)errors.push('planSnapshotHash missing');if(!review.reviewDate||!review.reviewedAt)errors.push('review timestamps missing');if(!OUTCOMES.includes(text(source.reviewOutcome||source.outcome)))errors.push('reviewOutcome invalid');if(!CONFIDENCE_LEVELS.includes(text(source.confidence)))errors.push('confidence invalid');if(!review.summary)errors.push('summary missing');return {ok:errors.length===0,errors,review}}
  function normalizeStore(value={}){const source=object(value),currentByPlan={},history=[];Object.values(object(source.currentByPlan)).forEach(raw=>{const review=normalizePlanReview(raw),validation=validatePlanReview(review);if(validation.ok)currentByPlan[reviewKey(review.symbol,review.planId)]=review});array(source.history).forEach(raw=>{const validation=validatePlanReview(raw);if(validation.ok)history.push(validation.review)});const snapshots=array(source.snapshots).map(snapshot=>({snapshotId:text(snapshot&&snapshot.snapshotId),reviewDate:dateOnly(snapshot&&snapshot.reviewDate),reviewedAt:dateValue(snapshot&&snapshot.reviewedAt),reviews:array(snapshot&&snapshot.reviews).map(normalizePlanReview).filter(review=>validatePlanReview(review).ok)})).filter(snapshot=>snapshot.snapshotId&&snapshot.reviewDate&&snapshot.reviewedAt);return {schemaVersion:STORE_SCHEMA_VERSION,currentByPlan,history:history.slice(-240),snapshots:snapshots.slice(-60)}}
  function validateStore(value){const source=object(value),errors=[];if(source.schemaVersion!==STORE_SCHEMA_VERSION)errors.push('PlanReview store schema invalid');for(const [key,raw] of Object.entries(object(source.currentByPlan))){const result=validatePlanReview(raw);errors.push(...result.errors);if(result.ok&&key!==reviewKey(result.review.symbol,result.review.planId))errors.push('PlanReview current key mismatch')}for(const raw of array(source.history)){const result=validatePlanReview(raw);errors.push(...result.errors)}for(const snapshot of array(source.snapshots)){if(!text(snapshot&&snapshot.snapshotId)||!dateOnly(snapshot&&snapshot.reviewDate)||!dateValue(snapshot&&snapshot.reviewedAt)||!Array.isArray(snapshot&&snapshot.reviews))errors.push('PlanReview snapshot invalid');else for(const raw of snapshot.reviews){const result=validatePlanReview(raw);errors.push(...result.errors)}}return {ok:errors.length===0,errors}}
  function currentReview(store,symbol,planId){return normalizeStore(store).currentByPlan[reviewKey(symbol,planId)]||null}
  function reviewFreshness(review,plan){if(!review)return {status:'absent',reason:'尚未保存计划复核'};const normalized=normalizePlanReview(review),current=PlanV2.normalizePlan(plan);if(normalized.planId!==current.id)return {status:'stale',reason:'复核已不属于当前计划'};if(normalized.planVersion!==current.planVersion)return {status:'stale',reason:'计划已更新，旧复核不再适用'};if(normalized.planSnapshotHash!==planSnapshotHash(current))return {status:'stale',reason:'计划事实已变化'};return {status:'current',reason:'复核与当前计划版本一致'}}
  function reviewStatusForPlan(store,symbol,plan){const review=currentReview(store,symbol,plan&&plan.id),freshness=reviewFreshness(review,plan);return {review,freshness}}
  function candidatePlans(stock,reviewDate){return array(stock&&stock.plans).map(plan=>PlanV2.normalizePlan(plan)).filter(plan=>plan.status==='active'&&['active','needs_review'].includes(plan.validityStatus)).map(plan=>({plan,freshness:PlanV2.freshness(plan,reviewDate)}))}
  function selectableStocks(stocks,options={}){const reviewDate=dateOnly(options.reviewDate)||new Date().toISOString().slice(0,10);return array(stocks).filter(stock=>canonical(stock&&(stock.code||stock.symbol))&&candidatePlans(stock,reviewDate).length>0)}
  function premise(code,meaning){return {code,meaning}}
  function derivePremiseFacts(plan,stockContext,reviewDate){
    const facts=[],today=dateOnly(reviewDate),holding=object(stockContext&&stockContext.holding),allocation=object(stockContext&&stockContext.allocation),technical=object(stockContext&&stockContext.technical),p=PlanV2.normalizePlan(plan),max=Number(p.allocationConstraint&&p.allocationConstraint.maxPositionPct),weight=Number(holding.currentWeight),allocationUpper=Number(allocation.upperLimit);
    if(p.source==='migrated_legacy'&&!p.lastReviewedAt)facts.push(premise('legacy_review_unknown','历史计划缺少可靠复核日期'));
    if(p.validUntil&&today&&p.validUntil<today)facts.push(premise('valid_until_passed','计划明确有效期已过'));
    if(p.nextReviewDate&&today&&p.nextReviewDate<today)facts.push(premise('review_date_passed','已过下次复核日期'));
    if(['buy','add'].includes(p.action)&&Number.isFinite(max)&&max>0&&Number.isFinite(weight)&&weight>max)facts.push(premise('allocation_limit_exceeded',`当前权重 ${weight.toFixed(1)}% 已高于计划上限 ${max.toFixed(1)}%`));
    if(Number.isFinite(max)&&max>0&&Number.isFinite(allocationUpper)&&allocationUpper>0&&Math.abs(max-allocationUpper)>0.01)facts.push(premise('allocation_limit_changed',`当前配置上限 ${allocationUpper.toFixed(1)}% 与计划前提 ${max.toFixed(1)}% 不同`));
    if(p.priceTriggerStatus==='triggered')facts.push(premise('price_triggered','价格已触发，其他条件仍待确认'));else if(p.priceTriggerStatus==='near')facts.push(premise('price_near','当前价格接近计划价格'));
    if(!['current'].includes(text(technical.todayRelevance)))facts.push(premise('technical_not_current',technical.todayRelevance==='unavailable'?'技术资料不可用':'技术资料不足以作为当前确证'));
    for(const [key,label] of [['news','新闻'],['fundamental','基本面'],['valuation','估值'],['longTermLogic','长期逻辑']])if(object(stockContext&&stockContext[key]).todayRelevance==='unavailable')facts.push(premise(`${key}_unavailable`,`${label}资料不可用`));
    return facts;
  }
  function reviewClass(plan,reviewDate){const freshness=PlanV2.freshness(plan,reviewDate);if(freshness==='current')return 'current_active';if(freshness==='needs_review')return 'needs_review';return 'historical_only'}
  function compactPlanCandidate(plan,stock,stockContext,reviewDate,store){const authoritative=PlanV2.normalizePlan(plan),evaluated=PlanV2.normalizePlan(authoritative,{currentPrice:currentPrice(stock)}),compact=PlanV2.compactForPortfolio(evaluated,currentPrice(stock),reviewDate),prior=reviewStatusForPlan(store,stock.code||stock.symbol,authoritative);return {...compact,planSnapshotHash:planSnapshotHash(authoritative),reviewClass:reviewClass(authoritative,reviewDate),programPremiseFacts:derivePremiseFacts({...evaluated,priceTriggerStatus:compact.priceTriggerStatus},stockContext,reviewDate),priorReview:prior.review?{outcome:prior.review.reviewOutcome,reviewedAt:prior.review.reviewedAt,confidence:prior.review.confidence,freshness:prior.freshness.status}:null}}
  function buildContext(stocks,options={}){
    const selected=selectableStocks(stocks,options);if(selected.length<1)throw new Error('请至少选择一只有计划的股票。');if(selected.length>12)throw new Error('批量计划复核最多选择 12 只股票。');
    const portfolioContext=options.portfolioContext;if(!portfolioContext||typeof portfolioContext.buildPortfolioContext!=='function')throw new Error('Portfolio context helper unavailable.');const reviewDate=dateOnly(options.reviewDate)||new Date().toISOString().slice(0,10),base=portfolioContext.buildPortfolioContext(selected,{allStocks:options.allStocks||stocks,reviewDate,generatedAt:options.generatedAt,planReviewStore:options.planReviewStore}),contexts=selected.map(stock=>{const symbol=canonical(stock.code||stock.symbol),stockContext=base.stocks.find(item=>item.stock.symbol===symbol),plans=candidatePlans(stock,reviewDate).map(item=>compactPlanCandidate(item.plan,stock,stockContext,reviewDate,options.planReviewStore));return {stock:stockContext.stock,holding:stockContext.holding,allocation:stockContext.allocation,technical:stockContext.technical,news:stockContext.news,fundamental:stockContext.fundamental,valuation:stockContext.valuation,longTermLogic:stockContext.longTermLogic,plans}}),expectedPlans=contexts.flatMap(item=>item.plans.map(plan=>({symbol:item.stock.symbol,planId:plan.id,planVersion:plan.planVersion,planSnapshotHash:plan.planSnapshotHash,action:plan.action,triggerPrice:plan.triggerPrice,validityStatus:plan.validityStatus,reviewClass:plan.reviewClass,planSummary:plan.note,priceTriggerStatus:plan.priceTriggerStatus,fullConditionStatus:plan.fullConditionStatus,programPremiseFacts:plan.programPremiseFacts})));
    return {reviewDate,generatedAt:text(options.generatedAt)||new Date().toISOString(),marketContext:{status:'unavailable',meaning:'当前没有权威市场状态模块，不得臆测'},expectedPlans,stocks:contexts};
  }
  function buildRequest(stocks,options={}){const context=buildContext(stocks,options),example={planReviews:context.expectedPlans.slice(0,1).map(item=>({symbol:item.symbol,planId:item.planId,planVersion:item.planVersion,review:{outcome:'needs_review',summary:'简要说明当前证据与原计划的关系。',changedPremises:[],riskFlags:[],suggestedChanges:[{field:'note',suggestion:'建议用户重新检查计划备注'}],confidence:'low'}}))};return ['你是谨慎的批量计划复核助理。你只输出判断，不修改正式计划。','', '权威边界：','1. 程序拥有计划 ID、版本、价格触发、日期、持仓、配置和资料可用性事实，不得改写或重算。','2. 你可以判断继续有效、需复核、可能失效或可能已完成，但这不会自动改变正式计划。','3. 不得发明触发价、日期、持仓、市场状态或确定性买卖指令。','4. 价格已触发不等于完整条件已满足；除非输入明确确认，完整条件始终未证明。','5. suggestedChanges 只是自然语言建议，不是可直接应用的计划字段。','', '严格 JSON 契约：','- 只输出一个顶层对象，且只包含 planReviews 数组。','- 每个预期 Plan ID/版本必须恰好返回一次，不得缺少、重复或增加计划。','- outcome 只能为 still_valid, needs_review, likely_invalid, completed_candidate。','- confidence 只能为 high, medium, low。','- changedPremises/riskFlags 是字符串数组。','- suggestedChanges 每项只包含 field 和 suggestion；field 只能为 '+SUGGESTION_FIELDS.join(', ')+'.','', '程序事实上下文：',JSON.stringify(context,null,2),'','输出结构示例（内容必须按输入改写）：',JSON.stringify(example,null,2)].join('\n')}
  function validateReviewJudgment(value){const review=object(value),extra=Object.keys(review).filter(key=>!REVIEW_FIELDS.includes(key));if(extra.length)return {ok:false,error:`review contains unknown fields: ${extra.join(', ')}`};const outcome=text(review.outcome),confidence=text(review.confidence);if(!OUTCOMES.includes(outcome))return {ok:false,error:'review outcome invalid'};if(!CONFIDENCE_LEVELS.includes(confidence))return {ok:false,error:'review confidence invalid'};if(!text(review.summary))return {ok:false,error:'review summary missing'};for(const key of ['changedPremises','riskFlags'])if(!Array.isArray(review[key])||review[key].some(item=>typeof item!=='string'))return {ok:false,error:`review.${key} must be a string array`};if(!Array.isArray(review.suggestedChanges))return {ok:false,error:'review.suggestedChanges must be an array'};for(const suggestion of review.suggestedChanges){const source=object(suggestion),keys=Object.keys(source);if(keys.some(key=>!['field','suggestion'].includes(key))||keys.length!==2||!SUGGESTION_FIELDS.includes(text(source.field))||!text(source.suggestion))return {ok:false,error:'suggestedChanges item invalid'}}return {ok:true,review:{outcome,summary:text(review.summary),changedPremises:uniqueStrings(review.changedPremises),riskFlags:uniqueStrings(review.riskFlags),suggestedChanges:review.suggestedChanges.map(normalizeSuggestion),confidence}}}
  function invalidResult(code,message,input=null){return {ok:false,previewReady:false,writes:0,code,message,input,items:[],summary:{total:0,valid:0}}}
  function process(raw,options={}){
    const parsed=BatchTechnicalReview.parseAiBatchJsonInput(raw);if(!parsed.ok)return invalidResult('parse_error',parsed.error.reason,parsed.input);const envelope=parsed.value;if(!envelope||typeof envelope!=='object'||Array.isArray(envelope))return invalidResult('invalid_top_level','顶层必须是对象。',parsed.input);if(Object.keys(envelope).length!==1||!Array.isArray(envelope.planReviews))return invalidResult('invalid_top_level','顶层只能包含 planReviews 数组。',parsed.input);
    const expected=array(options.expectedPlans),expectedByKey=new Map(expected.map(item=>[reviewKey(item.symbol,item.planId),item])),seen=new Set(),items=[],errors=[];
    envelope.planReviews.forEach((rawItem,index)=>{const item=object(rawItem),extra=Object.keys(item).filter(key=>!ITEM_FIELDS.includes(key)),symbol=canonical(item.symbol),planId=text(item.planId),key=reviewKey(symbol,planId),expectedItem=expectedByKey.get(key);let error='';if(extra.length||Object.keys(item).length!==ITEM_FIELDS.length)error='item fields invalid';else if(!symbol||!expected.some(entry=>canonical(entry.symbol)===symbol))error='unexpected symbol';else if(!expectedItem)error='unexpected Plan ID';else if(Number(item.planVersion)!==Number(expectedItem.planVersion))error='wrong Plan version';else if(seen.has(key))error='duplicate PlanReview';const judgment=validateReviewJudgment(item.review);if(!error&&!judgment.ok)error=judgment.error;seen.add(key);const normalized={index,symbol,planId,planVersion:Number(item.planVersion),review:judgment.ok?judgment.review:null,expected:expectedItem||null,error};items.push(normalized);if(error)errors.push(`${symbol||index+1}/${planId||'-'}: ${error}`)});
    expected.forEach(item=>{const key=reviewKey(item.symbol,item.planId);if(!seen.has(key)){const error='missing selected Plan';items.push({index:items.length,symbol:canonical(item.symbol),planId:item.planId,planVersion:item.planVersion,review:null,expected:item,error});errors.push(`${item.symbol}/${item.planId}: ${error}`)}});if(!expected.length)errors.push('expected Plan list is empty');if(errors.length)return {ok:false,previewReady:false,writes:0,code:'validation_error',message:errors.join('；'),input:parsed.input,items,summary:{total:items.length,valid:items.filter(item=>!item.error).length}};return {ok:true,previewReady:true,writes:0,code:'valid',message:'复核结果已通过严格校验，尚未写入。',input:parsed.input,reviewDate:dateOnly(options.reviewDate)||new Date().toISOString().slice(0,10),items,summary:{total:items.length,valid:items.length,counts:Object.fromEntries(OUTCOMES.map(outcome=>[outcome,items.filter(item=>item.review.outcome===outcome).length]))}}}
  function eligibleEntries(result){return result&&result.ok&&result.previewReady?result.items.slice():[]}
  function buildReviewCandidate(state,result,options={}){if(!result||!result.ok||!result.previewReady)throw new Error('必须先完成有效预览。');const candidate=clone(state),store=normalizeStore(candidate.planReviews),reviewedAt=nowIso(options),reviews=result.items.map(item=>{const found=findPlan(candidate,item.symbol,item.planId),current=found.plan&&PlanV2.normalizePlan(found.plan);if(!current||current.planVersion!==item.planVersion||planSnapshotHash(current)!==item.expected.planSnapshotHash)throw new Error('预览对应的计划已经变化，请重新生成复核。');return normalizePlanReview({reviewId:generatedId(`${item.symbol}|${item.planId}|${reviewedAt}`),symbol:item.symbol,planId:item.planId,planVersion:item.planVersion,planSnapshotHash:item.expected.planSnapshotHash,reviewDate:result.reviewDate,reviewedAt,reviewOutcome:item.review.outcome,priceTriggerStatus:item.expected.priceTriggerStatus,fullConditionStatus:item.expected.fullConditionStatus,changedPremises:item.review.changedPremises,programPremiseFacts:item.expected.programPremiseFacts,riskFlags:item.review.riskFlags,suggestedChanges:item.review.suggestedChanges,summary:item.review.summary,confidence:item.review.confidence,source:'ai_batch_review'})});for(const review of reviews){const validation=validatePlanReview(review);if(!validation.ok)throw new Error(validation.errors.join(';'));const key=reviewKey(review.symbol,review.planId),prior=store.currentByPlan[key];if(prior)store.history.push(prior);store.currentByPlan[key]=review}store.history=store.history.slice(-240);store.snapshots.push({snapshotId:`planreview_snapshot_${PlanV2.hash(`${reviewedAt}|${reviews.map(item=>item.reviewId).join('|')}`)}`,reviewDate:result.reviewDate,reviewedAt,reviews:clone(reviews)});store.snapshots=store.snapshots.slice(-60);candidate.planReviews=store;return {candidate,reviews}}
  async function commitReviewSnapshot(result,state,deps={},options={}){if(!result||!result.ok||!result.previewReady)return {status:'preview_required',writes:0};if(typeof deps.saveCandidate!=='function')return {status:'failed',writes:0,error:new Error('saveCandidate unavailable')};let built;try{built=buildReviewCandidate(state,result,options)}catch(error){return {status:'invalid',writes:0,error}};try{const saved=await deps.saveCandidate(built.candidate,{critical:true}),next=saved&&saved.state?saved.state:(saved&&Array.isArray(saved.stocks)?saved:built.candidate);if(saved===false||(saved&&saved.ok===false))throw new Error('critical save failed');if(typeof deps.adoptCandidate==='function')deps.adoptCandidate(next);if(typeof deps.render==='function')deps.render();return {status:'completed',writes:1,state:next,reviews:built.reviews}}catch(error){if(typeof deps.rollback==='function')deps.rollback(state);return {status:'failed',writes:1,error}}}
  function createCommitController(){let pending=false;return Object.freeze({get pending(){return pending},run(fn){if(pending)return Promise.resolve({status:'busy'});pending=true;return Promise.resolve().then(fn).finally(()=>{pending=false})}})}
  function findPlan(state,symbol,planId){const target=canonical(symbol),stock=array(state&&state.stocks).find(item=>canonical(item&&(item.code||item.symbol))===target),index=stock?array(stock.plans).findIndex(plan=>text(plan&&plan.id)===text(planId)):-1;return {stock,index,plan:stock&&index>=0?stock.plans[index]:null}}
  function createPlanUpdateDraft(plan,review){const current=PlanV2.normalizePlan(plan),suggestions=array(review&&review.suggestedChanges).map(normalizeSuggestion).filter(Boolean);return {planId:current.id,planVersion:current.planVersion,suggestions,editableFields:SUGGESTION_FIELDS.slice(),patch:{},requiresExplicitValues:true}}
  function buildPlanEditDiff(plan,patch={},options={}){const current=PlanV2.normalizePlan(plan),next=PlanV2.applyAuthoritativeEdit(current,object(patch),options),diff=SUGGESTION_FIELDS.filter(field=>PlanV2.stable(current[field])!==PlanV2.stable(next[field])).map(field=>({field,oldValue:clone(current[field]),newValue:clone(next[field])}));return {current,next,diff,changed:diff.length>0}}
  async function applyPlanActions(state,actions,deps={},options={}){if(!Array.isArray(actions)||!actions.length)return {status:'no_actions',writes:0};if(typeof deps.saveCandidate!=='function')return {status:'failed',writes:0,error:new Error('saveCandidate unavailable')};const authoritative=state,candidate=clone(state),seen=new Set(),now=nowIso(options);try{for(const request of actions){const action=text(request&&request.action),symbol=canonical(request&&request.symbol),planId=text(request&&request.planId),key=reviewKey(symbol,planId);if(!MUTATION_ACTIONS.includes(action)||seen.has(key))throw new Error('计划变更请求无效或重复。');seen.add(key);const found=findPlan(candidate,symbol,planId);if(!found.plan)throw new Error('找不到待变更计划。');let next;if(action==='reconfirm')next=PlanV2.reconfirmPlan(found.plan,{now,nextReviewDate:request.nextReviewDate});else if(action==='invalidate'){const reason=text(request.reason);if(!reason)throw new Error('标记失效需要明确原因。');next=PlanV2.terminatePlan(found.plan,'cancelled',{now,reason})}else if(action==='complete')next=PlanV2.terminatePlan(found.plan,'completed',{now});else{const edit=buildPlanEditDiff(found.plan,request.patch,{now});if(!edit.changed)throw new Error('计划修改没有实际变化。');next=edit.next}found.stock.plans[found.index]=next;found.stock.updatedAt=Date.now()}for(const stock of candidate.stocks){stock.plans=array(stock.plans).map(plan=>PlanV2.normalizePlan(plan));const validation=PlanV2.validatePlanCollection(stock.plans);if(!validation.ok)throw new Error(validation.errors.join('；'))}}catch(error){return {status:'invalid',writes:0,error}};try{const saved=await deps.saveCandidate(candidate,{critical:true}),next=saved&&saved.state?saved.state:(saved&&Array.isArray(saved.stocks)?saved:candidate);if(saved===false||(saved&&saved.ok===false))throw new Error('critical save failed');if(typeof deps.adoptCandidate==='function')deps.adoptCandidate(next);if(typeof deps.render==='function')deps.render();return {status:'completed',writes:1,state:next}}catch(error){if(typeof deps.rollback==='function')deps.rollback(authoritative);return {status:'failed',writes:1,error}}}
  function renderPreview(result,nameForSymbol){if(!result)return '';if(!result.ok)return `<div class="hint"><b>复核结果未通过</b><div class="card-note">${escapeHtml(result.message)}</div><div class="card-note">未写入任何数据。</div></div>`;const counts=result.summary.counts||{},summary=`<div class="plan-review-counts"><span>继续有效 ${counts.still_valid||0}</span><span>需复核 ${counts.needs_review||0}</span><span>可能失效 ${counts.likely_invalid||0}</span><span>可能已完成 ${counts.completed_candidate||0}</span></div>`;return summary+result.items.map(item=>{const expected=item.expected||{},action=['buy','add'].includes(expected.action)?'加仓 / 建仓':['sell','reduce'].includes(expected.action)?'减仓 / 卖出':'观察',status=expected.reviewClass==='current_active'?'当前有效':expected.reviewClass==='needs_review'?'需要复核':'历史计划参考',planText=expected.planSummary||`${action}${expected.triggerPrice?`，价格 ${expected.triggerPrice}`:''}`;return `<div class="card plan-review-preview"><div class="card-title">${escapeHtml(typeof nameForSymbol==='function'?nameForSymbol(item.symbol):item.symbol)} · ${escapeHtml(OUTCOME_LABELS[item.review.outcome])}</div><div class="card-note">当前计划：${escapeHtml(planText)} · ${escapeHtml(status)}</div><div class="text" style="max-width:none">${escapeHtml(item.review.summary)}</div>${item.review.changedPremises.length?`<div class="card-note">前提变化：${escapeHtml(item.review.changedPremises.join('；'))}</div>`:''}${item.review.suggestedChanges.length?`<div class="card-note">建议复核：${escapeHtml(item.review.suggestedChanges.map(change=>change.suggestion).join('；'))}</div>`:''}<div class="card-note">置信度：${item.review.confidence==='high'?'高':item.review.confidence==='medium'?'中':'低'}</div></div>`}).join('')+`<div class="hint">这是 AI 复核结果，不是正式计划修改。</div>`}
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}

  return Object.freeze({SCHEMA_VERSION,STORE_SCHEMA_VERSION,OUTCOMES,CONFIDENCE_LEVELS,SUGGESTION_FIELDS,MUTATION_ACTIONS,OUTCOME_LABELS,normalizePlanReview,validatePlanReview,normalizeStore,validateStore,planSnapshot,planSnapshotHash,reviewKey,currentReview,reviewFreshness,reviewStatusForPlan,candidatePlans,selectableStocks,derivePremiseFacts,buildContext,buildRequest,process,eligibleEntries,buildReviewCandidate,commitReviewSnapshot,createCommitController,createPlanUpdateDraft,buildPlanEditDiff,applyPlanActions,renderPreview,escapeHtml,clone});
});
